/* This file is generated. Do not edit!
   see https://github.com/hpvb/dynload-wrapper (patched) for details
   generated by scripts/generate-wrapper.py 0.5
   flags: scripts/generate-wrapper.py --include include/EGL/egl.h --sys-include <EGL/egl.h> --soname libEGL.so.1 --init-name egl --output-header include_gen/egl-so_wrap.h --output-implementation src_gen/egl-so_wrap.c --ignore-other --include-dir include
*/
#include <stdint.h>

#define eglChooseConfig eglChooseConfig_dylibloader_orig_egl
#define eglCopyBuffers eglCopyBuffers_dylibloader_orig_egl
#define eglCreateContext eglCreateContext_dylibloader_orig_egl
#define eglCreatePbufferSurface eglCreatePbufferSurface_dylibloader_orig_egl
#define eglCreatePixmapSurface eglCreatePixmapSurface_dylibloader_orig_egl
#define eglCreateWindowSurface eglCreateWindowSurface_dylibloader_orig_egl
#define eglDestroyContext eglDestroyContext_dylibloader_orig_egl
#define eglDestroySurface eglDestroySurface_dylibloader_orig_egl
#define eglGetConfigAttrib eglGetConfigAttrib_dylibloader_orig_egl
#define eglGetConfigs eglGetConfigs_dylibloader_orig_egl
#define eglGetCurrentDisplay eglGetCurrentDisplay_dylibloader_orig_egl
#define eglGetCurrentSurface eglGetCurrentSurface_dylibloader_orig_egl
#define eglGetDisplay eglGetDisplay_dylibloader_orig_egl
#define eglGetError eglGetError_dylibloader_orig_egl
#define eglGetProcAddress eglGetProcAddress_dylibloader_orig_egl
#define eglInitialize eglInitialize_dylibloader_orig_egl
#define eglMakeCurrent eglMakeCurrent_dylibloader_orig_egl
#define eglQueryContext eglQueryContext_dylibloader_orig_egl
#define eglQueryString eglQueryString_dylibloader_orig_egl
#define eglQuerySurface eglQuerySurface_dylibloader_orig_egl
#define eglSwapBuffers eglSwapBuffers_dylibloader_orig_egl
#define eglTerminate eglTerminate_dylibloader_orig_egl
#define eglWaitGL eglWaitGL_dylibloader_orig_egl
#define eglWaitNative eglWaitNative_dylibloader_orig_egl
#define eglBindTexImage eglBindTexImage_dylibloader_orig_egl
#define eglReleaseTexImage eglReleaseTexImage_dylibloader_orig_egl
#define eglSurfaceAttrib eglSurfaceAttrib_dylibloader_orig_egl
#define eglSwapInterval eglSwapInterval_dylibloader_orig_egl
#define eglBindAPI eglBindAPI_dylibloader_orig_egl
#define eglQueryAPI eglQueryAPI_dylibloader_orig_egl
#define eglCreatePbufferFromClientBuffer eglCreatePbufferFromClientBuffer_dylibloader_orig_egl
#define eglReleaseThread eglReleaseThread_dylibloader_orig_egl
#define eglWaitClient eglWaitClient_dylibloader_orig_egl
#define eglGetCurrentContext eglGetCurrentContext_dylibloader_orig_egl
#define eglCreateSync eglCreateSync_dylibloader_orig_egl
#define eglDestroySync eglDestroySync_dylibloader_orig_egl
#define eglClientWaitSync eglClientWaitSync_dylibloader_orig_egl
#define eglGetSyncAttrib eglGetSyncAttrib_dylibloader_orig_egl
#define eglCreateImage eglCreateImage_dylibloader_orig_egl
#define eglDestroyImage eglDestroyImage_dylibloader_orig_egl
#define eglGetPlatformDisplay eglGetPlatformDisplay_dylibloader_orig_egl
#define eglCreatePlatformWindowSurface eglCreatePlatformWindowSurface_dylibloader_orig_egl
#define eglCreatePlatformPixmapSurface eglCreatePlatformPixmapSurface_dylibloader_orig_egl
#define eglWaitSync eglWaitSync_dylibloader_orig_egl
#include <EGL/egl.h>
#undef eglChooseConfig
#undef eglCopyBuffers
#undef eglCreateContext
#undef eglCreatePbufferSurface
#undef eglCreatePixmapSurface
#undef eglCreateWindowSurface
#undef eglDestroyContext
#undef eglDestroySurface
#undef eglGetConfigAttrib
#undef eglGetConfigs
#undef eglGetCurrentDisplay
#undef eglGetCurrentSurface
#undef eglGetDisplay
#undef eglGetError
#undef eglGetProcAddress
#undef eglInitialize
#undef eglMakeCurrent
#undef eglQueryContext
#undef eglQueryString
#undef eglQuerySurface
#undef eglSwapBuffers
#undef eglTerminate
#undef eglWaitGL
#undef eglWaitNative
#undef eglBindTexImage
#undef eglReleaseTexImage
#undef eglSurfaceAttrib
#undef eglSwapInterval
#undef eglBindAPI
#undef eglQueryAPI
#undef eglCreatePbufferFromClientBuffer
#undef eglReleaseThread
#undef eglWaitClient
#undef eglGetCurrentContext
#undef eglCreateSync
#undef eglDestroySync
#undef eglClientWaitSync
#undef eglGetSyncAttrib
#undef eglCreateImage
#undef eglDestroyImage
#undef eglGetPlatformDisplay
#undef eglCreatePlatformWindowSurface
#undef eglCreatePlatformPixmapSurface
#undef eglWaitSync
#include <dlfcn.h>
#include <stdio.h>
EGLBoolean (*eglChooseConfig_dylibloader_wrapper_egl)(EGLDisplay, const EGLint *, EGLConfig *, EGLint, EGLint *);
EGLBoolean (*eglCopyBuffers_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLNativePixmapType);
EGLContext (*eglCreateContext_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, EGLContext, const EGLint *);
EGLSurface (*eglCreatePbufferSurface_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, const EGLint *);
EGLSurface (*eglCreatePixmapSurface_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, EGLNativePixmapType, const EGLint *);
EGLSurface (*eglCreateWindowSurface_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, EGLNativeWindowType, const EGLint *);
EGLBoolean (*eglDestroyContext_dylibloader_wrapper_egl)(EGLDisplay, EGLContext);
EGLBoolean (*eglDestroySurface_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface);
EGLBoolean (*eglGetConfigAttrib_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, EGLint, EGLint *);
EGLBoolean (*eglGetConfigs_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig *, EGLint, EGLint *);
EGLDisplay (*eglGetCurrentDisplay_dylibloader_wrapper_egl)(void);
EGLSurface (*eglGetCurrentSurface_dylibloader_wrapper_egl)(EGLint);
EGLDisplay (*eglGetDisplay_dylibloader_wrapper_egl)(EGLNativeDisplayType);
EGLint (*eglGetError_dylibloader_wrapper_egl)(void);
__eglMustCastToProperFunctionPointerType (*eglGetProcAddress_dylibloader_wrapper_egl)(const char *);
EGLBoolean (*eglInitialize_dylibloader_wrapper_egl)(EGLDisplay, EGLint *, EGLint *);
EGLBoolean (*eglMakeCurrent_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLSurface, EGLContext);
EGLBoolean (*eglQueryContext_dylibloader_wrapper_egl)(EGLDisplay, EGLContext, EGLint, EGLint *);
const char *(*eglQueryString_dylibloader_wrapper_egl)(EGLDisplay, EGLint);
EGLBoolean (*eglQuerySurface_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLint, EGLint *);
EGLBoolean (*eglSwapBuffers_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface);
EGLBoolean (*eglTerminate_dylibloader_wrapper_egl)(EGLDisplay);
EGLBoolean (*eglWaitGL_dylibloader_wrapper_egl)(void);
EGLBoolean (*eglWaitNative_dylibloader_wrapper_egl)(EGLint);
EGLBoolean (*eglBindTexImage_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLint);
EGLBoolean (*eglReleaseTexImage_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLint);
EGLBoolean (*eglSurfaceAttrib_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLint, EGLint);
EGLBoolean (*eglSwapInterval_dylibloader_wrapper_egl)(EGLDisplay, EGLint);
EGLBoolean (*eglBindAPI_dylibloader_wrapper_egl)(EGLenum);
EGLenum (*eglQueryAPI_dylibloader_wrapper_egl)(void);
EGLSurface (*eglCreatePbufferFromClientBuffer_dylibloader_wrapper_egl)(EGLDisplay, EGLenum, EGLClientBuffer, EGLConfig, const EGLint *);
EGLBoolean (*eglReleaseThread_dylibloader_wrapper_egl)(void);
EGLBoolean (*eglWaitClient_dylibloader_wrapper_egl)(void);
EGLContext (*eglGetCurrentContext_dylibloader_wrapper_egl)(void);
EGLSync (*eglCreateSync_dylibloader_wrapper_egl)(EGLDisplay, EGLenum, const EGLAttrib *);
EGLBoolean (*eglDestroySync_dylibloader_wrapper_egl)(EGLDisplay, EGLSync);
EGLint (*eglClientWaitSync_dylibloader_wrapper_egl)(EGLDisplay, EGLSync, EGLint, EGLTime);
EGLBoolean (*eglGetSyncAttrib_dylibloader_wrapper_egl)(EGLDisplay, EGLSync, EGLint, EGLAttrib *);
EGLImage (*eglCreateImage_dylibloader_wrapper_egl)(EGLDisplay, EGLContext, EGLenum, EGLClientBuffer, const EGLAttrib *);
EGLBoolean (*eglDestroyImage_dylibloader_wrapper_egl)(EGLDisplay, EGLImage);
EGLDisplay (*eglGetPlatformDisplay_dylibloader_wrapper_egl)(EGLenum, void *, const EGLAttrib *);
EGLSurface (*eglCreatePlatformWindowSurface_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, void *, const EGLAttrib *);
EGLSurface (*eglCreatePlatformPixmapSurface_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, void *, const EGLAttrib *);
EGLBoolean (*eglWaitSync_dylibloader_wrapper_egl)(EGLDisplay, EGLSync, EGLint);
int initialize_egl(int verbose) {
  void *handle;
  char *error;
  handle = dlopen("libEGL.so.1", RTLD_LAZY);
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
/* eglChooseConfig */
  *(void **) (&eglChooseConfig_dylibloader_wrapper_egl) = dlsym(handle, "eglChooseConfig");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglCopyBuffers */
  *(void **) (&eglCopyBuffers_dylibloader_wrapper_egl) = dlsym(handle, "eglCopyBuffers");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglCreateContext */
  *(void **) (&eglCreateContext_dylibloader_wrapper_egl) = dlsym(handle, "eglCreateContext");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglCreatePbufferSurface */
  *(void **) (&eglCreatePbufferSurface_dylibloader_wrapper_egl) = dlsym(handle, "eglCreatePbufferSurface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglCreatePixmapSurface */
  *(void **) (&eglCreatePixmapSurface_dylibloader_wrapper_egl) = dlsym(handle, "eglCreatePixmapSurface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglCreateWindowSurface */
  *(void **) (&eglCreateWindowSurface_dylibloader_wrapper_egl) = dlsym(handle, "eglCreateWindowSurface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglDestroyContext */
  *(void **) (&eglDestroyContext_dylibloader_wrapper_egl) = dlsym(handle, "eglDestroyContext");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglDestroySurface */
  *(void **) (&eglDestroySurface_dylibloader_wrapper_egl) = dlsym(handle, "eglDestroySurface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglGetConfigAttrib */
  *(void **) (&eglGetConfigAttrib_dylibloader_wrapper_egl) = dlsym(handle, "eglGetConfigAttrib");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglGetConfigs */
  *(void **) (&eglGetConfigs_dylibloader_wrapper_egl) = dlsym(handle, "eglGetConfigs");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglGetCurrentDisplay */
  *(void **) (&eglGetCurrentDisplay_dylibloader_wrapper_egl) = dlsym(handle, "eglGetCurrentDisplay");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglGetCurrentSurface */
  *(void **) (&eglGetCurrentSurface_dylibloader_wrapper_egl) = dlsym(handle, "eglGetCurrentSurface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglGetDisplay */
  *(void **) (&eglGetDisplay_dylibloader_wrapper_egl) = dlsym(handle, "eglGetDisplay");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglGetError */
  *(void **) (&eglGetError_dylibloader_wrapper_egl) = dlsym(handle, "eglGetError");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglGetProcAddress */
  *(void **) (&eglGetProcAddress_dylibloader_wrapper_egl) = dlsym(handle, "eglGetProcAddress");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglInitialize */
  *(void **) (&eglInitialize_dylibloader_wrapper_egl) = dlsym(handle, "eglInitialize");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglMakeCurrent */
  *(void **) (&eglMakeCurrent_dylibloader_wrapper_egl) = dlsym(handle, "eglMakeCurrent");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglQueryContext */
  *(void **) (&eglQueryContext_dylibloader_wrapper_egl) = dlsym(handle, "eglQueryContext");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglQueryString */
  *(void **) (&eglQueryString_dylibloader_wrapper_egl) = dlsym(handle, "eglQueryString");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglQuerySurface */
  *(void **) (&eglQuerySurface_dylibloader_wrapper_egl) = dlsym(handle, "eglQuerySurface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglSwapBuffers */
  *(void **) (&eglSwapBuffers_dylibloader_wrapper_egl) = dlsym(handle, "eglSwapBuffers");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglTerminate */
  *(void **) (&eglTerminate_dylibloader_wrapper_egl) = dlsym(handle, "eglTerminate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglWaitGL */
  *(void **) (&eglWaitGL_dylibloader_wrapper_egl) = dlsym(handle, "eglWaitGL");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglWaitNative */
  *(void **) (&eglWaitNative_dylibloader_wrapper_egl) = dlsym(handle, "eglWaitNative");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglBindTexImage */
  *(void **) (&eglBindTexImage_dylibloader_wrapper_egl) = dlsym(handle, "eglBindTexImage");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglReleaseTexImage */
  *(void **) (&eglReleaseTexImage_dylibloader_wrapper_egl) = dlsym(handle, "eglReleaseTexImage");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglSurfaceAttrib */
  *(void **) (&eglSurfaceAttrib_dylibloader_wrapper_egl) = dlsym(handle, "eglSurfaceAttrib");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglSwapInterval */
  *(void **) (&eglSwapInterval_dylibloader_wrapper_egl) = dlsym(handle, "eglSwapInterval");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglBindAPI */
  *(void **) (&eglBindAPI_dylibloader_wrapper_egl) = dlsym(handle, "eglBindAPI");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglQueryAPI */
  *(void **) (&eglQueryAPI_dylibloader_wrapper_egl) = dlsym(handle, "eglQueryAPI");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglCreatePbufferFromClientBuffer */
  *(void **) (&eglCreatePbufferFromClientBuffer_dylibloader_wrapper_egl) = dlsym(handle, "eglCreatePbufferFromClientBuffer");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglReleaseThread */
  *(void **) (&eglReleaseThread_dylibloader_wrapper_egl) = dlsym(handle, "eglReleaseThread");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglWaitClient */
  *(void **) (&eglWaitClient_dylibloader_wrapper_egl) = dlsym(handle, "eglWaitClient");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglGetCurrentContext */
  *(void **) (&eglGetCurrentContext_dylibloader_wrapper_egl) = dlsym(handle, "eglGetCurrentContext");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglCreateSync */
  *(void **) (&eglCreateSync_dylibloader_wrapper_egl) = dlsym(handle, "eglCreateSync");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglDestroySync */
  *(void **) (&eglDestroySync_dylibloader_wrapper_egl) = dlsym(handle, "eglDestroySync");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglClientWaitSync */
  *(void **) (&eglClientWaitSync_dylibloader_wrapper_egl) = dlsym(handle, "eglClientWaitSync");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglGetSyncAttrib */
  *(void **) (&eglGetSyncAttrib_dylibloader_wrapper_egl) = dlsym(handle, "eglGetSyncAttrib");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglCreateImage */
  *(void **) (&eglCreateImage_dylibloader_wrapper_egl) = dlsym(handle, "eglCreateImage");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglDestroyImage */
  *(void **) (&eglDestroyImage_dylibloader_wrapper_egl) = dlsym(handle, "eglDestroyImage");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglGetPlatformDisplay */
  *(void **) (&eglGetPlatformDisplay_dylibloader_wrapper_egl) = dlsym(handle, "eglGetPlatformDisplay");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglCreatePlatformWindowSurface */
  *(void **) (&eglCreatePlatformWindowSurface_dylibloader_wrapper_egl) = dlsym(handle, "eglCreatePlatformWindowSurface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglCreatePlatformPixmapSurface */
  *(void **) (&eglCreatePlatformPixmapSurface_dylibloader_wrapper_egl) = dlsym(handle, "eglCreatePlatformPixmapSurface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* eglWaitSync */
  *(void **) (&eglWaitSync_dylibloader_wrapper_egl) = dlsym(handle, "eglWaitSync");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
return 0;
}
