/* This file is generated. Do not edit!
   see https://github.com/hpvb/dynload-wrapper (patched) for details
   generated by scripts/generate-wrapper.py 0.5
   flags: scripts/generate-wrapper.py --include include/fontconfig/fontconfig.h --include include/fontconfig/fcfreetype.h --sys-include freetype-so_wrap.h --sys-include <fontconfig/fontconfig.h> --sys-include <fontconfig/fcfreetype.h> --soname libfontconfig.so.1 --init-name fontconfig --output-header include_gen/fontconfig-so_wrap.h --output-implementation src_gen/fontconfig-so_wrap.c --ignore-other --include-dir include
*/
#include <stdint.h>

#define FcBlanksCreate FcBlanksCreate_dylibloader_orig_fontconfig
#define FcBlanksDestroy FcBlanksDestroy_dylibloader_orig_fontconfig
#define FcBlanksAdd FcBlanksAdd_dylibloader_orig_fontconfig
#define FcBlanksIsMember FcBlanksIsMember_dylibloader_orig_fontconfig
#define FcCacheDir FcCacheDir_dylibloader_orig_fontconfig
#define FcCacheCopySet FcCacheCopySet_dylibloader_orig_fontconfig
#define FcCacheSubdir FcCacheSubdir_dylibloader_orig_fontconfig
#define FcCacheNumSubdir FcCacheNumSubdir_dylibloader_orig_fontconfig
#define FcCacheNumFont FcCacheNumFont_dylibloader_orig_fontconfig
#define FcDirCacheUnlink FcDirCacheUnlink_dylibloader_orig_fontconfig
#define FcDirCacheValid FcDirCacheValid_dylibloader_orig_fontconfig
#define FcDirCacheClean FcDirCacheClean_dylibloader_orig_fontconfig
#define FcCacheCreateTagFile FcCacheCreateTagFile_dylibloader_orig_fontconfig
#define FcConfigHome FcConfigHome_dylibloader_orig_fontconfig
#define FcConfigEnableHome FcConfigEnableHome_dylibloader_orig_fontconfig
#define FcConfigFilename FcConfigFilename_dylibloader_orig_fontconfig
#define FcConfigCreate FcConfigCreate_dylibloader_orig_fontconfig
#define FcConfigReference FcConfigReference_dylibloader_orig_fontconfig
#define FcConfigDestroy FcConfigDestroy_dylibloader_orig_fontconfig
#define FcConfigSetCurrent FcConfigSetCurrent_dylibloader_orig_fontconfig
#define FcConfigGetCurrent FcConfigGetCurrent_dylibloader_orig_fontconfig
#define FcConfigUptoDate FcConfigUptoDate_dylibloader_orig_fontconfig
#define FcConfigBuildFonts FcConfigBuildFonts_dylibloader_orig_fontconfig
#define FcConfigGetFontDirs FcConfigGetFontDirs_dylibloader_orig_fontconfig
#define FcConfigGetConfigDirs FcConfigGetConfigDirs_dylibloader_orig_fontconfig
#define FcConfigGetConfigFiles FcConfigGetConfigFiles_dylibloader_orig_fontconfig
#define FcConfigGetCache FcConfigGetCache_dylibloader_orig_fontconfig
#define FcConfigGetBlanks FcConfigGetBlanks_dylibloader_orig_fontconfig
#define FcConfigGetCacheDirs FcConfigGetCacheDirs_dylibloader_orig_fontconfig
#define FcConfigGetRescanInterval FcConfigGetRescanInterval_dylibloader_orig_fontconfig
#define FcConfigSetRescanInterval FcConfigSetRescanInterval_dylibloader_orig_fontconfig
#define FcConfigGetFonts FcConfigGetFonts_dylibloader_orig_fontconfig
#define FcConfigAppFontAddFile FcConfigAppFontAddFile_dylibloader_orig_fontconfig
#define FcConfigAppFontAddDir FcConfigAppFontAddDir_dylibloader_orig_fontconfig
#define FcConfigAppFontClear FcConfigAppFontClear_dylibloader_orig_fontconfig
#define FcConfigSubstituteWithPat FcConfigSubstituteWithPat_dylibloader_orig_fontconfig
#define FcConfigSubstitute FcConfigSubstitute_dylibloader_orig_fontconfig
#define FcConfigGetSysRoot FcConfigGetSysRoot_dylibloader_orig_fontconfig
#define FcConfigSetSysRoot FcConfigSetSysRoot_dylibloader_orig_fontconfig
#define FcCharSetCreate FcCharSetCreate_dylibloader_orig_fontconfig
#define FcCharSetNew FcCharSetNew_dylibloader_orig_fontconfig
#define FcCharSetDestroy FcCharSetDestroy_dylibloader_orig_fontconfig
#define FcCharSetAddChar FcCharSetAddChar_dylibloader_orig_fontconfig
#define FcCharSetDelChar FcCharSetDelChar_dylibloader_orig_fontconfig
#define FcCharSetCopy FcCharSetCopy_dylibloader_orig_fontconfig
#define FcCharSetEqual FcCharSetEqual_dylibloader_orig_fontconfig
#define FcCharSetIntersect FcCharSetIntersect_dylibloader_orig_fontconfig
#define FcCharSetUnion FcCharSetUnion_dylibloader_orig_fontconfig
#define FcCharSetSubtract FcCharSetSubtract_dylibloader_orig_fontconfig
#define FcCharSetMerge FcCharSetMerge_dylibloader_orig_fontconfig
#define FcCharSetHasChar FcCharSetHasChar_dylibloader_orig_fontconfig
#define FcCharSetCount FcCharSetCount_dylibloader_orig_fontconfig
#define FcCharSetIntersectCount FcCharSetIntersectCount_dylibloader_orig_fontconfig
#define FcCharSetSubtractCount FcCharSetSubtractCount_dylibloader_orig_fontconfig
#define FcCharSetIsSubset FcCharSetIsSubset_dylibloader_orig_fontconfig
#define FcCharSetFirstPage FcCharSetFirstPage_dylibloader_orig_fontconfig
#define FcCharSetNextPage FcCharSetNextPage_dylibloader_orig_fontconfig
#define FcCharSetCoverage FcCharSetCoverage_dylibloader_orig_fontconfig
#define FcValuePrint FcValuePrint_dylibloader_orig_fontconfig
#define FcPatternPrint FcPatternPrint_dylibloader_orig_fontconfig
#define FcFontSetPrint FcFontSetPrint_dylibloader_orig_fontconfig
#define FcGetDefaultLangs FcGetDefaultLangs_dylibloader_orig_fontconfig
#define FcDefaultSubstitute FcDefaultSubstitute_dylibloader_orig_fontconfig
#define FcFileIsDir FcFileIsDir_dylibloader_orig_fontconfig
#define FcFileScan FcFileScan_dylibloader_orig_fontconfig
#define FcDirScan FcDirScan_dylibloader_orig_fontconfig
#define FcDirSave FcDirSave_dylibloader_orig_fontconfig
#define FcDirCacheLoad FcDirCacheLoad_dylibloader_orig_fontconfig
#define FcDirCacheRescan FcDirCacheRescan_dylibloader_orig_fontconfig
#define FcDirCacheRead FcDirCacheRead_dylibloader_orig_fontconfig
#define FcDirCacheLoadFile FcDirCacheLoadFile_dylibloader_orig_fontconfig
#define FcDirCacheUnload FcDirCacheUnload_dylibloader_orig_fontconfig
#define FcFreeTypeQuery FcFreeTypeQuery_dylibloader_orig_fontconfig
#define FcFontSetCreate FcFontSetCreate_dylibloader_orig_fontconfig
#define FcFontSetDestroy FcFontSetDestroy_dylibloader_orig_fontconfig
#define FcFontSetAdd FcFontSetAdd_dylibloader_orig_fontconfig
#define FcInitLoadConfig FcInitLoadConfig_dylibloader_orig_fontconfig
#define FcInitLoadConfigAndFonts FcInitLoadConfigAndFonts_dylibloader_orig_fontconfig
#define FcInit FcInit_dylibloader_orig_fontconfig
#define FcFini FcFini_dylibloader_orig_fontconfig
#define FcGetVersion FcGetVersion_dylibloader_orig_fontconfig
#define FcInitReinitialize FcInitReinitialize_dylibloader_orig_fontconfig
#define FcInitBringUptoDate FcInitBringUptoDate_dylibloader_orig_fontconfig
#define FcGetLangs FcGetLangs_dylibloader_orig_fontconfig
#define FcLangNormalize FcLangNormalize_dylibloader_orig_fontconfig
#define FcLangGetCharSet FcLangGetCharSet_dylibloader_orig_fontconfig
#define FcLangSetCreate FcLangSetCreate_dylibloader_orig_fontconfig
#define FcLangSetDestroy FcLangSetDestroy_dylibloader_orig_fontconfig
#define FcLangSetCopy FcLangSetCopy_dylibloader_orig_fontconfig
#define FcLangSetAdd FcLangSetAdd_dylibloader_orig_fontconfig
#define FcLangSetDel FcLangSetDel_dylibloader_orig_fontconfig
#define FcLangSetHasLang FcLangSetHasLang_dylibloader_orig_fontconfig
#define FcLangSetCompare FcLangSetCompare_dylibloader_orig_fontconfig
#define FcLangSetContains FcLangSetContains_dylibloader_orig_fontconfig
#define FcLangSetEqual FcLangSetEqual_dylibloader_orig_fontconfig
#define FcLangSetHash FcLangSetHash_dylibloader_orig_fontconfig
#define FcLangSetGetLangs FcLangSetGetLangs_dylibloader_orig_fontconfig
#define FcLangSetUnion FcLangSetUnion_dylibloader_orig_fontconfig
#define FcLangSetSubtract FcLangSetSubtract_dylibloader_orig_fontconfig
#define FcObjectSetCreate FcObjectSetCreate_dylibloader_orig_fontconfig
#define FcObjectSetAdd FcObjectSetAdd_dylibloader_orig_fontconfig
#define FcObjectSetDestroy FcObjectSetDestroy_dylibloader_orig_fontconfig
#define FcObjectSetVaBuild FcObjectSetVaBuild_dylibloader_orig_fontconfig
#define FcObjectSetBuild FcObjectSetBuild_dylibloader_orig_fontconfig
#define FcFontSetList FcFontSetList_dylibloader_orig_fontconfig
#define FcFontList FcFontList_dylibloader_orig_fontconfig
#define FcAtomicCreate FcAtomicCreate_dylibloader_orig_fontconfig
#define FcAtomicLock FcAtomicLock_dylibloader_orig_fontconfig
#define FcAtomicNewFile FcAtomicNewFile_dylibloader_orig_fontconfig
#define FcAtomicOrigFile FcAtomicOrigFile_dylibloader_orig_fontconfig
#define FcAtomicReplaceOrig FcAtomicReplaceOrig_dylibloader_orig_fontconfig
#define FcAtomicDeleteNew FcAtomicDeleteNew_dylibloader_orig_fontconfig
#define FcAtomicUnlock FcAtomicUnlock_dylibloader_orig_fontconfig
#define FcAtomicDestroy FcAtomicDestroy_dylibloader_orig_fontconfig
#define FcFontSetMatch FcFontSetMatch_dylibloader_orig_fontconfig
#define FcFontMatch FcFontMatch_dylibloader_orig_fontconfig
#define FcFontRenderPrepare FcFontRenderPrepare_dylibloader_orig_fontconfig
#define FcFontSetSort FcFontSetSort_dylibloader_orig_fontconfig
#define FcFontSort FcFontSort_dylibloader_orig_fontconfig
#define FcFontSetSortDestroy FcFontSetSortDestroy_dylibloader_orig_fontconfig
#define FcMatrixCopy FcMatrixCopy_dylibloader_orig_fontconfig
#define FcMatrixEqual FcMatrixEqual_dylibloader_orig_fontconfig
#define FcMatrixMultiply FcMatrixMultiply_dylibloader_orig_fontconfig
#define FcMatrixRotate FcMatrixRotate_dylibloader_orig_fontconfig
#define FcMatrixScale FcMatrixScale_dylibloader_orig_fontconfig
#define FcMatrixShear FcMatrixShear_dylibloader_orig_fontconfig
#define FcNameRegisterObjectTypes FcNameRegisterObjectTypes_dylibloader_orig_fontconfig
#define FcNameUnregisterObjectTypes FcNameUnregisterObjectTypes_dylibloader_orig_fontconfig
#define FcNameGetObjectType FcNameGetObjectType_dylibloader_orig_fontconfig
#define FcNameRegisterConstants FcNameRegisterConstants_dylibloader_orig_fontconfig
#define FcNameUnregisterConstants FcNameUnregisterConstants_dylibloader_orig_fontconfig
#define FcNameGetConstant FcNameGetConstant_dylibloader_orig_fontconfig
#define FcNameConstant FcNameConstant_dylibloader_orig_fontconfig
#define FcNameParse FcNameParse_dylibloader_orig_fontconfig
#define FcNameUnparse FcNameUnparse_dylibloader_orig_fontconfig
#define FcPatternCreate FcPatternCreate_dylibloader_orig_fontconfig
#define FcPatternDuplicate FcPatternDuplicate_dylibloader_orig_fontconfig
#define FcPatternReference FcPatternReference_dylibloader_orig_fontconfig
#define FcPatternFilter FcPatternFilter_dylibloader_orig_fontconfig
#define FcValueDestroy FcValueDestroy_dylibloader_orig_fontconfig
#define FcValueEqual FcValueEqual_dylibloader_orig_fontconfig
#define FcValueSave FcValueSave_dylibloader_orig_fontconfig
#define FcPatternDestroy FcPatternDestroy_dylibloader_orig_fontconfig
#define FcPatternEqual FcPatternEqual_dylibloader_orig_fontconfig
#define FcPatternEqualSubset FcPatternEqualSubset_dylibloader_orig_fontconfig
#define FcPatternHash FcPatternHash_dylibloader_orig_fontconfig
#define FcPatternAdd FcPatternAdd_dylibloader_orig_fontconfig
#define FcPatternAddWeak FcPatternAddWeak_dylibloader_orig_fontconfig
#define FcPatternGet FcPatternGet_dylibloader_orig_fontconfig
#define FcPatternGetWithBinding FcPatternGetWithBinding_dylibloader_orig_fontconfig
#define FcPatternDel FcPatternDel_dylibloader_orig_fontconfig
#define FcPatternRemove FcPatternRemove_dylibloader_orig_fontconfig
#define FcPatternAddInteger FcPatternAddInteger_dylibloader_orig_fontconfig
#define FcPatternAddDouble FcPatternAddDouble_dylibloader_orig_fontconfig
#define FcPatternAddString FcPatternAddString_dylibloader_orig_fontconfig
#define FcPatternAddMatrix FcPatternAddMatrix_dylibloader_orig_fontconfig
#define FcPatternAddCharSet FcPatternAddCharSet_dylibloader_orig_fontconfig
#define FcPatternAddBool FcPatternAddBool_dylibloader_orig_fontconfig
#define FcPatternAddLangSet FcPatternAddLangSet_dylibloader_orig_fontconfig
#define FcPatternAddRange FcPatternAddRange_dylibloader_orig_fontconfig
#define FcPatternGetInteger FcPatternGetInteger_dylibloader_orig_fontconfig
#define FcPatternGetDouble FcPatternGetDouble_dylibloader_orig_fontconfig
#define FcPatternGetString FcPatternGetString_dylibloader_orig_fontconfig
#define FcPatternGetMatrix FcPatternGetMatrix_dylibloader_orig_fontconfig
#define FcPatternGetCharSet FcPatternGetCharSet_dylibloader_orig_fontconfig
#define FcPatternGetBool FcPatternGetBool_dylibloader_orig_fontconfig
#define FcPatternGetLangSet FcPatternGetLangSet_dylibloader_orig_fontconfig
#define FcPatternGetRange FcPatternGetRange_dylibloader_orig_fontconfig
#define FcPatternVaBuild FcPatternVaBuild_dylibloader_orig_fontconfig
#define FcPatternBuild FcPatternBuild_dylibloader_orig_fontconfig
#define FcPatternFormat FcPatternFormat_dylibloader_orig_fontconfig
#define FcRangeCreateDouble FcRangeCreateDouble_dylibloader_orig_fontconfig
#define FcRangeCreateInteger FcRangeCreateInteger_dylibloader_orig_fontconfig
#define FcRangeDestroy FcRangeDestroy_dylibloader_orig_fontconfig
#define FcRangeCopy FcRangeCopy_dylibloader_orig_fontconfig
#define FcRangeGetDouble FcRangeGetDouble_dylibloader_orig_fontconfig
#define FcWeightFromOpenType FcWeightFromOpenType_dylibloader_orig_fontconfig
#define FcWeightToOpenType FcWeightToOpenType_dylibloader_orig_fontconfig
#define FcStrCopy FcStrCopy_dylibloader_orig_fontconfig
#define FcStrCopyFilename FcStrCopyFilename_dylibloader_orig_fontconfig
#define FcStrPlus FcStrPlus_dylibloader_orig_fontconfig
#define FcStrFree FcStrFree_dylibloader_orig_fontconfig
#define FcStrDowncase FcStrDowncase_dylibloader_orig_fontconfig
#define FcStrCmpIgnoreCase FcStrCmpIgnoreCase_dylibloader_orig_fontconfig
#define FcStrCmp FcStrCmp_dylibloader_orig_fontconfig
#define FcStrStrIgnoreCase FcStrStrIgnoreCase_dylibloader_orig_fontconfig
#define FcStrStr FcStrStr_dylibloader_orig_fontconfig
#define FcUtf8ToUcs4 FcUtf8ToUcs4_dylibloader_orig_fontconfig
#define FcUtf8Len FcUtf8Len_dylibloader_orig_fontconfig
#define FcUcs4ToUtf8 FcUcs4ToUtf8_dylibloader_orig_fontconfig
#define FcUtf16ToUcs4 FcUtf16ToUcs4_dylibloader_orig_fontconfig
#define FcUtf16Len FcUtf16Len_dylibloader_orig_fontconfig
#define FcStrDirname FcStrDirname_dylibloader_orig_fontconfig
#define FcStrBasename FcStrBasename_dylibloader_orig_fontconfig
#define FcStrSetCreate FcStrSetCreate_dylibloader_orig_fontconfig
#define FcStrSetMember FcStrSetMember_dylibloader_orig_fontconfig
#define FcStrSetEqual FcStrSetEqual_dylibloader_orig_fontconfig
#define FcStrSetAdd FcStrSetAdd_dylibloader_orig_fontconfig
#define FcStrSetAddFilename FcStrSetAddFilename_dylibloader_orig_fontconfig
#define FcStrSetDel FcStrSetDel_dylibloader_orig_fontconfig
#define FcStrSetDestroy FcStrSetDestroy_dylibloader_orig_fontconfig
#define FcStrListCreate FcStrListCreate_dylibloader_orig_fontconfig
#define FcStrListFirst FcStrListFirst_dylibloader_orig_fontconfig
#define FcStrListNext FcStrListNext_dylibloader_orig_fontconfig
#define FcStrListDone FcStrListDone_dylibloader_orig_fontconfig
#define FcConfigParseAndLoad FcConfigParseAndLoad_dylibloader_orig_fontconfig
#define FcConfigParseAndLoadFromMemory FcConfigParseAndLoadFromMemory_dylibloader_orig_fontconfig
#define FcFreeTypeCharIndex FcFreeTypeCharIndex_dylibloader_orig_fontconfig
#define FcFreeTypeCharSetAndSpacing FcFreeTypeCharSetAndSpacing_dylibloader_orig_fontconfig
#define FcFreeTypeCharSet FcFreeTypeCharSet_dylibloader_orig_fontconfig
#define FcPatternGetFTFace FcPatternGetFTFace_dylibloader_orig_fontconfig
#define FcPatternAddFTFace FcPatternAddFTFace_dylibloader_orig_fontconfig
#define FcFreeTypeQueryFace FcFreeTypeQueryFace_dylibloader_orig_fontconfig
#include "freetype-so_wrap.h"
#include <fontconfig/fontconfig.h>
#include <fontconfig/fcfreetype.h>
#undef FcBlanksCreate
#undef FcBlanksDestroy
#undef FcBlanksAdd
#undef FcBlanksIsMember
#undef FcCacheDir
#undef FcCacheCopySet
#undef FcCacheSubdir
#undef FcCacheNumSubdir
#undef FcCacheNumFont
#undef FcDirCacheUnlink
#undef FcDirCacheValid
#undef FcDirCacheClean
#undef FcCacheCreateTagFile
#undef FcConfigHome
#undef FcConfigEnableHome
#undef FcConfigFilename
#undef FcConfigCreate
#undef FcConfigReference
#undef FcConfigDestroy
#undef FcConfigSetCurrent
#undef FcConfigGetCurrent
#undef FcConfigUptoDate
#undef FcConfigBuildFonts
#undef FcConfigGetFontDirs
#undef FcConfigGetConfigDirs
#undef FcConfigGetConfigFiles
#undef FcConfigGetCache
#undef FcConfigGetBlanks
#undef FcConfigGetCacheDirs
#undef FcConfigGetRescanInterval
#undef FcConfigSetRescanInterval
#undef FcConfigGetFonts
#undef FcConfigAppFontAddFile
#undef FcConfigAppFontAddDir
#undef FcConfigAppFontClear
#undef FcConfigSubstituteWithPat
#undef FcConfigSubstitute
#undef FcConfigGetSysRoot
#undef FcConfigSetSysRoot
#undef FcCharSetCreate
#undef FcCharSetNew
#undef FcCharSetDestroy
#undef FcCharSetAddChar
#undef FcCharSetDelChar
#undef FcCharSetCopy
#undef FcCharSetEqual
#undef FcCharSetIntersect
#undef FcCharSetUnion
#undef FcCharSetSubtract
#undef FcCharSetMerge
#undef FcCharSetHasChar
#undef FcCharSetCount
#undef FcCharSetIntersectCount
#undef FcCharSetSubtractCount
#undef FcCharSetIsSubset
#undef FcCharSetFirstPage
#undef FcCharSetNextPage
#undef FcCharSetCoverage
#undef FcValuePrint
#undef FcPatternPrint
#undef FcFontSetPrint
#undef FcGetDefaultLangs
#undef FcDefaultSubstitute
#undef FcFileIsDir
#undef FcFileScan
#undef FcDirScan
#undef FcDirSave
#undef FcDirCacheLoad
#undef FcDirCacheRescan
#undef FcDirCacheRead
#undef FcDirCacheLoadFile
#undef FcDirCacheUnload
#undef FcFreeTypeQuery
#undef FcFontSetCreate
#undef FcFontSetDestroy
#undef FcFontSetAdd
#undef FcInitLoadConfig
#undef FcInitLoadConfigAndFonts
#undef FcInit
#undef FcFini
#undef FcGetVersion
#undef FcInitReinitialize
#undef FcInitBringUptoDate
#undef FcGetLangs
#undef FcLangNormalize
#undef FcLangGetCharSet
#undef FcLangSetCreate
#undef FcLangSetDestroy
#undef FcLangSetCopy
#undef FcLangSetAdd
#undef FcLangSetDel
#undef FcLangSetHasLang
#undef FcLangSetCompare
#undef FcLangSetContains
#undef FcLangSetEqual
#undef FcLangSetHash
#undef FcLangSetGetLangs
#undef FcLangSetUnion
#undef FcLangSetSubtract
#undef FcObjectSetCreate
#undef FcObjectSetAdd
#undef FcObjectSetDestroy
#undef FcObjectSetVaBuild
#undef FcObjectSetBuild
#undef FcFontSetList
#undef FcFontList
#undef FcAtomicCreate
#undef FcAtomicLock
#undef FcAtomicNewFile
#undef FcAtomicOrigFile
#undef FcAtomicReplaceOrig
#undef FcAtomicDeleteNew
#undef FcAtomicUnlock
#undef FcAtomicDestroy
#undef FcFontSetMatch
#undef FcFontMatch
#undef FcFontRenderPrepare
#undef FcFontSetSort
#undef FcFontSort
#undef FcFontSetSortDestroy
#undef FcMatrixCopy
#undef FcMatrixEqual
#undef FcMatrixMultiply
#undef FcMatrixRotate
#undef FcMatrixScale
#undef FcMatrixShear
#undef FcNameRegisterObjectTypes
#undef FcNameUnregisterObjectTypes
#undef FcNameGetObjectType
#undef FcNameRegisterConstants
#undef FcNameUnregisterConstants
#undef FcNameGetConstant
#undef FcNameConstant
#undef FcNameParse
#undef FcNameUnparse
#undef FcPatternCreate
#undef FcPatternDuplicate
#undef FcPatternReference
#undef FcPatternFilter
#undef FcValueDestroy
#undef FcValueEqual
#undef FcValueSave
#undef FcPatternDestroy
#undef FcPatternEqual
#undef FcPatternEqualSubset
#undef FcPatternHash
#undef FcPatternAdd
#undef FcPatternAddWeak
#undef FcPatternGet
#undef FcPatternGetWithBinding
#undef FcPatternDel
#undef FcPatternRemove
#undef FcPatternAddInteger
#undef FcPatternAddDouble
#undef FcPatternAddString
#undef FcPatternAddMatrix
#undef FcPatternAddCharSet
#undef FcPatternAddBool
#undef FcPatternAddLangSet
#undef FcPatternAddRange
#undef FcPatternGetInteger
#undef FcPatternGetDouble
#undef FcPatternGetString
#undef FcPatternGetMatrix
#undef FcPatternGetCharSet
#undef FcPatternGetBool
#undef FcPatternGetLangSet
#undef FcPatternGetRange
#undef FcPatternVaBuild
#undef FcPatternBuild
#undef FcPatternFormat
#undef FcRangeCreateDouble
#undef FcRangeCreateInteger
#undef FcRangeDestroy
#undef FcRangeCopy
#undef FcRangeGetDouble
#undef FcWeightFromOpenType
#undef FcWeightToOpenType
#undef FcStrCopy
#undef FcStrCopyFilename
#undef FcStrPlus
#undef FcStrFree
#undef FcStrDowncase
#undef FcStrCmpIgnoreCase
#undef FcStrCmp
#undef FcStrStrIgnoreCase
#undef FcStrStr
#undef FcUtf8ToUcs4
#undef FcUtf8Len
#undef FcUcs4ToUtf8
#undef FcUtf16ToUcs4
#undef FcUtf16Len
#undef FcStrDirname
#undef FcStrBasename
#undef FcStrSetCreate
#undef FcStrSetMember
#undef FcStrSetEqual
#undef FcStrSetAdd
#undef FcStrSetAddFilename
#undef FcStrSetDel
#undef FcStrSetDestroy
#undef FcStrListCreate
#undef FcStrListFirst
#undef FcStrListNext
#undef FcStrListDone
#undef FcConfigParseAndLoad
#undef FcConfigParseAndLoadFromMemory
#undef FcFreeTypeCharIndex
#undef FcFreeTypeCharSetAndSpacing
#undef FcFreeTypeCharSet
#undef FcPatternGetFTFace
#undef FcPatternAddFTFace
#undef FcFreeTypeQueryFace
#include <dlfcn.h>
#include <stdio.h>
FcBlanks *(*FcBlanksCreate_dylibloader_wrapper_fontconfig)(void);
void (*FcBlanksDestroy_dylibloader_wrapper_fontconfig)(FcBlanks *);
FcBool (*FcBlanksAdd_dylibloader_wrapper_fontconfig)(FcBlanks *, FcChar32);
FcBool (*FcBlanksIsMember_dylibloader_wrapper_fontconfig)(FcBlanks *, FcChar32);
const FcChar8 *(*FcCacheDir_dylibloader_wrapper_fontconfig)(const FcCache *);
FcFontSet *(*FcCacheCopySet_dylibloader_wrapper_fontconfig)(const FcCache *);
const FcChar8 *(*FcCacheSubdir_dylibloader_wrapper_fontconfig)(const FcCache *, int);
int (*FcCacheNumSubdir_dylibloader_wrapper_fontconfig)(const FcCache *);
int (*FcCacheNumFont_dylibloader_wrapper_fontconfig)(const FcCache *);
FcBool (*FcDirCacheUnlink_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcConfig *);
FcBool (*FcDirCacheValid_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcBool (*FcDirCacheClean_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcBool);
void (*FcCacheCreateTagFile_dylibloader_wrapper_fontconfig)(const FcConfig *);
FcChar8 *(*FcConfigHome_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcConfigEnableHome_dylibloader_wrapper_fontconfig)(FcBool);
FcChar8 *(*FcConfigFilename_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcConfig *(*FcConfigCreate_dylibloader_wrapper_fontconfig)(void);
FcConfig *(*FcConfigReference_dylibloader_wrapper_fontconfig)(FcConfig *);
void (*FcConfigDestroy_dylibloader_wrapper_fontconfig)(FcConfig *);
FcBool (*FcConfigSetCurrent_dylibloader_wrapper_fontconfig)(FcConfig *);
FcConfig *(*FcConfigGetCurrent_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcConfigUptoDate_dylibloader_wrapper_fontconfig)(FcConfig *);
FcBool (*FcConfigBuildFonts_dylibloader_wrapper_fontconfig)(FcConfig *);
FcStrList *(*FcConfigGetFontDirs_dylibloader_wrapper_fontconfig)(FcConfig *);
FcStrList *(*FcConfigGetConfigDirs_dylibloader_wrapper_fontconfig)(FcConfig *);
FcStrList *(*FcConfigGetConfigFiles_dylibloader_wrapper_fontconfig)(FcConfig *);
FcChar8 *(*FcConfigGetCache_dylibloader_wrapper_fontconfig)(FcConfig *);
FcBlanks *(*FcConfigGetBlanks_dylibloader_wrapper_fontconfig)(FcConfig *);
FcStrList *(*FcConfigGetCacheDirs_dylibloader_wrapper_fontconfig)(const FcConfig *);
int (*FcConfigGetRescanInterval_dylibloader_wrapper_fontconfig)(FcConfig *);
FcBool (*FcConfigSetRescanInterval_dylibloader_wrapper_fontconfig)(FcConfig *, int);
FcFontSet *(*FcConfigGetFonts_dylibloader_wrapper_fontconfig)(FcConfig *, FcSetName);
FcBool (*FcConfigAppFontAddFile_dylibloader_wrapper_fontconfig)(FcConfig *, const FcChar8 *);
FcBool (*FcConfigAppFontAddDir_dylibloader_wrapper_fontconfig)(FcConfig *, const FcChar8 *);
void (*FcConfigAppFontClear_dylibloader_wrapper_fontconfig)(FcConfig *);
FcBool (*FcConfigSubstituteWithPat_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcPattern *, FcMatchKind);
FcBool (*FcConfigSubstitute_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcMatchKind);
const FcChar8 *(*FcConfigGetSysRoot_dylibloader_wrapper_fontconfig)(const FcConfig *);
void (*FcConfigSetSysRoot_dylibloader_wrapper_fontconfig)(FcConfig *, const FcChar8 *);
FcCharSet *(*FcCharSetCreate_dylibloader_wrapper_fontconfig)(void);
FcCharSet *(*FcCharSetNew_dylibloader_wrapper_fontconfig)(void);
void (*FcCharSetDestroy_dylibloader_wrapper_fontconfig)(FcCharSet *);
FcBool (*FcCharSetAddChar_dylibloader_wrapper_fontconfig)(FcCharSet *, FcChar32);
FcBool (*FcCharSetDelChar_dylibloader_wrapper_fontconfig)(FcCharSet *, FcChar32);
FcCharSet *(*FcCharSetCopy_dylibloader_wrapper_fontconfig)(FcCharSet *);
FcBool (*FcCharSetEqual_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcCharSet *(*FcCharSetIntersect_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcCharSet *(*FcCharSetUnion_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcCharSet *(*FcCharSetSubtract_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcBool (*FcCharSetMerge_dylibloader_wrapper_fontconfig)(FcCharSet *, const FcCharSet *, FcBool *);
FcBool (*FcCharSetHasChar_dylibloader_wrapper_fontconfig)(const FcCharSet *, FcChar32);
FcChar32 (*FcCharSetCount_dylibloader_wrapper_fontconfig)(const FcCharSet *);
FcChar32 (*FcCharSetIntersectCount_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcChar32 (*FcCharSetSubtractCount_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcBool (*FcCharSetIsSubset_dylibloader_wrapper_fontconfig)(const FcCharSet *, const FcCharSet *);
FcChar32 (*FcCharSetFirstPage_dylibloader_wrapper_fontconfig)(const FcCharSet *, FcChar32 [256 / 32], FcChar32 *);
FcChar32 (*FcCharSetNextPage_dylibloader_wrapper_fontconfig)(const FcCharSet *, FcChar32 [256 / 32], FcChar32 *);
FcChar32 (*FcCharSetCoverage_dylibloader_wrapper_fontconfig)(const FcCharSet *, FcChar32, FcChar32 *);
void (*FcValuePrint_dylibloader_wrapper_fontconfig)(const FcValue);
void (*FcPatternPrint_dylibloader_wrapper_fontconfig)(const FcPattern *);
void (*FcFontSetPrint_dylibloader_wrapper_fontconfig)(const FcFontSet *);
FcStrSet *(*FcGetDefaultLangs_dylibloader_wrapper_fontconfig)(void);
void (*FcDefaultSubstitute_dylibloader_wrapper_fontconfig)(FcPattern *);
FcBool (*FcFileIsDir_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcBool (*FcFileScan_dylibloader_wrapper_fontconfig)(FcFontSet *, FcStrSet *, FcFileCache *, FcBlanks *, const FcChar8 *, FcBool);
FcBool (*FcDirScan_dylibloader_wrapper_fontconfig)(FcFontSet *, FcStrSet *, FcFileCache *, FcBlanks *, const FcChar8 *, FcBool);
FcBool (*FcDirSave_dylibloader_wrapper_fontconfig)(FcFontSet *, FcStrSet *, const FcChar8 *);
FcCache *(*FcDirCacheLoad_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcConfig *, FcChar8 **);
FcCache *(*FcDirCacheRescan_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcConfig *);
FcCache *(*FcDirCacheRead_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcBool, FcConfig *);
FcCache *(*FcDirCacheLoadFile_dylibloader_wrapper_fontconfig)(const FcChar8 *, struct stat *);
void (*FcDirCacheUnload_dylibloader_wrapper_fontconfig)(FcCache *);
FcPattern *(*FcFreeTypeQuery_dylibloader_wrapper_fontconfig)(const FcChar8 *, int, FcBlanks *, int *);
FcFontSet *(*FcFontSetCreate_dylibloader_wrapper_fontconfig)(void);
void (*FcFontSetDestroy_dylibloader_wrapper_fontconfig)(FcFontSet *);
FcBool (*FcFontSetAdd_dylibloader_wrapper_fontconfig)(FcFontSet *, FcPattern *);
FcConfig *(*FcInitLoadConfig_dylibloader_wrapper_fontconfig)(void);
FcConfig *(*FcInitLoadConfigAndFonts_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcInit_dylibloader_wrapper_fontconfig)(void);
void (*FcFini_dylibloader_wrapper_fontconfig)(void);
int (*FcGetVersion_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcInitReinitialize_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcInitBringUptoDate_dylibloader_wrapper_fontconfig)(void);
FcStrSet *(*FcGetLangs_dylibloader_wrapper_fontconfig)(void);
FcChar8 *(*FcLangNormalize_dylibloader_wrapper_fontconfig)(const FcChar8 *);
const FcCharSet *(*FcLangGetCharSet_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcLangSet *(*FcLangSetCreate_dylibloader_wrapper_fontconfig)(void);
void (*FcLangSetDestroy_dylibloader_wrapper_fontconfig)(FcLangSet *);
FcLangSet *(*FcLangSetCopy_dylibloader_wrapper_fontconfig)(const FcLangSet *);
FcBool (*FcLangSetAdd_dylibloader_wrapper_fontconfig)(FcLangSet *, const FcChar8 *);
FcBool (*FcLangSetDel_dylibloader_wrapper_fontconfig)(FcLangSet *, const FcChar8 *);
FcLangResult (*FcLangSetHasLang_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcChar8 *);
FcLangResult (*FcLangSetCompare_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcLangSet *);
FcBool (*FcLangSetContains_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcLangSet *);
FcBool (*FcLangSetEqual_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcLangSet *);
FcChar32 (*FcLangSetHash_dylibloader_wrapper_fontconfig)(const FcLangSet *);
FcStrSet *(*FcLangSetGetLangs_dylibloader_wrapper_fontconfig)(const FcLangSet *);
FcLangSet *(*FcLangSetUnion_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcLangSet *);
FcLangSet *(*FcLangSetSubtract_dylibloader_wrapper_fontconfig)(const FcLangSet *, const FcLangSet *);
FcObjectSet *(*FcObjectSetCreate_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcObjectSetAdd_dylibloader_wrapper_fontconfig)(FcObjectSet *, const char *);
void (*FcObjectSetDestroy_dylibloader_wrapper_fontconfig)(FcObjectSet *);
FcObjectSet *(*FcObjectSetVaBuild_dylibloader_wrapper_fontconfig)(const char *, va_list);
FcObjectSet *(*FcObjectSetBuild_dylibloader_wrapper_fontconfig)(const char *, ...);
FcFontSet *(*FcFontSetList_dylibloader_wrapper_fontconfig)(FcConfig *, FcFontSet **, int, FcPattern *, FcObjectSet *);
FcFontSet *(*FcFontList_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcObjectSet *);
FcAtomic *(*FcAtomicCreate_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcBool (*FcAtomicLock_dylibloader_wrapper_fontconfig)(FcAtomic *);
FcChar8 *(*FcAtomicNewFile_dylibloader_wrapper_fontconfig)(FcAtomic *);
FcChar8 *(*FcAtomicOrigFile_dylibloader_wrapper_fontconfig)(FcAtomic *);
FcBool (*FcAtomicReplaceOrig_dylibloader_wrapper_fontconfig)(FcAtomic *);
void (*FcAtomicDeleteNew_dylibloader_wrapper_fontconfig)(FcAtomic *);
void (*FcAtomicUnlock_dylibloader_wrapper_fontconfig)(FcAtomic *);
void (*FcAtomicDestroy_dylibloader_wrapper_fontconfig)(FcAtomic *);
FcPattern *(*FcFontSetMatch_dylibloader_wrapper_fontconfig)(FcConfig *, FcFontSet **, int, FcPattern *, FcResult *);
FcPattern *(*FcFontMatch_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcResult *);
FcPattern *(*FcFontRenderPrepare_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcPattern *);
FcFontSet *(*FcFontSetSort_dylibloader_wrapper_fontconfig)(FcConfig *, FcFontSet **, int, FcPattern *, FcBool, FcCharSet **, FcResult *);
FcFontSet *(*FcFontSort_dylibloader_wrapper_fontconfig)(FcConfig *, FcPattern *, FcBool, FcCharSet **, FcResult *);
void (*FcFontSetSortDestroy_dylibloader_wrapper_fontconfig)(FcFontSet *);
FcMatrix *(*FcMatrixCopy_dylibloader_wrapper_fontconfig)(const FcMatrix *);
FcBool (*FcMatrixEqual_dylibloader_wrapper_fontconfig)(const FcMatrix *, const FcMatrix *);
void (*FcMatrixMultiply_dylibloader_wrapper_fontconfig)(FcMatrix *, const FcMatrix *, const FcMatrix *);
void (*FcMatrixRotate_dylibloader_wrapper_fontconfig)(FcMatrix *, double, double);
void (*FcMatrixScale_dylibloader_wrapper_fontconfig)(FcMatrix *, double, double);
void (*FcMatrixShear_dylibloader_wrapper_fontconfig)(FcMatrix *, double, double);
FcBool (*FcNameRegisterObjectTypes_dylibloader_wrapper_fontconfig)(const FcObjectType *, int);
FcBool (*FcNameUnregisterObjectTypes_dylibloader_wrapper_fontconfig)(const FcObjectType *, int);
const FcObjectType *(*FcNameGetObjectType_dylibloader_wrapper_fontconfig)(const char *);
FcBool (*FcNameRegisterConstants_dylibloader_wrapper_fontconfig)(const FcConstant *, int);
FcBool (*FcNameUnregisterConstants_dylibloader_wrapper_fontconfig)(const FcConstant *, int);
const FcConstant *(*FcNameGetConstant_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcBool (*FcNameConstant_dylibloader_wrapper_fontconfig)(const FcChar8 *, int *);
FcPattern *(*FcNameParse_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcChar8 *(*FcNameUnparse_dylibloader_wrapper_fontconfig)(FcPattern *);
FcPattern *(*FcPatternCreate_dylibloader_wrapper_fontconfig)(void);
FcPattern *(*FcPatternDuplicate_dylibloader_wrapper_fontconfig)(const FcPattern *);
void (*FcPatternReference_dylibloader_wrapper_fontconfig)(FcPattern *);
FcPattern *(*FcPatternFilter_dylibloader_wrapper_fontconfig)(FcPattern *, const FcObjectSet *);
void (*FcValueDestroy_dylibloader_wrapper_fontconfig)(FcValue);
FcBool (*FcValueEqual_dylibloader_wrapper_fontconfig)(FcValue, FcValue);
FcValue (*FcValueSave_dylibloader_wrapper_fontconfig)(FcValue);
void (*FcPatternDestroy_dylibloader_wrapper_fontconfig)(FcPattern *);
FcBool (*FcPatternEqual_dylibloader_wrapper_fontconfig)(const FcPattern *, const FcPattern *);
FcBool (*FcPatternEqualSubset_dylibloader_wrapper_fontconfig)(const FcPattern *, const FcPattern *, const FcObjectSet *);
FcChar32 (*FcPatternHash_dylibloader_wrapper_fontconfig)(const FcPattern *);
FcBool (*FcPatternAdd_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, FcValue, FcBool);
FcBool (*FcPatternAddWeak_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, FcValue, FcBool);
FcResult (*FcPatternGet_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcValue *);
FcResult (*FcPatternGetWithBinding_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcValue *, FcValueBinding *);
FcBool (*FcPatternDel_dylibloader_wrapper_fontconfig)(FcPattern *, const char *);
FcBool (*FcPatternRemove_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, int);
FcBool (*FcPatternAddInteger_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, int);
FcBool (*FcPatternAddDouble_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, double);
FcBool (*FcPatternAddString_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FcChar8 *);
FcBool (*FcPatternAddMatrix_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FcMatrix *);
FcBool (*FcPatternAddCharSet_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FcCharSet *);
FcBool (*FcPatternAddBool_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, FcBool);
FcBool (*FcPatternAddLangSet_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FcLangSet *);
FcBool (*FcPatternAddRange_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FcRange *);
FcResult (*FcPatternGetInteger_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, int *);
FcResult (*FcPatternGetDouble_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, double *);
FcResult (*FcPatternGetString_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcChar8 **);
FcResult (*FcPatternGetMatrix_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcMatrix **);
FcResult (*FcPatternGetCharSet_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcCharSet **);
FcResult (*FcPatternGetBool_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcBool *);
FcResult (*FcPatternGetLangSet_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcLangSet **);
FcResult (*FcPatternGetRange_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FcRange **);
FcPattern *(*FcPatternVaBuild_dylibloader_wrapper_fontconfig)(FcPattern *, va_list);
FcPattern *(*FcPatternBuild_dylibloader_wrapper_fontconfig)(FcPattern *, ...);
FcChar8 *(*FcPatternFormat_dylibloader_wrapper_fontconfig)(FcPattern *, const FcChar8 *);
FcRange *(*FcRangeCreateDouble_dylibloader_wrapper_fontconfig)(double, double);
FcRange *(*FcRangeCreateInteger_dylibloader_wrapper_fontconfig)(FcChar32, FcChar32);
void (*FcRangeDestroy_dylibloader_wrapper_fontconfig)(FcRange *);
FcRange *(*FcRangeCopy_dylibloader_wrapper_fontconfig)(const FcRange *);
FcBool (*FcRangeGetDouble_dylibloader_wrapper_fontconfig)(const FcRange *, double *, double *);
int (*FcWeightFromOpenType_dylibloader_wrapper_fontconfig)(int);
int (*FcWeightToOpenType_dylibloader_wrapper_fontconfig)(int);
FcChar8 *(*FcStrCopy_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcChar8 *(*FcStrCopyFilename_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcChar8 *(*FcStrPlus_dylibloader_wrapper_fontconfig)(const FcChar8 *, const FcChar8 *);
void (*FcStrFree_dylibloader_wrapper_fontconfig)(FcChar8 *);
FcChar8 *(*FcStrDowncase_dylibloader_wrapper_fontconfig)(const FcChar8 *);
int (*FcStrCmpIgnoreCase_dylibloader_wrapper_fontconfig)(const FcChar8 *, const FcChar8 *);
int (*FcStrCmp_dylibloader_wrapper_fontconfig)(const FcChar8 *, const FcChar8 *);
const FcChar8 *(*FcStrStrIgnoreCase_dylibloader_wrapper_fontconfig)(const FcChar8 *, const FcChar8 *);
const FcChar8 *(*FcStrStr_dylibloader_wrapper_fontconfig)(const FcChar8 *, const FcChar8 *);
int (*FcUtf8ToUcs4_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcChar32 *, int);
FcBool (*FcUtf8Len_dylibloader_wrapper_fontconfig)(const FcChar8 *, int, int *, int *);
int (*FcUcs4ToUtf8_dylibloader_wrapper_fontconfig)(FcChar32, FcChar8 [6]);
int (*FcUtf16ToUcs4_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcEndian, FcChar32 *, int);
FcBool (*FcUtf16Len_dylibloader_wrapper_fontconfig)(const FcChar8 *, FcEndian, int, int *, int *);
FcChar8 *(*FcStrDirname_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcChar8 *(*FcStrBasename_dylibloader_wrapper_fontconfig)(const FcChar8 *);
FcStrSet *(*FcStrSetCreate_dylibloader_wrapper_fontconfig)(void);
FcBool (*FcStrSetMember_dylibloader_wrapper_fontconfig)(FcStrSet *, const FcChar8 *);
FcBool (*FcStrSetEqual_dylibloader_wrapper_fontconfig)(FcStrSet *, FcStrSet *);
FcBool (*FcStrSetAdd_dylibloader_wrapper_fontconfig)(FcStrSet *, const FcChar8 *);
FcBool (*FcStrSetAddFilename_dylibloader_wrapper_fontconfig)(FcStrSet *, const FcChar8 *);
FcBool (*FcStrSetDel_dylibloader_wrapper_fontconfig)(FcStrSet *, const FcChar8 *);
void (*FcStrSetDestroy_dylibloader_wrapper_fontconfig)(FcStrSet *);
FcStrList *(*FcStrListCreate_dylibloader_wrapper_fontconfig)(FcStrSet *);
void (*FcStrListFirst_dylibloader_wrapper_fontconfig)(FcStrList *);
FcChar8 *(*FcStrListNext_dylibloader_wrapper_fontconfig)(FcStrList *);
void (*FcStrListDone_dylibloader_wrapper_fontconfig)(FcStrList *);
FcBool (*FcConfigParseAndLoad_dylibloader_wrapper_fontconfig)(FcConfig *, const FcChar8 *, FcBool);
FcBool (*FcConfigParseAndLoadFromMemory_dylibloader_wrapper_fontconfig)(FcConfig *, const FcChar8 *, FcBool);
FT_UInt (*FcFreeTypeCharIndex_dylibloader_wrapper_fontconfig)(FT_Face, FcChar32);
FcCharSet *(*FcFreeTypeCharSetAndSpacing_dylibloader_wrapper_fontconfig)(FT_Face, FcBlanks *, int *);
FcCharSet *(*FcFreeTypeCharSet_dylibloader_wrapper_fontconfig)(FT_Face, FcBlanks *);
FcResult (*FcPatternGetFTFace_dylibloader_wrapper_fontconfig)(const FcPattern *, const char *, int, FT_Face *);
FcBool (*FcPatternAddFTFace_dylibloader_wrapper_fontconfig)(FcPattern *, const char *, const FT_Face);
FcPattern *(*FcFreeTypeQueryFace_dylibloader_wrapper_fontconfig)(const FT_Face, const FcChar8 *, int, FcBlanks *);
int initialize_fontconfig(int verbose) {
  void *handle;
  char *error;
  handle = dlopen("libfontconfig.so.1", RTLD_LAZY);
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
/* FcBlanksCreate */
  *(void **) (&FcBlanksCreate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcBlanksCreate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcBlanksDestroy */
  *(void **) (&FcBlanksDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcBlanksDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcBlanksAdd */
  *(void **) (&FcBlanksAdd_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcBlanksAdd");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcBlanksIsMember */
  *(void **) (&FcBlanksIsMember_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcBlanksIsMember");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCacheDir */
  *(void **) (&FcCacheDir_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCacheDir");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCacheCopySet */
  *(void **) (&FcCacheCopySet_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCacheCopySet");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCacheSubdir */
  *(void **) (&FcCacheSubdir_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCacheSubdir");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCacheNumSubdir */
  *(void **) (&FcCacheNumSubdir_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCacheNumSubdir");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCacheNumFont */
  *(void **) (&FcCacheNumFont_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCacheNumFont");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDirCacheUnlink */
  *(void **) (&FcDirCacheUnlink_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDirCacheUnlink");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDirCacheValid */
  *(void **) (&FcDirCacheValid_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDirCacheValid");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDirCacheClean */
  *(void **) (&FcDirCacheClean_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDirCacheClean");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCacheCreateTagFile */
  *(void **) (&FcCacheCreateTagFile_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCacheCreateTagFile");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigHome */
  *(void **) (&FcConfigHome_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigHome");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigEnableHome */
  *(void **) (&FcConfigEnableHome_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigEnableHome");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigFilename */
  *(void **) (&FcConfigFilename_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigFilename");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigCreate */
  *(void **) (&FcConfigCreate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigCreate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigReference */
  *(void **) (&FcConfigReference_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigReference");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigDestroy */
  *(void **) (&FcConfigDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigSetCurrent */
  *(void **) (&FcConfigSetCurrent_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigSetCurrent");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigGetCurrent */
  *(void **) (&FcConfigGetCurrent_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigGetCurrent");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigUptoDate */
  *(void **) (&FcConfigUptoDate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigUptoDate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigBuildFonts */
  *(void **) (&FcConfigBuildFonts_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigBuildFonts");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigGetFontDirs */
  *(void **) (&FcConfigGetFontDirs_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigGetFontDirs");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigGetConfigDirs */
  *(void **) (&FcConfigGetConfigDirs_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigGetConfigDirs");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigGetConfigFiles */
  *(void **) (&FcConfigGetConfigFiles_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigGetConfigFiles");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigGetCache */
  *(void **) (&FcConfigGetCache_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigGetCache");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigGetBlanks */
  *(void **) (&FcConfigGetBlanks_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigGetBlanks");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigGetCacheDirs */
  *(void **) (&FcConfigGetCacheDirs_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigGetCacheDirs");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigGetRescanInterval */
  *(void **) (&FcConfigGetRescanInterval_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigGetRescanInterval");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigSetRescanInterval */
  *(void **) (&FcConfigSetRescanInterval_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigSetRescanInterval");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigGetFonts */
  *(void **) (&FcConfigGetFonts_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigGetFonts");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigAppFontAddFile */
  *(void **) (&FcConfigAppFontAddFile_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigAppFontAddFile");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigAppFontAddDir */
  *(void **) (&FcConfigAppFontAddDir_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigAppFontAddDir");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigAppFontClear */
  *(void **) (&FcConfigAppFontClear_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigAppFontClear");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigSubstituteWithPat */
  *(void **) (&FcConfigSubstituteWithPat_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigSubstituteWithPat");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigSubstitute */
  *(void **) (&FcConfigSubstitute_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigSubstitute");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigGetSysRoot */
  *(void **) (&FcConfigGetSysRoot_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigGetSysRoot");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigSetSysRoot */
  *(void **) (&FcConfigSetSysRoot_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigSetSysRoot");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetCreate */
  *(void **) (&FcCharSetCreate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetCreate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetNew */
  *(void **) (&FcCharSetNew_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetNew");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetDestroy */
  *(void **) (&FcCharSetDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetAddChar */
  *(void **) (&FcCharSetAddChar_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetAddChar");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetDelChar */
  *(void **) (&FcCharSetDelChar_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetDelChar");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetCopy */
  *(void **) (&FcCharSetCopy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetCopy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetEqual */
  *(void **) (&FcCharSetEqual_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetEqual");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetIntersect */
  *(void **) (&FcCharSetIntersect_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetIntersect");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetUnion */
  *(void **) (&FcCharSetUnion_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetUnion");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetSubtract */
  *(void **) (&FcCharSetSubtract_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetSubtract");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetMerge */
  *(void **) (&FcCharSetMerge_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetMerge");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetHasChar */
  *(void **) (&FcCharSetHasChar_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetHasChar");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetCount */
  *(void **) (&FcCharSetCount_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetCount");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetIntersectCount */
  *(void **) (&FcCharSetIntersectCount_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetIntersectCount");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetSubtractCount */
  *(void **) (&FcCharSetSubtractCount_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetSubtractCount");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetIsSubset */
  *(void **) (&FcCharSetIsSubset_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetIsSubset");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetFirstPage */
  *(void **) (&FcCharSetFirstPage_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetFirstPage");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetNextPage */
  *(void **) (&FcCharSetNextPage_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetNextPage");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcCharSetCoverage */
  *(void **) (&FcCharSetCoverage_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcCharSetCoverage");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcValuePrint */
  *(void **) (&FcValuePrint_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcValuePrint");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternPrint */
  *(void **) (&FcPatternPrint_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternPrint");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontSetPrint */
  *(void **) (&FcFontSetPrint_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontSetPrint");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcGetDefaultLangs */
  *(void **) (&FcGetDefaultLangs_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcGetDefaultLangs");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDefaultSubstitute */
  *(void **) (&FcDefaultSubstitute_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDefaultSubstitute");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFileIsDir */
  *(void **) (&FcFileIsDir_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFileIsDir");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFileScan */
  *(void **) (&FcFileScan_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFileScan");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDirScan */
  *(void **) (&FcDirScan_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDirScan");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDirSave */
  *(void **) (&FcDirSave_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDirSave");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDirCacheLoad */
  *(void **) (&FcDirCacheLoad_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDirCacheLoad");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDirCacheRescan */
  *(void **) (&FcDirCacheRescan_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDirCacheRescan");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDirCacheRead */
  *(void **) (&FcDirCacheRead_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDirCacheRead");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDirCacheLoadFile */
  *(void **) (&FcDirCacheLoadFile_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDirCacheLoadFile");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcDirCacheUnload */
  *(void **) (&FcDirCacheUnload_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcDirCacheUnload");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFreeTypeQuery */
  *(void **) (&FcFreeTypeQuery_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFreeTypeQuery");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontSetCreate */
  *(void **) (&FcFontSetCreate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontSetCreate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontSetDestroy */
  *(void **) (&FcFontSetDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontSetDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontSetAdd */
  *(void **) (&FcFontSetAdd_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontSetAdd");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcInitLoadConfig */
  *(void **) (&FcInitLoadConfig_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcInitLoadConfig");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcInitLoadConfigAndFonts */
  *(void **) (&FcInitLoadConfigAndFonts_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcInitLoadConfigAndFonts");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcInit */
  *(void **) (&FcInit_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcInit");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFini */
  *(void **) (&FcFini_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFini");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcGetVersion */
  *(void **) (&FcGetVersion_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcGetVersion");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcInitReinitialize */
  *(void **) (&FcInitReinitialize_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcInitReinitialize");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcInitBringUptoDate */
  *(void **) (&FcInitBringUptoDate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcInitBringUptoDate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcGetLangs */
  *(void **) (&FcGetLangs_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcGetLangs");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangNormalize */
  *(void **) (&FcLangNormalize_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangNormalize");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangGetCharSet */
  *(void **) (&FcLangGetCharSet_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangGetCharSet");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetCreate */
  *(void **) (&FcLangSetCreate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetCreate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetDestroy */
  *(void **) (&FcLangSetDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetCopy */
  *(void **) (&FcLangSetCopy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetCopy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetAdd */
  *(void **) (&FcLangSetAdd_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetAdd");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetDel */
  *(void **) (&FcLangSetDel_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetDel");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetHasLang */
  *(void **) (&FcLangSetHasLang_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetHasLang");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetCompare */
  *(void **) (&FcLangSetCompare_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetCompare");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetContains */
  *(void **) (&FcLangSetContains_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetContains");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetEqual */
  *(void **) (&FcLangSetEqual_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetEqual");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetHash */
  *(void **) (&FcLangSetHash_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetHash");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetGetLangs */
  *(void **) (&FcLangSetGetLangs_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetGetLangs");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetUnion */
  *(void **) (&FcLangSetUnion_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetUnion");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcLangSetSubtract */
  *(void **) (&FcLangSetSubtract_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcLangSetSubtract");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcObjectSetCreate */
  *(void **) (&FcObjectSetCreate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcObjectSetCreate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcObjectSetAdd */
  *(void **) (&FcObjectSetAdd_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcObjectSetAdd");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcObjectSetDestroy */
  *(void **) (&FcObjectSetDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcObjectSetDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcObjectSetVaBuild */
  *(void **) (&FcObjectSetVaBuild_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcObjectSetVaBuild");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcObjectSetBuild */
  *(void **) (&FcObjectSetBuild_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcObjectSetBuild");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontSetList */
  *(void **) (&FcFontSetList_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontSetList");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontList */
  *(void **) (&FcFontList_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontList");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcAtomicCreate */
  *(void **) (&FcAtomicCreate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcAtomicCreate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcAtomicLock */
  *(void **) (&FcAtomicLock_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcAtomicLock");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcAtomicNewFile */
  *(void **) (&FcAtomicNewFile_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcAtomicNewFile");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcAtomicOrigFile */
  *(void **) (&FcAtomicOrigFile_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcAtomicOrigFile");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcAtomicReplaceOrig */
  *(void **) (&FcAtomicReplaceOrig_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcAtomicReplaceOrig");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcAtomicDeleteNew */
  *(void **) (&FcAtomicDeleteNew_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcAtomicDeleteNew");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcAtomicUnlock */
  *(void **) (&FcAtomicUnlock_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcAtomicUnlock");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcAtomicDestroy */
  *(void **) (&FcAtomicDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcAtomicDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontSetMatch */
  *(void **) (&FcFontSetMatch_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontSetMatch");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontMatch */
  *(void **) (&FcFontMatch_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontMatch");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontRenderPrepare */
  *(void **) (&FcFontRenderPrepare_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontRenderPrepare");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontSetSort */
  *(void **) (&FcFontSetSort_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontSetSort");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontSort */
  *(void **) (&FcFontSort_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontSort");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFontSetSortDestroy */
  *(void **) (&FcFontSetSortDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFontSetSortDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcMatrixCopy */
  *(void **) (&FcMatrixCopy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcMatrixCopy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcMatrixEqual */
  *(void **) (&FcMatrixEqual_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcMatrixEqual");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcMatrixMultiply */
  *(void **) (&FcMatrixMultiply_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcMatrixMultiply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcMatrixRotate */
  *(void **) (&FcMatrixRotate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcMatrixRotate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcMatrixScale */
  *(void **) (&FcMatrixScale_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcMatrixScale");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcMatrixShear */
  *(void **) (&FcMatrixShear_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcMatrixShear");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcNameRegisterObjectTypes */
  *(void **) (&FcNameRegisterObjectTypes_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcNameRegisterObjectTypes");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcNameUnregisterObjectTypes */
  *(void **) (&FcNameUnregisterObjectTypes_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcNameUnregisterObjectTypes");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcNameGetObjectType */
  *(void **) (&FcNameGetObjectType_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcNameGetObjectType");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcNameRegisterConstants */
  *(void **) (&FcNameRegisterConstants_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcNameRegisterConstants");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcNameUnregisterConstants */
  *(void **) (&FcNameUnregisterConstants_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcNameUnregisterConstants");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcNameGetConstant */
  *(void **) (&FcNameGetConstant_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcNameGetConstant");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcNameConstant */
  *(void **) (&FcNameConstant_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcNameConstant");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcNameParse */
  *(void **) (&FcNameParse_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcNameParse");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcNameUnparse */
  *(void **) (&FcNameUnparse_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcNameUnparse");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternCreate */
  *(void **) (&FcPatternCreate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternCreate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternDuplicate */
  *(void **) (&FcPatternDuplicate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternDuplicate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternReference */
  *(void **) (&FcPatternReference_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternReference");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternFilter */
  *(void **) (&FcPatternFilter_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternFilter");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcValueDestroy */
  *(void **) (&FcValueDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcValueDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcValueEqual */
  *(void **) (&FcValueEqual_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcValueEqual");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcValueSave */
  *(void **) (&FcValueSave_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcValueSave");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternDestroy */
  *(void **) (&FcPatternDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternEqual */
  *(void **) (&FcPatternEqual_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternEqual");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternEqualSubset */
  *(void **) (&FcPatternEqualSubset_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternEqualSubset");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternHash */
  *(void **) (&FcPatternHash_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternHash");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAdd */
  *(void **) (&FcPatternAdd_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAdd");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAddWeak */
  *(void **) (&FcPatternAddWeak_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAddWeak");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGet */
  *(void **) (&FcPatternGet_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGet");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGetWithBinding */
  *(void **) (&FcPatternGetWithBinding_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGetWithBinding");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternDel */
  *(void **) (&FcPatternDel_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternDel");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternRemove */
  *(void **) (&FcPatternRemove_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternRemove");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAddInteger */
  *(void **) (&FcPatternAddInteger_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAddInteger");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAddDouble */
  *(void **) (&FcPatternAddDouble_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAddDouble");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAddString */
  *(void **) (&FcPatternAddString_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAddString");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAddMatrix */
  *(void **) (&FcPatternAddMatrix_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAddMatrix");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAddCharSet */
  *(void **) (&FcPatternAddCharSet_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAddCharSet");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAddBool */
  *(void **) (&FcPatternAddBool_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAddBool");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAddLangSet */
  *(void **) (&FcPatternAddLangSet_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAddLangSet");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAddRange */
  *(void **) (&FcPatternAddRange_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAddRange");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGetInteger */
  *(void **) (&FcPatternGetInteger_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGetInteger");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGetDouble */
  *(void **) (&FcPatternGetDouble_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGetDouble");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGetString */
  *(void **) (&FcPatternGetString_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGetString");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGetMatrix */
  *(void **) (&FcPatternGetMatrix_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGetMatrix");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGetCharSet */
  *(void **) (&FcPatternGetCharSet_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGetCharSet");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGetBool */
  *(void **) (&FcPatternGetBool_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGetBool");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGetLangSet */
  *(void **) (&FcPatternGetLangSet_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGetLangSet");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGetRange */
  *(void **) (&FcPatternGetRange_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGetRange");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternVaBuild */
  *(void **) (&FcPatternVaBuild_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternVaBuild");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternBuild */
  *(void **) (&FcPatternBuild_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternBuild");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternFormat */
  *(void **) (&FcPatternFormat_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternFormat");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcRangeCreateDouble */
  *(void **) (&FcRangeCreateDouble_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcRangeCreateDouble");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcRangeCreateInteger */
  *(void **) (&FcRangeCreateInteger_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcRangeCreateInteger");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcRangeDestroy */
  *(void **) (&FcRangeDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcRangeDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcRangeCopy */
  *(void **) (&FcRangeCopy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcRangeCopy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcRangeGetDouble */
  *(void **) (&FcRangeGetDouble_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcRangeGetDouble");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcWeightFromOpenType */
  *(void **) (&FcWeightFromOpenType_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcWeightFromOpenType");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcWeightToOpenType */
  *(void **) (&FcWeightToOpenType_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcWeightToOpenType");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrCopy */
  *(void **) (&FcStrCopy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrCopy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrCopyFilename */
  *(void **) (&FcStrCopyFilename_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrCopyFilename");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrPlus */
  *(void **) (&FcStrPlus_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrPlus");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrFree */
  *(void **) (&FcStrFree_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrFree");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrDowncase */
  *(void **) (&FcStrDowncase_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrDowncase");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrCmpIgnoreCase */
  *(void **) (&FcStrCmpIgnoreCase_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrCmpIgnoreCase");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrCmp */
  *(void **) (&FcStrCmp_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrCmp");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrStrIgnoreCase */
  *(void **) (&FcStrStrIgnoreCase_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrStrIgnoreCase");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrStr */
  *(void **) (&FcStrStr_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrStr");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcUtf8ToUcs4 */
  *(void **) (&FcUtf8ToUcs4_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcUtf8ToUcs4");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcUtf8Len */
  *(void **) (&FcUtf8Len_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcUtf8Len");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcUcs4ToUtf8 */
  *(void **) (&FcUcs4ToUtf8_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcUcs4ToUtf8");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcUtf16ToUcs4 */
  *(void **) (&FcUtf16ToUcs4_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcUtf16ToUcs4");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcUtf16Len */
  *(void **) (&FcUtf16Len_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcUtf16Len");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrDirname */
  *(void **) (&FcStrDirname_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrDirname");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrBasename */
  *(void **) (&FcStrBasename_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrBasename");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrSetCreate */
  *(void **) (&FcStrSetCreate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrSetCreate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrSetMember */
  *(void **) (&FcStrSetMember_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrSetMember");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrSetEqual */
  *(void **) (&FcStrSetEqual_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrSetEqual");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrSetAdd */
  *(void **) (&FcStrSetAdd_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrSetAdd");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrSetAddFilename */
  *(void **) (&FcStrSetAddFilename_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrSetAddFilename");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrSetDel */
  *(void **) (&FcStrSetDel_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrSetDel");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrSetDestroy */
  *(void **) (&FcStrSetDestroy_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrSetDestroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrListCreate */
  *(void **) (&FcStrListCreate_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrListCreate");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrListFirst */
  *(void **) (&FcStrListFirst_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrListFirst");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrListNext */
  *(void **) (&FcStrListNext_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrListNext");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcStrListDone */
  *(void **) (&FcStrListDone_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcStrListDone");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigParseAndLoad */
  *(void **) (&FcConfigParseAndLoad_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigParseAndLoad");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcConfigParseAndLoadFromMemory */
  *(void **) (&FcConfigParseAndLoadFromMemory_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcConfigParseAndLoadFromMemory");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFreeTypeCharIndex */
  *(void **) (&FcFreeTypeCharIndex_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFreeTypeCharIndex");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFreeTypeCharSetAndSpacing */
  *(void **) (&FcFreeTypeCharSetAndSpacing_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFreeTypeCharSetAndSpacing");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFreeTypeCharSet */
  *(void **) (&FcFreeTypeCharSet_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFreeTypeCharSet");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternGetFTFace */
  *(void **) (&FcPatternGetFTFace_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternGetFTFace");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcPatternAddFTFace */
  *(void **) (&FcPatternAddFTFace_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcPatternAddFTFace");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* FcFreeTypeQueryFace */
  *(void **) (&FcFreeTypeQueryFace_dylibloader_wrapper_fontconfig) = dlsym(handle, "FcFreeTypeQueryFace");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
return 0;
}
