/* This file is generated. Do not edit!
   see https://github.com/hpvb/dynload-wrapper (patched) for details
   generated by scripts/generate-wrapper.py 0.5
   flags: scripts/generate-wrapper.py --include include/wayland-client.h --include include/wayland-client-core.h --include include/wayland-client-protocol.h --sys-include <wayland-client.h> --sys-include <wayland-client-core.h> --sys-include <wayland-client-protocol.h> --soname libwayland-client.so.0 --init-name wayland_client --output-header include_gen/wayland_client-so_wrap.h --output-implementation src_gen/wayland_client-so_wrap.c --ignore-other --include-dir include
*/
#include <stdint.h>

#define wl_event_queue_destroy wl_event_queue_destroy_dylibloader_orig_wayland_client
#define wl_proxy_marshal wl_proxy_marshal_dylibloader_orig_wayland_client
#define wl_proxy_marshal_array wl_proxy_marshal_array_dylibloader_orig_wayland_client
#define wl_proxy_create wl_proxy_create_dylibloader_orig_wayland_client
#define wl_proxy_create_wrapper wl_proxy_create_wrapper_dylibloader_orig_wayland_client
#define wl_proxy_wrapper_destroy wl_proxy_wrapper_destroy_dylibloader_orig_wayland_client
#define wl_proxy_marshal_constructor wl_proxy_marshal_constructor_dylibloader_orig_wayland_client
#define wl_proxy_marshal_constructor_versioned wl_proxy_marshal_constructor_versioned_dylibloader_orig_wayland_client
#define wl_proxy_marshal_array_constructor wl_proxy_marshal_array_constructor_dylibloader_orig_wayland_client
#define wl_proxy_marshal_array_constructor_versioned wl_proxy_marshal_array_constructor_versioned_dylibloader_orig_wayland_client
#define wl_proxy_destroy wl_proxy_destroy_dylibloader_orig_wayland_client
#define wl_proxy_add_listener wl_proxy_add_listener_dylibloader_orig_wayland_client
#define wl_proxy_get_listener wl_proxy_get_listener_dylibloader_orig_wayland_client
#define wl_proxy_add_dispatcher wl_proxy_add_dispatcher_dylibloader_orig_wayland_client
#define wl_proxy_set_user_data wl_proxy_set_user_data_dylibloader_orig_wayland_client
#define wl_proxy_get_user_data wl_proxy_get_user_data_dylibloader_orig_wayland_client
#define wl_proxy_get_version wl_proxy_get_version_dylibloader_orig_wayland_client
#define wl_proxy_get_id wl_proxy_get_id_dylibloader_orig_wayland_client
#define wl_proxy_set_tag wl_proxy_set_tag_dylibloader_orig_wayland_client
#define wl_proxy_get_tag wl_proxy_get_tag_dylibloader_orig_wayland_client
#define wl_proxy_get_class wl_proxy_get_class_dylibloader_orig_wayland_client
#define wl_proxy_set_queue wl_proxy_set_queue_dylibloader_orig_wayland_client
#define wl_display_connect wl_display_connect_dylibloader_orig_wayland_client
#define wl_display_connect_to_fd wl_display_connect_to_fd_dylibloader_orig_wayland_client
#define wl_display_disconnect wl_display_disconnect_dylibloader_orig_wayland_client
#define wl_display_get_fd wl_display_get_fd_dylibloader_orig_wayland_client
#define wl_display_dispatch wl_display_dispatch_dylibloader_orig_wayland_client
#define wl_display_dispatch_queue wl_display_dispatch_queue_dylibloader_orig_wayland_client
#define wl_display_dispatch_queue_pending wl_display_dispatch_queue_pending_dylibloader_orig_wayland_client
#define wl_display_dispatch_pending wl_display_dispatch_pending_dylibloader_orig_wayland_client
#define wl_display_get_error wl_display_get_error_dylibloader_orig_wayland_client
#define wl_display_get_protocol_error wl_display_get_protocol_error_dylibloader_orig_wayland_client
#define wl_display_flush wl_display_flush_dylibloader_orig_wayland_client
#define wl_display_roundtrip_queue wl_display_roundtrip_queue_dylibloader_orig_wayland_client
#define wl_display_roundtrip wl_display_roundtrip_dylibloader_orig_wayland_client
#define wl_display_create_queue wl_display_create_queue_dylibloader_orig_wayland_client
#define wl_display_prepare_read_queue wl_display_prepare_read_queue_dylibloader_orig_wayland_client
#define wl_display_prepare_read wl_display_prepare_read_dylibloader_orig_wayland_client
#define wl_display_cancel_read wl_display_cancel_read_dylibloader_orig_wayland_client
#define wl_display_read_events wl_display_read_events_dylibloader_orig_wayland_client
#define wl_log_set_handler_client wl_log_set_handler_client_dylibloader_orig_wayland_client
#define wl_display_interface wl_display_interface_dylibloader_orig_wayland_client
#define wl_registry_interface wl_registry_interface_dylibloader_orig_wayland_client
#define wl_callback_interface wl_callback_interface_dylibloader_orig_wayland_client
#define wl_compositor_interface wl_compositor_interface_dylibloader_orig_wayland_client
#define wl_shm_pool_interface wl_shm_pool_interface_dylibloader_orig_wayland_client
#define wl_shm_interface wl_shm_interface_dylibloader_orig_wayland_client
#define wl_buffer_interface wl_buffer_interface_dylibloader_orig_wayland_client
#define wl_data_offer_interface wl_data_offer_interface_dylibloader_orig_wayland_client
#define wl_data_source_interface wl_data_source_interface_dylibloader_orig_wayland_client
#define wl_data_device_interface wl_data_device_interface_dylibloader_orig_wayland_client
#define wl_data_device_manager_interface wl_data_device_manager_interface_dylibloader_orig_wayland_client
#define wl_shell_interface wl_shell_interface_dylibloader_orig_wayland_client
#define wl_shell_surface_interface wl_shell_surface_interface_dylibloader_orig_wayland_client
#define wl_surface_interface wl_surface_interface_dylibloader_orig_wayland_client
#define wl_seat_interface wl_seat_interface_dylibloader_orig_wayland_client
#define wl_pointer_interface wl_pointer_interface_dylibloader_orig_wayland_client
#define wl_keyboard_interface wl_keyboard_interface_dylibloader_orig_wayland_client
#define wl_touch_interface wl_touch_interface_dylibloader_orig_wayland_client
#define wl_output_interface wl_output_interface_dylibloader_orig_wayland_client
#define wl_region_interface wl_region_interface_dylibloader_orig_wayland_client
#define wl_subcompositor_interface wl_subcompositor_interface_dylibloader_orig_wayland_client
#define wl_subsurface_interface wl_subsurface_interface_dylibloader_orig_wayland_client
#include <wayland-client.h>
#include <wayland-client-core.h>
#include <wayland-client-protocol.h>
#undef wl_event_queue_destroy
#undef wl_proxy_marshal
#undef wl_proxy_marshal_array
#undef wl_proxy_create
#undef wl_proxy_create_wrapper
#undef wl_proxy_wrapper_destroy
#undef wl_proxy_marshal_constructor
#undef wl_proxy_marshal_constructor_versioned
#undef wl_proxy_marshal_array_constructor
#undef wl_proxy_marshal_array_constructor_versioned
#undef wl_proxy_destroy
#undef wl_proxy_add_listener
#undef wl_proxy_get_listener
#undef wl_proxy_add_dispatcher
#undef wl_proxy_set_user_data
#undef wl_proxy_get_user_data
#undef wl_proxy_get_version
#undef wl_proxy_get_id
#undef wl_proxy_set_tag
#undef wl_proxy_get_tag
#undef wl_proxy_get_class
#undef wl_proxy_set_queue
#undef wl_display_connect
#undef wl_display_connect_to_fd
#undef wl_display_disconnect
#undef wl_display_get_fd
#undef wl_display_dispatch
#undef wl_display_dispatch_queue
#undef wl_display_dispatch_queue_pending
#undef wl_display_dispatch_pending
#undef wl_display_get_error
#undef wl_display_get_protocol_error
#undef wl_display_flush
#undef wl_display_roundtrip_queue
#undef wl_display_roundtrip
#undef wl_display_create_queue
#undef wl_display_prepare_read_queue
#undef wl_display_prepare_read
#undef wl_display_cancel_read
#undef wl_display_read_events
#undef wl_log_set_handler_client
#undef wl_display_interface
#undef wl_registry_interface
#undef wl_callback_interface
#undef wl_compositor_interface
#undef wl_shm_pool_interface
#undef wl_shm_interface
#undef wl_buffer_interface
#undef wl_data_offer_interface
#undef wl_data_source_interface
#undef wl_data_device_interface
#undef wl_data_device_manager_interface
#undef wl_shell_interface
#undef wl_shell_surface_interface
#undef wl_surface_interface
#undef wl_seat_interface
#undef wl_pointer_interface
#undef wl_keyboard_interface
#undef wl_touch_interface
#undef wl_output_interface
#undef wl_region_interface
#undef wl_subcompositor_interface
#undef wl_subsurface_interface
#include <dlfcn.h>
#include <stdio.h>
void (*wl_event_queue_destroy_dylibloader_wrapper_wayland_client)(struct wl_event_queue *);
void (*wl_proxy_marshal_dylibloader_wrapper_wayland_client)(struct wl_proxy *, uint32_t, ...);
void (*wl_proxy_marshal_array_dylibloader_wrapper_wayland_client)(struct wl_proxy *, uint32_t, union wl_argument *);
struct wl_proxy *(*wl_proxy_create_dylibloader_wrapper_wayland_client)(struct wl_proxy *, const struct wl_interface *);
void *(*wl_proxy_create_wrapper_dylibloader_wrapper_wayland_client)(void *);
void (*wl_proxy_wrapper_destroy_dylibloader_wrapper_wayland_client)(void *);
struct wl_proxy *(*wl_proxy_marshal_constructor_dylibloader_wrapper_wayland_client)(struct wl_proxy *, uint32_t, const struct wl_interface *, ...);
struct wl_proxy *(*wl_proxy_marshal_constructor_versioned_dylibloader_wrapper_wayland_client)(struct wl_proxy *, uint32_t, const struct wl_interface *, uint32_t, ...);
struct wl_proxy *(*wl_proxy_marshal_array_constructor_dylibloader_wrapper_wayland_client)(struct wl_proxy *, uint32_t, union wl_argument *, const struct wl_interface *);
struct wl_proxy *(*wl_proxy_marshal_array_constructor_versioned_dylibloader_wrapper_wayland_client)(struct wl_proxy *, uint32_t, union wl_argument *, const struct wl_interface *, uint32_t);
void (*wl_proxy_destroy_dylibloader_wrapper_wayland_client)(struct wl_proxy *);
int (*wl_proxy_add_listener_dylibloader_wrapper_wayland_client)(struct wl_proxy *, void (**)(void), void *);
const void *(*wl_proxy_get_listener_dylibloader_wrapper_wayland_client)(struct wl_proxy *);
int (*wl_proxy_add_dispatcher_dylibloader_wrapper_wayland_client)(struct wl_proxy *, wl_dispatcher_func_t, const void *, void *);
void (*wl_proxy_set_user_data_dylibloader_wrapper_wayland_client)(struct wl_proxy *, void *);
void *(*wl_proxy_get_user_data_dylibloader_wrapper_wayland_client)(struct wl_proxy *);
uint32_t (*wl_proxy_get_version_dylibloader_wrapper_wayland_client)(struct wl_proxy *);
uint32_t (*wl_proxy_get_id_dylibloader_wrapper_wayland_client)(struct wl_proxy *);
void (*wl_proxy_set_tag_dylibloader_wrapper_wayland_client)(struct wl_proxy *, const char * const *);
const char * const *(*wl_proxy_get_tag_dylibloader_wrapper_wayland_client)(struct wl_proxy *);
const char *(*wl_proxy_get_class_dylibloader_wrapper_wayland_client)(struct wl_proxy *);
void (*wl_proxy_set_queue_dylibloader_wrapper_wayland_client)(struct wl_proxy *, struct wl_event_queue *);
struct wl_display *(*wl_display_connect_dylibloader_wrapper_wayland_client)(const char *);
struct wl_display *(*wl_display_connect_to_fd_dylibloader_wrapper_wayland_client)(int);
void (*wl_display_disconnect_dylibloader_wrapper_wayland_client)(struct wl_display *);
int (*wl_display_get_fd_dylibloader_wrapper_wayland_client)(struct wl_display *);
int (*wl_display_dispatch_dylibloader_wrapper_wayland_client)(struct wl_display *);
int (*wl_display_dispatch_queue_dylibloader_wrapper_wayland_client)(struct wl_display *, struct wl_event_queue *);
int (*wl_display_dispatch_queue_pending_dylibloader_wrapper_wayland_client)(struct wl_display *, struct wl_event_queue *);
int (*wl_display_dispatch_pending_dylibloader_wrapper_wayland_client)(struct wl_display *);
int (*wl_display_get_error_dylibloader_wrapper_wayland_client)(struct wl_display *);
uint32_t (*wl_display_get_protocol_error_dylibloader_wrapper_wayland_client)(struct wl_display *, const struct wl_interface **, uint32_t *);
int (*wl_display_flush_dylibloader_wrapper_wayland_client)(struct wl_display *);
int (*wl_display_roundtrip_queue_dylibloader_wrapper_wayland_client)(struct wl_display *, struct wl_event_queue *);
int (*wl_display_roundtrip_dylibloader_wrapper_wayland_client)(struct wl_display *);
struct wl_event_queue *(*wl_display_create_queue_dylibloader_wrapper_wayland_client)(struct wl_display *);
int (*wl_display_prepare_read_queue_dylibloader_wrapper_wayland_client)(struct wl_display *, struct wl_event_queue *);
int (*wl_display_prepare_read_dylibloader_wrapper_wayland_client)(struct wl_display *);
void (*wl_display_cancel_read_dylibloader_wrapper_wayland_client)(struct wl_display *);
int (*wl_display_read_events_dylibloader_wrapper_wayland_client)(struct wl_display *);
void (*wl_log_set_handler_client_dylibloader_wrapper_wayland_client)(wl_log_func_t);
const struct wl_interface *wl_display_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_registry_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_callback_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_compositor_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_shm_pool_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_shm_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_buffer_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_data_offer_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_data_source_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_data_device_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_data_device_manager_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_shell_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_shell_surface_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_surface_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_seat_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_pointer_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_keyboard_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_touch_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_output_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_region_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_subcompositor_interface_dylibloader_wrapper_wayland_client;
const struct wl_interface *wl_subsurface_interface_dylibloader_wrapper_wayland_client;
int initialize_wayland_client(int verbose) {
  void *handle;
  char *error;
  handle = dlopen("libwayland-client.so.0", RTLD_LAZY);
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
/* wl_event_queue_destroy */
  *(void **) (&wl_event_queue_destroy_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_event_queue_destroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_marshal */
  *(void **) (&wl_proxy_marshal_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_marshal");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_marshal_array */
  *(void **) (&wl_proxy_marshal_array_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_marshal_array");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_create */
  *(void **) (&wl_proxy_create_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_create");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_create_wrapper */
  *(void **) (&wl_proxy_create_wrapper_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_create_wrapper");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_wrapper_destroy */
  *(void **) (&wl_proxy_wrapper_destroy_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_wrapper_destroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_marshal_constructor */
  *(void **) (&wl_proxy_marshal_constructor_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_marshal_constructor");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_marshal_constructor_versioned */
  *(void **) (&wl_proxy_marshal_constructor_versioned_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_marshal_constructor_versioned");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_marshal_array_constructor */
  *(void **) (&wl_proxy_marshal_array_constructor_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_marshal_array_constructor");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_marshal_array_constructor_versioned */
  *(void **) (&wl_proxy_marshal_array_constructor_versioned_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_marshal_array_constructor_versioned");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_destroy */
  *(void **) (&wl_proxy_destroy_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_destroy");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_add_listener */
  *(void **) (&wl_proxy_add_listener_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_add_listener");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_get_listener */
  *(void **) (&wl_proxy_get_listener_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_get_listener");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_add_dispatcher */
  *(void **) (&wl_proxy_add_dispatcher_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_add_dispatcher");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_set_user_data */
  *(void **) (&wl_proxy_set_user_data_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_set_user_data");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_get_user_data */
  *(void **) (&wl_proxy_get_user_data_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_get_user_data");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_get_version */
  *(void **) (&wl_proxy_get_version_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_get_version");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_get_id */
  *(void **) (&wl_proxy_get_id_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_get_id");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_set_tag */
  *(void **) (&wl_proxy_set_tag_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_set_tag");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_get_tag */
  *(void **) (&wl_proxy_get_tag_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_get_tag");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_get_class */
  *(void **) (&wl_proxy_get_class_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_get_class");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_proxy_set_queue */
  *(void **) (&wl_proxy_set_queue_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_proxy_set_queue");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_connect */
  *(void **) (&wl_display_connect_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_connect");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_connect_to_fd */
  *(void **) (&wl_display_connect_to_fd_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_connect_to_fd");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_disconnect */
  *(void **) (&wl_display_disconnect_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_disconnect");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_get_fd */
  *(void **) (&wl_display_get_fd_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_get_fd");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_dispatch */
  *(void **) (&wl_display_dispatch_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_dispatch");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_dispatch_queue */
  *(void **) (&wl_display_dispatch_queue_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_dispatch_queue");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_dispatch_queue_pending */
  *(void **) (&wl_display_dispatch_queue_pending_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_dispatch_queue_pending");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_dispatch_pending */
  *(void **) (&wl_display_dispatch_pending_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_dispatch_pending");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_get_error */
  *(void **) (&wl_display_get_error_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_get_error");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_get_protocol_error */
  *(void **) (&wl_display_get_protocol_error_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_get_protocol_error");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_flush */
  *(void **) (&wl_display_flush_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_flush");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_roundtrip_queue */
  *(void **) (&wl_display_roundtrip_queue_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_roundtrip_queue");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_roundtrip */
  *(void **) (&wl_display_roundtrip_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_roundtrip");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_create_queue */
  *(void **) (&wl_display_create_queue_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_create_queue");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_prepare_read_queue */
  *(void **) (&wl_display_prepare_read_queue_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_prepare_read_queue");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_prepare_read */
  *(void **) (&wl_display_prepare_read_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_prepare_read");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_cancel_read */
  *(void **) (&wl_display_cancel_read_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_cancel_read");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_read_events */
  *(void **) (&wl_display_read_events_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_read_events");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_log_set_handler_client */
  *(void **) (&wl_log_set_handler_client_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_log_set_handler_client");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_display_interface */
  *(void **) (&wl_display_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_display_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_registry_interface */
  *(void **) (&wl_registry_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_registry_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_callback_interface */
  *(void **) (&wl_callback_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_callback_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_compositor_interface */
  *(void **) (&wl_compositor_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_compositor_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_shm_pool_interface */
  *(void **) (&wl_shm_pool_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_shm_pool_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_shm_interface */
  *(void **) (&wl_shm_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_shm_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_buffer_interface */
  *(void **) (&wl_buffer_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_buffer_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_data_offer_interface */
  *(void **) (&wl_data_offer_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_data_offer_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_data_source_interface */
  *(void **) (&wl_data_source_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_data_source_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_data_device_interface */
  *(void **) (&wl_data_device_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_data_device_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_data_device_manager_interface */
  *(void **) (&wl_data_device_manager_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_data_device_manager_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_shell_interface */
  *(void **) (&wl_shell_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_shell_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_shell_surface_interface */
  *(void **) (&wl_shell_surface_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_shell_surface_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_surface_interface */
  *(void **) (&wl_surface_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_surface_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_seat_interface */
  *(void **) (&wl_seat_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_seat_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_pointer_interface */
  *(void **) (&wl_pointer_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_pointer_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_keyboard_interface */
  *(void **) (&wl_keyboard_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_keyboard_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_touch_interface */
  *(void **) (&wl_touch_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_touch_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_output_interface */
  *(void **) (&wl_output_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_output_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_region_interface */
  *(void **) (&wl_region_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_region_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_subcompositor_interface */
  *(void **) (&wl_subcompositor_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_subcompositor_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* wl_subsurface_interface */
  *(void **) (&wl_subsurface_interface_dylibloader_wrapper_wayland_client) = dlsym(handle, "wl_subsurface_interface");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
return 0;
}
