/* This file is generated. Do not edit!
   see https://github.com/hpvb/dynload-wrapper (patched) for details
   generated by scripts/generate-wrapper.py 0.5
   flags: scripts/generate-wrapper.py --include include/xcb/xcb_icccm.h --sys-include xcb-so_wrap.h --sys-include <xcb/xcb_icccm.h> --soname libxcb-icccm.so.4 --init-name xcb_icccm --output-header include_gen/xcb_icccm-so_wrap.h --output-implementation src_gen/xcb_icccm-so_wrap.c --ignore-other --include-dir include
*/
#include <stdint.h>

#define xcb_icccm_get_text_property xcb_icccm_get_text_property_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_text_property_unchecked xcb_icccm_get_text_property_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_text_property_reply xcb_icccm_get_text_property_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_text_property_reply_wipe xcb_icccm_get_text_property_reply_wipe_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_name_checked xcb_icccm_set_wm_name_checked_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_name xcb_icccm_set_wm_name_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_name xcb_icccm_get_wm_name_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_name_unchecked xcb_icccm_get_wm_name_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_name_reply xcb_icccm_get_wm_name_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_icon_name_checked xcb_icccm_set_wm_icon_name_checked_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_icon_name xcb_icccm_set_wm_icon_name_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_icon_name xcb_icccm_get_wm_icon_name_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_icon_name_unchecked xcb_icccm_get_wm_icon_name_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_icon_name_reply xcb_icccm_get_wm_icon_name_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_colormap_windows_checked xcb_icccm_set_wm_colormap_windows_checked_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_colormap_windows xcb_icccm_set_wm_colormap_windows_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_colormap_windows xcb_icccm_get_wm_colormap_windows_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_colormap_windows_unchecked xcb_icccm_get_wm_colormap_windows_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_colormap_windows_from_reply xcb_icccm_get_wm_colormap_windows_from_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_colormap_windows_reply xcb_icccm_get_wm_colormap_windows_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_colormap_windows_reply_wipe xcb_icccm_get_wm_colormap_windows_reply_wipe_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_client_machine_checked xcb_icccm_set_wm_client_machine_checked_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_client_machine xcb_icccm_set_wm_client_machine_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_client_machine xcb_icccm_get_wm_client_machine_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_client_machine_unchecked xcb_icccm_get_wm_client_machine_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_client_machine_reply xcb_icccm_get_wm_client_machine_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_class_checked xcb_icccm_set_wm_class_checked_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_class xcb_icccm_set_wm_class_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_class xcb_icccm_get_wm_class_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_class_unchecked xcb_icccm_get_wm_class_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_class_from_reply xcb_icccm_get_wm_class_from_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_class_reply xcb_icccm_get_wm_class_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_class_reply_wipe xcb_icccm_get_wm_class_reply_wipe_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_transient_for_checked xcb_icccm_set_wm_transient_for_checked_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_transient_for xcb_icccm_set_wm_transient_for_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_transient_for xcb_icccm_get_wm_transient_for_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_transient_for_unchecked xcb_icccm_get_wm_transient_for_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_transient_for_from_reply xcb_icccm_get_wm_transient_for_from_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_transient_for_reply xcb_icccm_get_wm_transient_for_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_size_hints_set_position xcb_icccm_size_hints_set_position_dylibloader_orig_xcb_icccm
#define xcb_icccm_size_hints_set_size xcb_icccm_size_hints_set_size_dylibloader_orig_xcb_icccm
#define xcb_icccm_size_hints_set_min_size xcb_icccm_size_hints_set_min_size_dylibloader_orig_xcb_icccm
#define xcb_icccm_size_hints_set_max_size xcb_icccm_size_hints_set_max_size_dylibloader_orig_xcb_icccm
#define xcb_icccm_size_hints_set_resize_inc xcb_icccm_size_hints_set_resize_inc_dylibloader_orig_xcb_icccm
#define xcb_icccm_size_hints_set_aspect xcb_icccm_size_hints_set_aspect_dylibloader_orig_xcb_icccm
#define xcb_icccm_size_hints_set_base_size xcb_icccm_size_hints_set_base_size_dylibloader_orig_xcb_icccm
#define xcb_icccm_size_hints_set_win_gravity xcb_icccm_size_hints_set_win_gravity_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_size_hints_checked xcb_icccm_set_wm_size_hints_checked_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_size_hints xcb_icccm_set_wm_size_hints_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_size_hints xcb_icccm_get_wm_size_hints_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_size_hints_unchecked xcb_icccm_get_wm_size_hints_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_size_hints_reply xcb_icccm_get_wm_size_hints_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_normal_hints_checked xcb_icccm_set_wm_normal_hints_checked_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_normal_hints xcb_icccm_set_wm_normal_hints_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_normal_hints xcb_icccm_get_wm_normal_hints_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_normal_hints_unchecked xcb_icccm_get_wm_normal_hints_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_size_hints_from_reply xcb_icccm_get_wm_size_hints_from_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_normal_hints_reply xcb_icccm_get_wm_normal_hints_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_get_urgency xcb_icccm_wm_hints_get_urgency_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_set_input xcb_icccm_wm_hints_set_input_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_set_iconic xcb_icccm_wm_hints_set_iconic_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_set_normal xcb_icccm_wm_hints_set_normal_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_set_withdrawn xcb_icccm_wm_hints_set_withdrawn_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_set_none xcb_icccm_wm_hints_set_none_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_set_icon_pixmap xcb_icccm_wm_hints_set_icon_pixmap_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_set_icon_mask xcb_icccm_wm_hints_set_icon_mask_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_set_icon_window xcb_icccm_wm_hints_set_icon_window_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_set_window_group xcb_icccm_wm_hints_set_window_group_dylibloader_orig_xcb_icccm
#define xcb_icccm_wm_hints_set_urgency xcb_icccm_wm_hints_set_urgency_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_hints_checked xcb_icccm_set_wm_hints_checked_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_hints xcb_icccm_set_wm_hints_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_hints xcb_icccm_get_wm_hints_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_hints_unchecked xcb_icccm_get_wm_hints_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_hints_from_reply xcb_icccm_get_wm_hints_from_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_hints_reply xcb_icccm_get_wm_hints_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_protocols_checked xcb_icccm_set_wm_protocols_checked_dylibloader_orig_xcb_icccm
#define xcb_icccm_set_wm_protocols xcb_icccm_set_wm_protocols_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_protocols xcb_icccm_get_wm_protocols_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_protocols_unchecked xcb_icccm_get_wm_protocols_unchecked_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_protocols_from_reply xcb_icccm_get_wm_protocols_from_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_protocols_reply xcb_icccm_get_wm_protocols_reply_dylibloader_orig_xcb_icccm
#define xcb_icccm_get_wm_protocols_reply_wipe xcb_icccm_get_wm_protocols_reply_wipe_dylibloader_orig_xcb_icccm
#include "xcb-so_wrap.h"
#include <xcb/xcb_icccm.h>
#undef xcb_icccm_get_text_property
#undef xcb_icccm_get_text_property_unchecked
#undef xcb_icccm_get_text_property_reply
#undef xcb_icccm_get_text_property_reply_wipe
#undef xcb_icccm_set_wm_name_checked
#undef xcb_icccm_set_wm_name
#undef xcb_icccm_get_wm_name
#undef xcb_icccm_get_wm_name_unchecked
#undef xcb_icccm_get_wm_name_reply
#undef xcb_icccm_set_wm_icon_name_checked
#undef xcb_icccm_set_wm_icon_name
#undef xcb_icccm_get_wm_icon_name
#undef xcb_icccm_get_wm_icon_name_unchecked
#undef xcb_icccm_get_wm_icon_name_reply
#undef xcb_icccm_set_wm_colormap_windows_checked
#undef xcb_icccm_set_wm_colormap_windows
#undef xcb_icccm_get_wm_colormap_windows
#undef xcb_icccm_get_wm_colormap_windows_unchecked
#undef xcb_icccm_get_wm_colormap_windows_from_reply
#undef xcb_icccm_get_wm_colormap_windows_reply
#undef xcb_icccm_get_wm_colormap_windows_reply_wipe
#undef xcb_icccm_set_wm_client_machine_checked
#undef xcb_icccm_set_wm_client_machine
#undef xcb_icccm_get_wm_client_machine
#undef xcb_icccm_get_wm_client_machine_unchecked
#undef xcb_icccm_get_wm_client_machine_reply
#undef xcb_icccm_set_wm_class_checked
#undef xcb_icccm_set_wm_class
#undef xcb_icccm_get_wm_class
#undef xcb_icccm_get_wm_class_unchecked
#undef xcb_icccm_get_wm_class_from_reply
#undef xcb_icccm_get_wm_class_reply
#undef xcb_icccm_get_wm_class_reply_wipe
#undef xcb_icccm_set_wm_transient_for_checked
#undef xcb_icccm_set_wm_transient_for
#undef xcb_icccm_get_wm_transient_for
#undef xcb_icccm_get_wm_transient_for_unchecked
#undef xcb_icccm_get_wm_transient_for_from_reply
#undef xcb_icccm_get_wm_transient_for_reply
#undef xcb_icccm_size_hints_set_position
#undef xcb_icccm_size_hints_set_size
#undef xcb_icccm_size_hints_set_min_size
#undef xcb_icccm_size_hints_set_max_size
#undef xcb_icccm_size_hints_set_resize_inc
#undef xcb_icccm_size_hints_set_aspect
#undef xcb_icccm_size_hints_set_base_size
#undef xcb_icccm_size_hints_set_win_gravity
#undef xcb_icccm_set_wm_size_hints_checked
#undef xcb_icccm_set_wm_size_hints
#undef xcb_icccm_get_wm_size_hints
#undef xcb_icccm_get_wm_size_hints_unchecked
#undef xcb_icccm_get_wm_size_hints_reply
#undef xcb_icccm_set_wm_normal_hints_checked
#undef xcb_icccm_set_wm_normal_hints
#undef xcb_icccm_get_wm_normal_hints
#undef xcb_icccm_get_wm_normal_hints_unchecked
#undef xcb_icccm_get_wm_size_hints_from_reply
#undef xcb_icccm_get_wm_normal_hints_reply
#undef xcb_icccm_wm_hints_get_urgency
#undef xcb_icccm_wm_hints_set_input
#undef xcb_icccm_wm_hints_set_iconic
#undef xcb_icccm_wm_hints_set_normal
#undef xcb_icccm_wm_hints_set_withdrawn
#undef xcb_icccm_wm_hints_set_none
#undef xcb_icccm_wm_hints_set_icon_pixmap
#undef xcb_icccm_wm_hints_set_icon_mask
#undef xcb_icccm_wm_hints_set_icon_window
#undef xcb_icccm_wm_hints_set_window_group
#undef xcb_icccm_wm_hints_set_urgency
#undef xcb_icccm_set_wm_hints_checked
#undef xcb_icccm_set_wm_hints
#undef xcb_icccm_get_wm_hints
#undef xcb_icccm_get_wm_hints_unchecked
#undef xcb_icccm_get_wm_hints_from_reply
#undef xcb_icccm_get_wm_hints_reply
#undef xcb_icccm_set_wm_protocols_checked
#undef xcb_icccm_set_wm_protocols
#undef xcb_icccm_get_wm_protocols
#undef xcb_icccm_get_wm_protocols_unchecked
#undef xcb_icccm_get_wm_protocols_from_reply
#undef xcb_icccm_get_wm_protocols_reply
#undef xcb_icccm_get_wm_protocols_reply_wipe
#include <dlfcn.h>
#include <stdio.h>
xcb_get_property_cookie_t (*xcb_icccm_get_text_property_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t);
xcb_get_property_cookie_t (*xcb_icccm_get_text_property_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t);
uint8_t (*xcb_icccm_get_text_property_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_icccm_get_text_property_reply_t *, xcb_generic_error_t **);
void (*xcb_icccm_get_text_property_reply_wipe_dylibloader_wrapper_xcb_icccm)(xcb_icccm_get_text_property_reply_t *);
xcb_void_cookie_t (*xcb_icccm_set_wm_name_checked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint8_t, uint32_t, const char *);
xcb_void_cookie_t (*xcb_icccm_set_wm_name_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint8_t, uint32_t, const char *);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_name_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_name_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
uint8_t (*xcb_icccm_get_wm_name_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_icccm_get_text_property_reply_t *, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_icccm_set_wm_icon_name_checked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint8_t, uint32_t, const char *);
xcb_void_cookie_t (*xcb_icccm_set_wm_icon_name_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint8_t, uint32_t, const char *);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_icon_name_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_icon_name_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
uint8_t (*xcb_icccm_get_wm_icon_name_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_icccm_get_text_property_reply_t *, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_icccm_set_wm_colormap_windows_checked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint32_t, const xcb_window_t *);
xcb_void_cookie_t (*xcb_icccm_set_wm_colormap_windows_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint32_t, const xcb_window_t *);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_colormap_windows_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_colormap_windows_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t);
uint8_t (*xcb_icccm_get_wm_colormap_windows_from_reply_dylibloader_wrapper_xcb_icccm)(xcb_get_property_reply_t *, xcb_icccm_get_wm_colormap_windows_reply_t *);
uint8_t (*xcb_icccm_get_wm_colormap_windows_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_icccm_get_wm_colormap_windows_reply_t *, xcb_generic_error_t **);
void (*xcb_icccm_get_wm_colormap_windows_reply_wipe_dylibloader_wrapper_xcb_icccm)(xcb_icccm_get_wm_colormap_windows_reply_t *);
xcb_void_cookie_t (*xcb_icccm_set_wm_client_machine_checked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint8_t, uint32_t, const char *);
xcb_void_cookie_t (*xcb_icccm_set_wm_client_machine_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint8_t, uint32_t, const char *);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_client_machine_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_client_machine_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
uint8_t (*xcb_icccm_get_wm_client_machine_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_icccm_get_text_property_reply_t *, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_icccm_set_wm_class_checked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, uint32_t, const char *);
xcb_void_cookie_t (*xcb_icccm_set_wm_class_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, uint32_t, const char *);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_class_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_class_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
uint8_t (*xcb_icccm_get_wm_class_from_reply_dylibloader_wrapper_xcb_icccm)(xcb_icccm_get_wm_class_reply_t *, xcb_get_property_reply_t *);
uint8_t (*xcb_icccm_get_wm_class_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_icccm_get_wm_class_reply_t *, xcb_generic_error_t **);
void (*xcb_icccm_get_wm_class_reply_wipe_dylibloader_wrapper_xcb_icccm)(xcb_icccm_get_wm_class_reply_t *);
xcb_void_cookie_t (*xcb_icccm_set_wm_transient_for_checked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_window_t);
xcb_void_cookie_t (*xcb_icccm_set_wm_transient_for_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_window_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_transient_for_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_transient_for_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
uint8_t (*xcb_icccm_get_wm_transient_for_from_reply_dylibloader_wrapper_xcb_icccm)(xcb_window_t *, xcb_get_property_reply_t *);
uint8_t (*xcb_icccm_get_wm_transient_for_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_window_t *, xcb_generic_error_t **);
void (*xcb_icccm_size_hints_set_position_dylibloader_wrapper_xcb_icccm)(xcb_size_hints_t *, int, int32_t, int32_t);
void (*xcb_icccm_size_hints_set_size_dylibloader_wrapper_xcb_icccm)(xcb_size_hints_t *, int, int32_t, int32_t);
void (*xcb_icccm_size_hints_set_min_size_dylibloader_wrapper_xcb_icccm)(xcb_size_hints_t *, int32_t, int32_t);
void (*xcb_icccm_size_hints_set_max_size_dylibloader_wrapper_xcb_icccm)(xcb_size_hints_t *, int32_t, int32_t);
void (*xcb_icccm_size_hints_set_resize_inc_dylibloader_wrapper_xcb_icccm)(xcb_size_hints_t *, int32_t, int32_t);
void (*xcb_icccm_size_hints_set_aspect_dylibloader_wrapper_xcb_icccm)(xcb_size_hints_t *, int32_t, int32_t, int32_t, int32_t);
void (*xcb_icccm_size_hints_set_base_size_dylibloader_wrapper_xcb_icccm)(xcb_size_hints_t *, int32_t, int32_t);
void (*xcb_icccm_size_hints_set_win_gravity_dylibloader_wrapper_xcb_icccm)(xcb_size_hints_t *, xcb_gravity_t);
xcb_void_cookie_t (*xcb_icccm_set_wm_size_hints_checked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, xcb_size_hints_t *);
xcb_void_cookie_t (*xcb_icccm_set_wm_size_hints_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, xcb_size_hints_t *);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_size_hints_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_size_hints_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t);
uint8_t (*xcb_icccm_get_wm_size_hints_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_size_hints_t *, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_icccm_set_wm_normal_hints_checked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_size_hints_t *);
xcb_void_cookie_t (*xcb_icccm_set_wm_normal_hints_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_size_hints_t *);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_normal_hints_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_normal_hints_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
uint8_t (*xcb_icccm_get_wm_size_hints_from_reply_dylibloader_wrapper_xcb_icccm)(xcb_size_hints_t *, xcb_get_property_reply_t *);
uint8_t (*xcb_icccm_get_wm_normal_hints_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_size_hints_t *, xcb_generic_error_t **);
uint32_t (*xcb_icccm_wm_hints_get_urgency_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *);
void (*xcb_icccm_wm_hints_set_input_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *, uint8_t);
void (*xcb_icccm_wm_hints_set_iconic_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *);
void (*xcb_icccm_wm_hints_set_normal_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *);
void (*xcb_icccm_wm_hints_set_withdrawn_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *);
void (*xcb_icccm_wm_hints_set_none_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *);
void (*xcb_icccm_wm_hints_set_icon_pixmap_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *, xcb_pixmap_t);
void (*xcb_icccm_wm_hints_set_icon_mask_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *, xcb_pixmap_t);
void (*xcb_icccm_wm_hints_set_icon_window_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *, xcb_window_t);
void (*xcb_icccm_wm_hints_set_window_group_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *, xcb_window_t);
void (*xcb_icccm_wm_hints_set_urgency_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *);
xcb_void_cookie_t (*xcb_icccm_set_wm_hints_checked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_icccm_wm_hints_t *);
xcb_void_cookie_t (*xcb_icccm_set_wm_hints_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_icccm_wm_hints_t *);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_hints_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_hints_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t);
uint8_t (*xcb_icccm_get_wm_hints_from_reply_dylibloader_wrapper_xcb_icccm)(xcb_icccm_wm_hints_t *, xcb_get_property_reply_t *);
uint8_t (*xcb_icccm_get_wm_hints_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_icccm_wm_hints_t *, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_icccm_set_wm_protocols_checked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint32_t, xcb_atom_t *);
xcb_void_cookie_t (*xcb_icccm_set_wm_protocols_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint32_t, xcb_atom_t *);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_protocols_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t);
xcb_get_property_cookie_t (*xcb_icccm_get_wm_protocols_unchecked_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_window_t, xcb_atom_t);
uint8_t (*xcb_icccm_get_wm_protocols_from_reply_dylibloader_wrapper_xcb_icccm)(xcb_get_property_reply_t *, xcb_icccm_get_wm_protocols_reply_t *);
uint8_t (*xcb_icccm_get_wm_protocols_reply_dylibloader_wrapper_xcb_icccm)(xcb_connection_t *, xcb_get_property_cookie_t, xcb_icccm_get_wm_protocols_reply_t *, xcb_generic_error_t **);
void (*xcb_icccm_get_wm_protocols_reply_wipe_dylibloader_wrapper_xcb_icccm)(xcb_icccm_get_wm_protocols_reply_t *);
int initialize_xcb_icccm(int verbose) {
  void *handle;
  char *error;
  handle = dlopen("libxcb-icccm.so.4", RTLD_LAZY);
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
/* xcb_icccm_get_text_property */
  *(void **) (&xcb_icccm_get_text_property_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_text_property");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_text_property_unchecked */
  *(void **) (&xcb_icccm_get_text_property_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_text_property_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_text_property_reply */
  *(void **) (&xcb_icccm_get_text_property_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_text_property_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_text_property_reply_wipe */
  *(void **) (&xcb_icccm_get_text_property_reply_wipe_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_text_property_reply_wipe");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_name_checked */
  *(void **) (&xcb_icccm_set_wm_name_checked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_name_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_name */
  *(void **) (&xcb_icccm_set_wm_name_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_name */
  *(void **) (&xcb_icccm_get_wm_name_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_name_unchecked */
  *(void **) (&xcb_icccm_get_wm_name_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_name_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_name_reply */
  *(void **) (&xcb_icccm_get_wm_name_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_name_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_icon_name_checked */
  *(void **) (&xcb_icccm_set_wm_icon_name_checked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_icon_name_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_icon_name */
  *(void **) (&xcb_icccm_set_wm_icon_name_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_icon_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_icon_name */
  *(void **) (&xcb_icccm_get_wm_icon_name_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_icon_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_icon_name_unchecked */
  *(void **) (&xcb_icccm_get_wm_icon_name_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_icon_name_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_icon_name_reply */
  *(void **) (&xcb_icccm_get_wm_icon_name_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_icon_name_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_colormap_windows_checked */
  *(void **) (&xcb_icccm_set_wm_colormap_windows_checked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_colormap_windows_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_colormap_windows */
  *(void **) (&xcb_icccm_set_wm_colormap_windows_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_colormap_windows");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_colormap_windows */
  *(void **) (&xcb_icccm_get_wm_colormap_windows_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_colormap_windows");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_colormap_windows_unchecked */
  *(void **) (&xcb_icccm_get_wm_colormap_windows_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_colormap_windows_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_colormap_windows_from_reply */
  *(void **) (&xcb_icccm_get_wm_colormap_windows_from_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_colormap_windows_from_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_colormap_windows_reply */
  *(void **) (&xcb_icccm_get_wm_colormap_windows_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_colormap_windows_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_colormap_windows_reply_wipe */
  *(void **) (&xcb_icccm_get_wm_colormap_windows_reply_wipe_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_colormap_windows_reply_wipe");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_client_machine_checked */
  *(void **) (&xcb_icccm_set_wm_client_machine_checked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_client_machine_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_client_machine */
  *(void **) (&xcb_icccm_set_wm_client_machine_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_client_machine");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_client_machine */
  *(void **) (&xcb_icccm_get_wm_client_machine_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_client_machine");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_client_machine_unchecked */
  *(void **) (&xcb_icccm_get_wm_client_machine_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_client_machine_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_client_machine_reply */
  *(void **) (&xcb_icccm_get_wm_client_machine_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_client_machine_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_class_checked */
  *(void **) (&xcb_icccm_set_wm_class_checked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_class_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_class */
  *(void **) (&xcb_icccm_set_wm_class_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_class");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_class */
  *(void **) (&xcb_icccm_get_wm_class_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_class");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_class_unchecked */
  *(void **) (&xcb_icccm_get_wm_class_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_class_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_class_from_reply */
  *(void **) (&xcb_icccm_get_wm_class_from_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_class_from_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_class_reply */
  *(void **) (&xcb_icccm_get_wm_class_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_class_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_class_reply_wipe */
  *(void **) (&xcb_icccm_get_wm_class_reply_wipe_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_class_reply_wipe");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_transient_for_checked */
  *(void **) (&xcb_icccm_set_wm_transient_for_checked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_transient_for_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_transient_for */
  *(void **) (&xcb_icccm_set_wm_transient_for_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_transient_for");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_transient_for */
  *(void **) (&xcb_icccm_get_wm_transient_for_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_transient_for");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_transient_for_unchecked */
  *(void **) (&xcb_icccm_get_wm_transient_for_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_transient_for_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_transient_for_from_reply */
  *(void **) (&xcb_icccm_get_wm_transient_for_from_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_transient_for_from_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_transient_for_reply */
  *(void **) (&xcb_icccm_get_wm_transient_for_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_transient_for_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_size_hints_set_position */
  *(void **) (&xcb_icccm_size_hints_set_position_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_size_hints_set_position");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_size_hints_set_size */
  *(void **) (&xcb_icccm_size_hints_set_size_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_size_hints_set_size");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_size_hints_set_min_size */
  *(void **) (&xcb_icccm_size_hints_set_min_size_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_size_hints_set_min_size");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_size_hints_set_max_size */
  *(void **) (&xcb_icccm_size_hints_set_max_size_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_size_hints_set_max_size");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_size_hints_set_resize_inc */
  *(void **) (&xcb_icccm_size_hints_set_resize_inc_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_size_hints_set_resize_inc");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_size_hints_set_aspect */
  *(void **) (&xcb_icccm_size_hints_set_aspect_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_size_hints_set_aspect");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_size_hints_set_base_size */
  *(void **) (&xcb_icccm_size_hints_set_base_size_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_size_hints_set_base_size");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_size_hints_set_win_gravity */
  *(void **) (&xcb_icccm_size_hints_set_win_gravity_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_size_hints_set_win_gravity");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_size_hints_checked */
  *(void **) (&xcb_icccm_set_wm_size_hints_checked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_size_hints_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_size_hints */
  *(void **) (&xcb_icccm_set_wm_size_hints_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_size_hints");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_size_hints */
  *(void **) (&xcb_icccm_get_wm_size_hints_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_size_hints");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_size_hints_unchecked */
  *(void **) (&xcb_icccm_get_wm_size_hints_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_size_hints_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_size_hints_reply */
  *(void **) (&xcb_icccm_get_wm_size_hints_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_size_hints_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_normal_hints_checked */
  *(void **) (&xcb_icccm_set_wm_normal_hints_checked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_normal_hints_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_normal_hints */
  *(void **) (&xcb_icccm_set_wm_normal_hints_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_normal_hints");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_normal_hints */
  *(void **) (&xcb_icccm_get_wm_normal_hints_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_normal_hints");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_normal_hints_unchecked */
  *(void **) (&xcb_icccm_get_wm_normal_hints_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_normal_hints_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_size_hints_from_reply */
  *(void **) (&xcb_icccm_get_wm_size_hints_from_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_size_hints_from_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_normal_hints_reply */
  *(void **) (&xcb_icccm_get_wm_normal_hints_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_normal_hints_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_get_urgency */
  *(void **) (&xcb_icccm_wm_hints_get_urgency_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_get_urgency");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_set_input */
  *(void **) (&xcb_icccm_wm_hints_set_input_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_set_input");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_set_iconic */
  *(void **) (&xcb_icccm_wm_hints_set_iconic_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_set_iconic");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_set_normal */
  *(void **) (&xcb_icccm_wm_hints_set_normal_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_set_normal");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_set_withdrawn */
  *(void **) (&xcb_icccm_wm_hints_set_withdrawn_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_set_withdrawn");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_set_none */
  *(void **) (&xcb_icccm_wm_hints_set_none_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_set_none");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_set_icon_pixmap */
  *(void **) (&xcb_icccm_wm_hints_set_icon_pixmap_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_set_icon_pixmap");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_set_icon_mask */
  *(void **) (&xcb_icccm_wm_hints_set_icon_mask_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_set_icon_mask");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_set_icon_window */
  *(void **) (&xcb_icccm_wm_hints_set_icon_window_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_set_icon_window");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_set_window_group */
  *(void **) (&xcb_icccm_wm_hints_set_window_group_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_set_window_group");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_wm_hints_set_urgency */
  *(void **) (&xcb_icccm_wm_hints_set_urgency_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_wm_hints_set_urgency");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_hints_checked */
  *(void **) (&xcb_icccm_set_wm_hints_checked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_hints_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_hints */
  *(void **) (&xcb_icccm_set_wm_hints_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_hints");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_hints */
  *(void **) (&xcb_icccm_get_wm_hints_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_hints");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_hints_unchecked */
  *(void **) (&xcb_icccm_get_wm_hints_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_hints_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_hints_from_reply */
  *(void **) (&xcb_icccm_get_wm_hints_from_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_hints_from_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_hints_reply */
  *(void **) (&xcb_icccm_get_wm_hints_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_hints_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_protocols_checked */
  *(void **) (&xcb_icccm_set_wm_protocols_checked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_protocols_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_set_wm_protocols */
  *(void **) (&xcb_icccm_set_wm_protocols_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_set_wm_protocols");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_protocols */
  *(void **) (&xcb_icccm_get_wm_protocols_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_protocols");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_protocols_unchecked */
  *(void **) (&xcb_icccm_get_wm_protocols_unchecked_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_protocols_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_protocols_from_reply */
  *(void **) (&xcb_icccm_get_wm_protocols_from_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_protocols_from_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_protocols_reply */
  *(void **) (&xcb_icccm_get_wm_protocols_reply_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_protocols_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_icccm_get_wm_protocols_reply_wipe */
  *(void **) (&xcb_icccm_get_wm_protocols_reply_wipe_dylibloader_wrapper_xcb_icccm) = dlsym(handle, "xcb_icccm_get_wm_protocols_reply_wipe");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
return 0;
}
