// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper (patched) for details
// generated by scripts/generate-wrapper.py 0.5
// flags: scripts/generate-wrapper.py --include include/xcb/sync.h --sys-include xcb-so_wrap.h --sys-include <xcb/sync.h> --soname libxcb-sync.so.1 --init-name xcb_sync --output-header include_gen/xcb_sync-so_wrap.h --output-implementation src_gen/xcb_sync-so_wrap.c --ignore-other --include-dir include
//
#include <stdint.h>

#define xcb_sync_alarm_next xcb_sync_alarm_next_dylibloader_orig_xcb_sync
#define xcb_sync_alarm_end xcb_sync_alarm_end_dylibloader_orig_xcb_sync
#define xcb_sync_counter_next xcb_sync_counter_next_dylibloader_orig_xcb_sync
#define xcb_sync_counter_end xcb_sync_counter_end_dylibloader_orig_xcb_sync
#define xcb_sync_fence_next xcb_sync_fence_next_dylibloader_orig_xcb_sync
#define xcb_sync_fence_end xcb_sync_fence_end_dylibloader_orig_xcb_sync
#define xcb_sync_int64_next xcb_sync_int64_next_dylibloader_orig_xcb_sync
#define xcb_sync_int64_end xcb_sync_int64_end_dylibloader_orig_xcb_sync
#define xcb_sync_systemcounter_sizeof xcb_sync_systemcounter_sizeof_dylibloader_orig_xcb_sync
#define xcb_sync_systemcounter_name xcb_sync_systemcounter_name_dylibloader_orig_xcb_sync
#define xcb_sync_systemcounter_name_length xcb_sync_systemcounter_name_length_dylibloader_orig_xcb_sync
#define xcb_sync_systemcounter_name_end xcb_sync_systemcounter_name_end_dylibloader_orig_xcb_sync
#define xcb_sync_systemcounter_next xcb_sync_systemcounter_next_dylibloader_orig_xcb_sync
#define xcb_sync_systemcounter_end xcb_sync_systemcounter_end_dylibloader_orig_xcb_sync
#define xcb_sync_trigger_next xcb_sync_trigger_next_dylibloader_orig_xcb_sync
#define xcb_sync_trigger_end xcb_sync_trigger_end_dylibloader_orig_xcb_sync
#define xcb_sync_waitcondition_next xcb_sync_waitcondition_next_dylibloader_orig_xcb_sync
#define xcb_sync_waitcondition_end xcb_sync_waitcondition_end_dylibloader_orig_xcb_sync
#define xcb_sync_initialize xcb_sync_initialize_dylibloader_orig_xcb_sync
#define xcb_sync_initialize_unchecked xcb_sync_initialize_unchecked_dylibloader_orig_xcb_sync
#define xcb_sync_initialize_reply xcb_sync_initialize_reply_dylibloader_orig_xcb_sync
#define xcb_sync_list_system_counters_sizeof xcb_sync_list_system_counters_sizeof_dylibloader_orig_xcb_sync
#define xcb_sync_list_system_counters xcb_sync_list_system_counters_dylibloader_orig_xcb_sync
#define xcb_sync_list_system_counters_unchecked xcb_sync_list_system_counters_unchecked_dylibloader_orig_xcb_sync
#define xcb_sync_list_system_counters_counters_length xcb_sync_list_system_counters_counters_length_dylibloader_orig_xcb_sync
#define xcb_sync_list_system_counters_counters_iterator xcb_sync_list_system_counters_counters_iterator_dylibloader_orig_xcb_sync
#define xcb_sync_list_system_counters_reply xcb_sync_list_system_counters_reply_dylibloader_orig_xcb_sync
#define xcb_sync_create_counter_checked xcb_sync_create_counter_checked_dylibloader_orig_xcb_sync
#define xcb_sync_create_counter xcb_sync_create_counter_dylibloader_orig_xcb_sync
#define xcb_sync_destroy_counter_checked xcb_sync_destroy_counter_checked_dylibloader_orig_xcb_sync
#define xcb_sync_destroy_counter xcb_sync_destroy_counter_dylibloader_orig_xcb_sync
#define xcb_sync_query_counter xcb_sync_query_counter_dylibloader_orig_xcb_sync
#define xcb_sync_query_counter_unchecked xcb_sync_query_counter_unchecked_dylibloader_orig_xcb_sync
#define xcb_sync_query_counter_reply xcb_sync_query_counter_reply_dylibloader_orig_xcb_sync
#define xcb_sync_await_sizeof xcb_sync_await_sizeof_dylibloader_orig_xcb_sync
#define xcb_sync_await_checked xcb_sync_await_checked_dylibloader_orig_xcb_sync
#define xcb_sync_await xcb_sync_await_dylibloader_orig_xcb_sync
#define xcb_sync_await_wait_list xcb_sync_await_wait_list_dylibloader_orig_xcb_sync
#define xcb_sync_await_wait_list_length xcb_sync_await_wait_list_length_dylibloader_orig_xcb_sync
#define xcb_sync_await_wait_list_iterator xcb_sync_await_wait_list_iterator_dylibloader_orig_xcb_sync
#define xcb_sync_change_counter_checked xcb_sync_change_counter_checked_dylibloader_orig_xcb_sync
#define xcb_sync_change_counter xcb_sync_change_counter_dylibloader_orig_xcb_sync
#define xcb_sync_set_counter_checked xcb_sync_set_counter_checked_dylibloader_orig_xcb_sync
#define xcb_sync_set_counter xcb_sync_set_counter_dylibloader_orig_xcb_sync
#define xcb_sync_create_alarm_value_list_serialize xcb_sync_create_alarm_value_list_serialize_dylibloader_orig_xcb_sync
#define xcb_sync_create_alarm_value_list_unpack xcb_sync_create_alarm_value_list_unpack_dylibloader_orig_xcb_sync
#define xcb_sync_create_alarm_value_list_sizeof xcb_sync_create_alarm_value_list_sizeof_dylibloader_orig_xcb_sync
#define xcb_sync_create_alarm_sizeof xcb_sync_create_alarm_sizeof_dylibloader_orig_xcb_sync
#define xcb_sync_create_alarm_checked xcb_sync_create_alarm_checked_dylibloader_orig_xcb_sync
#define xcb_sync_create_alarm xcb_sync_create_alarm_dylibloader_orig_xcb_sync
#define xcb_sync_create_alarm_aux_checked xcb_sync_create_alarm_aux_checked_dylibloader_orig_xcb_sync
#define xcb_sync_create_alarm_aux xcb_sync_create_alarm_aux_dylibloader_orig_xcb_sync
#define xcb_sync_create_alarm_value_list xcb_sync_create_alarm_value_list_dylibloader_orig_xcb_sync
#define xcb_sync_change_alarm_value_list_serialize xcb_sync_change_alarm_value_list_serialize_dylibloader_orig_xcb_sync
#define xcb_sync_change_alarm_value_list_unpack xcb_sync_change_alarm_value_list_unpack_dylibloader_orig_xcb_sync
#define xcb_sync_change_alarm_value_list_sizeof xcb_sync_change_alarm_value_list_sizeof_dylibloader_orig_xcb_sync
#define xcb_sync_change_alarm_sizeof xcb_sync_change_alarm_sizeof_dylibloader_orig_xcb_sync
#define xcb_sync_change_alarm_checked xcb_sync_change_alarm_checked_dylibloader_orig_xcb_sync
#define xcb_sync_change_alarm xcb_sync_change_alarm_dylibloader_orig_xcb_sync
#define xcb_sync_change_alarm_aux_checked xcb_sync_change_alarm_aux_checked_dylibloader_orig_xcb_sync
#define xcb_sync_change_alarm_aux xcb_sync_change_alarm_aux_dylibloader_orig_xcb_sync
#define xcb_sync_change_alarm_value_list xcb_sync_change_alarm_value_list_dylibloader_orig_xcb_sync
#define xcb_sync_destroy_alarm_checked xcb_sync_destroy_alarm_checked_dylibloader_orig_xcb_sync
#define xcb_sync_destroy_alarm xcb_sync_destroy_alarm_dylibloader_orig_xcb_sync
#define xcb_sync_query_alarm xcb_sync_query_alarm_dylibloader_orig_xcb_sync
#define xcb_sync_query_alarm_unchecked xcb_sync_query_alarm_unchecked_dylibloader_orig_xcb_sync
#define xcb_sync_query_alarm_reply xcb_sync_query_alarm_reply_dylibloader_orig_xcb_sync
#define xcb_sync_set_priority_checked xcb_sync_set_priority_checked_dylibloader_orig_xcb_sync
#define xcb_sync_set_priority xcb_sync_set_priority_dylibloader_orig_xcb_sync
#define xcb_sync_get_priority xcb_sync_get_priority_dylibloader_orig_xcb_sync
#define xcb_sync_get_priority_unchecked xcb_sync_get_priority_unchecked_dylibloader_orig_xcb_sync
#define xcb_sync_get_priority_reply xcb_sync_get_priority_reply_dylibloader_orig_xcb_sync
#define xcb_sync_create_fence_checked xcb_sync_create_fence_checked_dylibloader_orig_xcb_sync
#define xcb_sync_create_fence xcb_sync_create_fence_dylibloader_orig_xcb_sync
#define xcb_sync_trigger_fence_checked xcb_sync_trigger_fence_checked_dylibloader_orig_xcb_sync
#define xcb_sync_trigger_fence xcb_sync_trigger_fence_dylibloader_orig_xcb_sync
#define xcb_sync_reset_fence_checked xcb_sync_reset_fence_checked_dylibloader_orig_xcb_sync
#define xcb_sync_reset_fence xcb_sync_reset_fence_dylibloader_orig_xcb_sync
#define xcb_sync_destroy_fence_checked xcb_sync_destroy_fence_checked_dylibloader_orig_xcb_sync
#define xcb_sync_destroy_fence xcb_sync_destroy_fence_dylibloader_orig_xcb_sync
#define xcb_sync_query_fence xcb_sync_query_fence_dylibloader_orig_xcb_sync
#define xcb_sync_query_fence_unchecked xcb_sync_query_fence_unchecked_dylibloader_orig_xcb_sync
#define xcb_sync_query_fence_reply xcb_sync_query_fence_reply_dylibloader_orig_xcb_sync
#define xcb_sync_await_fence_sizeof xcb_sync_await_fence_sizeof_dylibloader_orig_xcb_sync
#define xcb_sync_await_fence_checked xcb_sync_await_fence_checked_dylibloader_orig_xcb_sync
#define xcb_sync_await_fence xcb_sync_await_fence_dylibloader_orig_xcb_sync
#define xcb_sync_await_fence_fence_list xcb_sync_await_fence_fence_list_dylibloader_orig_xcb_sync
#define xcb_sync_await_fence_fence_list_length xcb_sync_await_fence_fence_list_length_dylibloader_orig_xcb_sync
#define xcb_sync_await_fence_fence_list_end xcb_sync_await_fence_fence_list_end_dylibloader_orig_xcb_sync
#include "xcb-so_wrap.h"
#include <xcb/sync.h>
#undef xcb_sync_alarm_next
#undef xcb_sync_alarm_end
#undef xcb_sync_counter_next
#undef xcb_sync_counter_end
#undef xcb_sync_fence_next
#undef xcb_sync_fence_end
#undef xcb_sync_int64_next
#undef xcb_sync_int64_end
#undef xcb_sync_systemcounter_sizeof
#undef xcb_sync_systemcounter_name
#undef xcb_sync_systemcounter_name_length
#undef xcb_sync_systemcounter_name_end
#undef xcb_sync_systemcounter_next
#undef xcb_sync_systemcounter_end
#undef xcb_sync_trigger_next
#undef xcb_sync_trigger_end
#undef xcb_sync_waitcondition_next
#undef xcb_sync_waitcondition_end
#undef xcb_sync_initialize
#undef xcb_sync_initialize_unchecked
#undef xcb_sync_initialize_reply
#undef xcb_sync_list_system_counters_sizeof
#undef xcb_sync_list_system_counters
#undef xcb_sync_list_system_counters_unchecked
#undef xcb_sync_list_system_counters_counters_length
#undef xcb_sync_list_system_counters_counters_iterator
#undef xcb_sync_list_system_counters_reply
#undef xcb_sync_create_counter_checked
#undef xcb_sync_create_counter
#undef xcb_sync_destroy_counter_checked
#undef xcb_sync_destroy_counter
#undef xcb_sync_query_counter
#undef xcb_sync_query_counter_unchecked
#undef xcb_sync_query_counter_reply
#undef xcb_sync_await_sizeof
#undef xcb_sync_await_checked
#undef xcb_sync_await
#undef xcb_sync_await_wait_list
#undef xcb_sync_await_wait_list_length
#undef xcb_sync_await_wait_list_iterator
#undef xcb_sync_change_counter_checked
#undef xcb_sync_change_counter
#undef xcb_sync_set_counter_checked
#undef xcb_sync_set_counter
#undef xcb_sync_create_alarm_value_list_serialize
#undef xcb_sync_create_alarm_value_list_unpack
#undef xcb_sync_create_alarm_value_list_sizeof
#undef xcb_sync_create_alarm_sizeof
#undef xcb_sync_create_alarm_checked
#undef xcb_sync_create_alarm
#undef xcb_sync_create_alarm_aux_checked
#undef xcb_sync_create_alarm_aux
#undef xcb_sync_create_alarm_value_list
#undef xcb_sync_change_alarm_value_list_serialize
#undef xcb_sync_change_alarm_value_list_unpack
#undef xcb_sync_change_alarm_value_list_sizeof
#undef xcb_sync_change_alarm_sizeof
#undef xcb_sync_change_alarm_checked
#undef xcb_sync_change_alarm
#undef xcb_sync_change_alarm_aux_checked
#undef xcb_sync_change_alarm_aux
#undef xcb_sync_change_alarm_value_list
#undef xcb_sync_destroy_alarm_checked
#undef xcb_sync_destroy_alarm
#undef xcb_sync_query_alarm
#undef xcb_sync_query_alarm_unchecked
#undef xcb_sync_query_alarm_reply
#undef xcb_sync_set_priority_checked
#undef xcb_sync_set_priority
#undef xcb_sync_get_priority
#undef xcb_sync_get_priority_unchecked
#undef xcb_sync_get_priority_reply
#undef xcb_sync_create_fence_checked
#undef xcb_sync_create_fence
#undef xcb_sync_trigger_fence_checked
#undef xcb_sync_trigger_fence
#undef xcb_sync_reset_fence_checked
#undef xcb_sync_reset_fence
#undef xcb_sync_destroy_fence_checked
#undef xcb_sync_destroy_fence
#undef xcb_sync_query_fence
#undef xcb_sync_query_fence_unchecked
#undef xcb_sync_query_fence_reply
#undef xcb_sync_await_fence_sizeof
#undef xcb_sync_await_fence_checked
#undef xcb_sync_await_fence
#undef xcb_sync_await_fence_fence_list
#undef xcb_sync_await_fence_fence_list_length
#undef xcb_sync_await_fence_fence_list_end
#include <dlfcn.h>
#include <stdio.h>
void (*xcb_sync_alarm_next_dylibloader_wrapper_xcb_sync)(xcb_sync_alarm_iterator_t *);
xcb_generic_iterator_t (*xcb_sync_alarm_end_dylibloader_wrapper_xcb_sync)(xcb_sync_alarm_iterator_t);
void (*xcb_sync_counter_next_dylibloader_wrapper_xcb_sync)(xcb_sync_counter_iterator_t *);
xcb_generic_iterator_t (*xcb_sync_counter_end_dylibloader_wrapper_xcb_sync)(xcb_sync_counter_iterator_t);
void (*xcb_sync_fence_next_dylibloader_wrapper_xcb_sync)(xcb_sync_fence_iterator_t *);
xcb_generic_iterator_t (*xcb_sync_fence_end_dylibloader_wrapper_xcb_sync)(xcb_sync_fence_iterator_t);
void (*xcb_sync_int64_next_dylibloader_wrapper_xcb_sync)(xcb_sync_int64_iterator_t *);
xcb_generic_iterator_t (*xcb_sync_int64_end_dylibloader_wrapper_xcb_sync)(xcb_sync_int64_iterator_t);
int (*xcb_sync_systemcounter_sizeof_dylibloader_wrapper_xcb_sync)(const void *);
char *(*xcb_sync_systemcounter_name_dylibloader_wrapper_xcb_sync)(const xcb_sync_systemcounter_t *);
int (*xcb_sync_systemcounter_name_length_dylibloader_wrapper_xcb_sync)(const xcb_sync_systemcounter_t *);
xcb_generic_iterator_t (*xcb_sync_systemcounter_name_end_dylibloader_wrapper_xcb_sync)(const xcb_sync_systemcounter_t *);
void (*xcb_sync_systemcounter_next_dylibloader_wrapper_xcb_sync)(xcb_sync_systemcounter_iterator_t *);
xcb_generic_iterator_t (*xcb_sync_systemcounter_end_dylibloader_wrapper_xcb_sync)(xcb_sync_systemcounter_iterator_t);
void (*xcb_sync_trigger_next_dylibloader_wrapper_xcb_sync)(xcb_sync_trigger_iterator_t *);
xcb_generic_iterator_t (*xcb_sync_trigger_end_dylibloader_wrapper_xcb_sync)(xcb_sync_trigger_iterator_t);
void (*xcb_sync_waitcondition_next_dylibloader_wrapper_xcb_sync)(xcb_sync_waitcondition_iterator_t *);
xcb_generic_iterator_t (*xcb_sync_waitcondition_end_dylibloader_wrapper_xcb_sync)(xcb_sync_waitcondition_iterator_t);
xcb_sync_initialize_cookie_t (*xcb_sync_initialize_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, uint8_t, uint8_t);
xcb_sync_initialize_cookie_t (*xcb_sync_initialize_unchecked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, uint8_t, uint8_t);
xcb_sync_initialize_reply_t *(*xcb_sync_initialize_reply_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_initialize_cookie_t, xcb_generic_error_t **);
int (*xcb_sync_list_system_counters_sizeof_dylibloader_wrapper_xcb_sync)(const void *);
xcb_sync_list_system_counters_cookie_t (*xcb_sync_list_system_counters_dylibloader_wrapper_xcb_sync)(xcb_connection_t *);
xcb_sync_list_system_counters_cookie_t (*xcb_sync_list_system_counters_unchecked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *);
int (*xcb_sync_list_system_counters_counters_length_dylibloader_wrapper_xcb_sync)(const xcb_sync_list_system_counters_reply_t *);
xcb_sync_systemcounter_iterator_t (*xcb_sync_list_system_counters_counters_iterator_dylibloader_wrapper_xcb_sync)(const xcb_sync_list_system_counters_reply_t *);
xcb_sync_list_system_counters_reply_t *(*xcb_sync_list_system_counters_reply_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_list_system_counters_cookie_t, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_sync_create_counter_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_counter_t, xcb_sync_int64_t);
xcb_void_cookie_t (*xcb_sync_create_counter_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_counter_t, xcb_sync_int64_t);
xcb_void_cookie_t (*xcb_sync_destroy_counter_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_counter_t);
xcb_void_cookie_t (*xcb_sync_destroy_counter_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_counter_t);
xcb_sync_query_counter_cookie_t (*xcb_sync_query_counter_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_counter_t);
xcb_sync_query_counter_cookie_t (*xcb_sync_query_counter_unchecked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_counter_t);
xcb_sync_query_counter_reply_t *(*xcb_sync_query_counter_reply_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_query_counter_cookie_t, xcb_generic_error_t **);
int (*xcb_sync_await_sizeof_dylibloader_wrapper_xcb_sync)(const void *, uint32_t);
xcb_void_cookie_t (*xcb_sync_await_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, uint32_t, const xcb_sync_waitcondition_t *);
xcb_void_cookie_t (*xcb_sync_await_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, uint32_t, const xcb_sync_waitcondition_t *);
xcb_sync_waitcondition_t *(*xcb_sync_await_wait_list_dylibloader_wrapper_xcb_sync)(const xcb_sync_await_request_t *);
int (*xcb_sync_await_wait_list_length_dylibloader_wrapper_xcb_sync)(const xcb_sync_await_request_t *);
xcb_sync_waitcondition_iterator_t (*xcb_sync_await_wait_list_iterator_dylibloader_wrapper_xcb_sync)(const xcb_sync_await_request_t *);
xcb_void_cookie_t (*xcb_sync_change_counter_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_counter_t, xcb_sync_int64_t);
xcb_void_cookie_t (*xcb_sync_change_counter_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_counter_t, xcb_sync_int64_t);
xcb_void_cookie_t (*xcb_sync_set_counter_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_counter_t, xcb_sync_int64_t);
xcb_void_cookie_t (*xcb_sync_set_counter_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_counter_t, xcb_sync_int64_t);
int (*xcb_sync_create_alarm_value_list_serialize_dylibloader_wrapper_xcb_sync)(void **, uint32_t, const xcb_sync_create_alarm_value_list_t *);
int (*xcb_sync_create_alarm_value_list_unpack_dylibloader_wrapper_xcb_sync)(const void *, uint32_t, xcb_sync_create_alarm_value_list_t *);
int (*xcb_sync_create_alarm_value_list_sizeof_dylibloader_wrapper_xcb_sync)(const void *, uint32_t);
int (*xcb_sync_create_alarm_sizeof_dylibloader_wrapper_xcb_sync)(const void *);
xcb_void_cookie_t (*xcb_sync_create_alarm_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t, uint32_t, const void *);
xcb_void_cookie_t (*xcb_sync_create_alarm_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t, uint32_t, const void *);
xcb_void_cookie_t (*xcb_sync_create_alarm_aux_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t, uint32_t, const xcb_sync_create_alarm_value_list_t *);
xcb_void_cookie_t (*xcb_sync_create_alarm_aux_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t, uint32_t, const xcb_sync_create_alarm_value_list_t *);
void *(*xcb_sync_create_alarm_value_list_dylibloader_wrapper_xcb_sync)(const xcb_sync_create_alarm_request_t *);
int (*xcb_sync_change_alarm_value_list_serialize_dylibloader_wrapper_xcb_sync)(void **, uint32_t, const xcb_sync_change_alarm_value_list_t *);
int (*xcb_sync_change_alarm_value_list_unpack_dylibloader_wrapper_xcb_sync)(const void *, uint32_t, xcb_sync_change_alarm_value_list_t *);
int (*xcb_sync_change_alarm_value_list_sizeof_dylibloader_wrapper_xcb_sync)(const void *, uint32_t);
int (*xcb_sync_change_alarm_sizeof_dylibloader_wrapper_xcb_sync)(const void *);
xcb_void_cookie_t (*xcb_sync_change_alarm_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t, uint32_t, const void *);
xcb_void_cookie_t (*xcb_sync_change_alarm_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t, uint32_t, const void *);
xcb_void_cookie_t (*xcb_sync_change_alarm_aux_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t, uint32_t, const xcb_sync_change_alarm_value_list_t *);
xcb_void_cookie_t (*xcb_sync_change_alarm_aux_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t, uint32_t, const xcb_sync_change_alarm_value_list_t *);
void *(*xcb_sync_change_alarm_value_list_dylibloader_wrapper_xcb_sync)(const xcb_sync_change_alarm_request_t *);
xcb_void_cookie_t (*xcb_sync_destroy_alarm_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t);
xcb_void_cookie_t (*xcb_sync_destroy_alarm_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t);
xcb_sync_query_alarm_cookie_t (*xcb_sync_query_alarm_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t);
xcb_sync_query_alarm_cookie_t (*xcb_sync_query_alarm_unchecked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_alarm_t);
xcb_sync_query_alarm_reply_t *(*xcb_sync_query_alarm_reply_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_query_alarm_cookie_t, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_sync_set_priority_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, uint32_t, int32_t);
xcb_void_cookie_t (*xcb_sync_set_priority_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, uint32_t, int32_t);
xcb_sync_get_priority_cookie_t (*xcb_sync_get_priority_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, uint32_t);
xcb_sync_get_priority_cookie_t (*xcb_sync_get_priority_unchecked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, uint32_t);
xcb_sync_get_priority_reply_t *(*xcb_sync_get_priority_reply_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_get_priority_cookie_t, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_sync_create_fence_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_drawable_t, xcb_sync_fence_t, uint8_t);
xcb_void_cookie_t (*xcb_sync_create_fence_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_drawable_t, xcb_sync_fence_t, uint8_t);
xcb_void_cookie_t (*xcb_sync_trigger_fence_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_fence_t);
xcb_void_cookie_t (*xcb_sync_trigger_fence_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_fence_t);
xcb_void_cookie_t (*xcb_sync_reset_fence_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_fence_t);
xcb_void_cookie_t (*xcb_sync_reset_fence_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_fence_t);
xcb_void_cookie_t (*xcb_sync_destroy_fence_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_fence_t);
xcb_void_cookie_t (*xcb_sync_destroy_fence_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_fence_t);
xcb_sync_query_fence_cookie_t (*xcb_sync_query_fence_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_fence_t);
xcb_sync_query_fence_cookie_t (*xcb_sync_query_fence_unchecked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_fence_t);
xcb_sync_query_fence_reply_t *(*xcb_sync_query_fence_reply_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, xcb_sync_query_fence_cookie_t, xcb_generic_error_t **);
int (*xcb_sync_await_fence_sizeof_dylibloader_wrapper_xcb_sync)(const void *, uint32_t);
xcb_void_cookie_t (*xcb_sync_await_fence_checked_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, uint32_t, const xcb_sync_fence_t *);
xcb_void_cookie_t (*xcb_sync_await_fence_dylibloader_wrapper_xcb_sync)(xcb_connection_t *, uint32_t, const xcb_sync_fence_t *);
xcb_sync_fence_t *(*xcb_sync_await_fence_fence_list_dylibloader_wrapper_xcb_sync)(const xcb_sync_await_fence_request_t *);
int (*xcb_sync_await_fence_fence_list_length_dylibloader_wrapper_xcb_sync)(const xcb_sync_await_fence_request_t *);
xcb_generic_iterator_t (*xcb_sync_await_fence_fence_list_end_dylibloader_wrapper_xcb_sync)(const xcb_sync_await_fence_request_t *);
int initialize_xcb_sync(int verbose) {
  void *handle;
  char *error;
  handle = dlopen("libxcb-sync.so.1", RTLD_LAZY);
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
// xcb_sync_alarm_next
  *(void **) (&xcb_sync_alarm_next_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_alarm_next");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_alarm_end
  *(void **) (&xcb_sync_alarm_end_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_alarm_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_counter_next
  *(void **) (&xcb_sync_counter_next_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_counter_next");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_counter_end
  *(void **) (&xcb_sync_counter_end_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_counter_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_fence_next
  *(void **) (&xcb_sync_fence_next_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_fence_next");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_fence_end
  *(void **) (&xcb_sync_fence_end_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_fence_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_int64_next
  *(void **) (&xcb_sync_int64_next_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_int64_next");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_int64_end
  *(void **) (&xcb_sync_int64_end_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_int64_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_systemcounter_sizeof
  *(void **) (&xcb_sync_systemcounter_sizeof_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_systemcounter_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_systemcounter_name
  *(void **) (&xcb_sync_systemcounter_name_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_systemcounter_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_systemcounter_name_length
  *(void **) (&xcb_sync_systemcounter_name_length_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_systemcounter_name_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_systemcounter_name_end
  *(void **) (&xcb_sync_systemcounter_name_end_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_systemcounter_name_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_systemcounter_next
  *(void **) (&xcb_sync_systemcounter_next_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_systemcounter_next");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_systemcounter_end
  *(void **) (&xcb_sync_systemcounter_end_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_systemcounter_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_trigger_next
  *(void **) (&xcb_sync_trigger_next_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_trigger_next");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_trigger_end
  *(void **) (&xcb_sync_trigger_end_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_trigger_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_waitcondition_next
  *(void **) (&xcb_sync_waitcondition_next_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_waitcondition_next");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_waitcondition_end
  *(void **) (&xcb_sync_waitcondition_end_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_waitcondition_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_initialize
  *(void **) (&xcb_sync_initialize_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_initialize");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_initialize_unchecked
  *(void **) (&xcb_sync_initialize_unchecked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_initialize_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_initialize_reply
  *(void **) (&xcb_sync_initialize_reply_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_initialize_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_list_system_counters_sizeof
  *(void **) (&xcb_sync_list_system_counters_sizeof_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_list_system_counters_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_list_system_counters
  *(void **) (&xcb_sync_list_system_counters_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_list_system_counters");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_list_system_counters_unchecked
  *(void **) (&xcb_sync_list_system_counters_unchecked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_list_system_counters_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_list_system_counters_counters_length
  *(void **) (&xcb_sync_list_system_counters_counters_length_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_list_system_counters_counters_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_list_system_counters_counters_iterator
  *(void **) (&xcb_sync_list_system_counters_counters_iterator_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_list_system_counters_counters_iterator");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_list_system_counters_reply
  *(void **) (&xcb_sync_list_system_counters_reply_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_list_system_counters_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_counter_checked
  *(void **) (&xcb_sync_create_counter_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_counter_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_counter
  *(void **) (&xcb_sync_create_counter_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_counter");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_destroy_counter_checked
  *(void **) (&xcb_sync_destroy_counter_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_destroy_counter_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_destroy_counter
  *(void **) (&xcb_sync_destroy_counter_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_destroy_counter");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_query_counter
  *(void **) (&xcb_sync_query_counter_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_query_counter");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_query_counter_unchecked
  *(void **) (&xcb_sync_query_counter_unchecked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_query_counter_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_query_counter_reply
  *(void **) (&xcb_sync_query_counter_reply_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_query_counter_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_sizeof
  *(void **) (&xcb_sync_await_sizeof_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_checked
  *(void **) (&xcb_sync_await_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await
  *(void **) (&xcb_sync_await_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_wait_list
  *(void **) (&xcb_sync_await_wait_list_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_wait_list");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_wait_list_length
  *(void **) (&xcb_sync_await_wait_list_length_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_wait_list_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_wait_list_iterator
  *(void **) (&xcb_sync_await_wait_list_iterator_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_wait_list_iterator");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_counter_checked
  *(void **) (&xcb_sync_change_counter_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_counter_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_counter
  *(void **) (&xcb_sync_change_counter_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_counter");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_set_counter_checked
  *(void **) (&xcb_sync_set_counter_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_set_counter_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_set_counter
  *(void **) (&xcb_sync_set_counter_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_set_counter");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_alarm_value_list_serialize
  *(void **) (&xcb_sync_create_alarm_value_list_serialize_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_alarm_value_list_serialize");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_alarm_value_list_unpack
  *(void **) (&xcb_sync_create_alarm_value_list_unpack_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_alarm_value_list_unpack");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_alarm_value_list_sizeof
  *(void **) (&xcb_sync_create_alarm_value_list_sizeof_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_alarm_value_list_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_alarm_sizeof
  *(void **) (&xcb_sync_create_alarm_sizeof_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_alarm_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_alarm_checked
  *(void **) (&xcb_sync_create_alarm_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_alarm_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_alarm
  *(void **) (&xcb_sync_create_alarm_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_alarm");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_alarm_aux_checked
  *(void **) (&xcb_sync_create_alarm_aux_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_alarm_aux_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_alarm_aux
  *(void **) (&xcb_sync_create_alarm_aux_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_alarm_aux");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_alarm_value_list
  *(void **) (&xcb_sync_create_alarm_value_list_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_alarm_value_list");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_alarm_value_list_serialize
  *(void **) (&xcb_sync_change_alarm_value_list_serialize_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_alarm_value_list_serialize");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_alarm_value_list_unpack
  *(void **) (&xcb_sync_change_alarm_value_list_unpack_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_alarm_value_list_unpack");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_alarm_value_list_sizeof
  *(void **) (&xcb_sync_change_alarm_value_list_sizeof_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_alarm_value_list_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_alarm_sizeof
  *(void **) (&xcb_sync_change_alarm_sizeof_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_alarm_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_alarm_checked
  *(void **) (&xcb_sync_change_alarm_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_alarm_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_alarm
  *(void **) (&xcb_sync_change_alarm_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_alarm");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_alarm_aux_checked
  *(void **) (&xcb_sync_change_alarm_aux_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_alarm_aux_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_alarm_aux
  *(void **) (&xcb_sync_change_alarm_aux_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_alarm_aux");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_change_alarm_value_list
  *(void **) (&xcb_sync_change_alarm_value_list_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_change_alarm_value_list");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_destroy_alarm_checked
  *(void **) (&xcb_sync_destroy_alarm_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_destroy_alarm_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_destroy_alarm
  *(void **) (&xcb_sync_destroy_alarm_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_destroy_alarm");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_query_alarm
  *(void **) (&xcb_sync_query_alarm_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_query_alarm");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_query_alarm_unchecked
  *(void **) (&xcb_sync_query_alarm_unchecked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_query_alarm_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_query_alarm_reply
  *(void **) (&xcb_sync_query_alarm_reply_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_query_alarm_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_set_priority_checked
  *(void **) (&xcb_sync_set_priority_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_set_priority_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_set_priority
  *(void **) (&xcb_sync_set_priority_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_set_priority");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_get_priority
  *(void **) (&xcb_sync_get_priority_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_get_priority");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_get_priority_unchecked
  *(void **) (&xcb_sync_get_priority_unchecked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_get_priority_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_get_priority_reply
  *(void **) (&xcb_sync_get_priority_reply_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_get_priority_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_fence_checked
  *(void **) (&xcb_sync_create_fence_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_fence_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_create_fence
  *(void **) (&xcb_sync_create_fence_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_create_fence");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_trigger_fence_checked
  *(void **) (&xcb_sync_trigger_fence_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_trigger_fence_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_trigger_fence
  *(void **) (&xcb_sync_trigger_fence_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_trigger_fence");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_reset_fence_checked
  *(void **) (&xcb_sync_reset_fence_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_reset_fence_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_reset_fence
  *(void **) (&xcb_sync_reset_fence_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_reset_fence");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_destroy_fence_checked
  *(void **) (&xcb_sync_destroy_fence_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_destroy_fence_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_destroy_fence
  *(void **) (&xcb_sync_destroy_fence_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_destroy_fence");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_query_fence
  *(void **) (&xcb_sync_query_fence_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_query_fence");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_query_fence_unchecked
  *(void **) (&xcb_sync_query_fence_unchecked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_query_fence_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_query_fence_reply
  *(void **) (&xcb_sync_query_fence_reply_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_query_fence_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_fence_sizeof
  *(void **) (&xcb_sync_await_fence_sizeof_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_fence_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_fence_checked
  *(void **) (&xcb_sync_await_fence_checked_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_fence_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_fence
  *(void **) (&xcb_sync_await_fence_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_fence");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_fence_fence_list
  *(void **) (&xcb_sync_await_fence_fence_list_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_fence_fence_list");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_fence_fence_list_length
  *(void **) (&xcb_sync_await_fence_fence_list_length_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_fence_fence_list_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
// xcb_sync_await_fence_fence_list_end
  *(void **) (&xcb_sync_await_fence_fence_list_end_dylibloader_wrapper_xcb_sync) = dlsym(handle, "xcb_sync_await_fence_fence_list_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
return 0;
}
