/* This file is generated. Do not edit!
   see https://github.com/hpvb/dynload-wrapper (patched) for details
   generated by scripts/generate-wrapper.py 0.5
   flags: scripts/generate-wrapper.py --include include/xcb/xcb_renderutil.h --sys-include xcb-so_wrap.h --sys-include xcb_render-so_wrap.h --sys-include <xcb/xcb_renderutil.h> --soname libxcb-render-util.so.0 --init-name xcb_render_util --output-header include_gen/xcb_render_util-so_wrap.h --output-implementation src_gen/xcb_render_util-so_wrap.c --ignore-other --include-dir include
*/
#include <stdint.h>

#define xcb_render_util_find_visual_format xcb_render_util_find_visual_format_dylibloader_orig_xcb_render_util
#define xcb_render_util_find_format xcb_render_util_find_format_dylibloader_orig_xcb_render_util
#define xcb_render_util_find_standard_format xcb_render_util_find_standard_format_dylibloader_orig_xcb_render_util
#define xcb_render_util_query_version xcb_render_util_query_version_dylibloader_orig_xcb_render_util
#define xcb_render_util_query_formats xcb_render_util_query_formats_dylibloader_orig_xcb_render_util
#define xcb_render_util_disconnect xcb_render_util_disconnect_dylibloader_orig_xcb_render_util
#define xcb_render_util_composite_text_stream xcb_render_util_composite_text_stream_dylibloader_orig_xcb_render_util
#define xcb_render_util_glyphs_8 xcb_render_util_glyphs_8_dylibloader_orig_xcb_render_util
#define xcb_render_util_glyphs_16 xcb_render_util_glyphs_16_dylibloader_orig_xcb_render_util
#define xcb_render_util_glyphs_32 xcb_render_util_glyphs_32_dylibloader_orig_xcb_render_util
#define xcb_render_util_change_glyphset xcb_render_util_change_glyphset_dylibloader_orig_xcb_render_util
#define xcb_render_util_composite_text xcb_render_util_composite_text_dylibloader_orig_xcb_render_util
#define xcb_render_util_composite_text_checked xcb_render_util_composite_text_checked_dylibloader_orig_xcb_render_util
#define xcb_render_util_composite_text_free xcb_render_util_composite_text_free_dylibloader_orig_xcb_render_util
#include "xcb-so_wrap.h"
#include "xcb_render-so_wrap.h"
#include <xcb/xcb_renderutil.h>
#undef xcb_render_util_find_visual_format
#undef xcb_render_util_find_format
#undef xcb_render_util_find_standard_format
#undef xcb_render_util_query_version
#undef xcb_render_util_query_formats
#undef xcb_render_util_disconnect
#undef xcb_render_util_composite_text_stream
#undef xcb_render_util_glyphs_8
#undef xcb_render_util_glyphs_16
#undef xcb_render_util_glyphs_32
#undef xcb_render_util_change_glyphset
#undef xcb_render_util_composite_text
#undef xcb_render_util_composite_text_checked
#undef xcb_render_util_composite_text_free
#include <dlfcn.h>
#include <stdio.h>
xcb_render_pictvisual_t *(*xcb_render_util_find_visual_format_dylibloader_wrapper_xcb_render_util)(const xcb_render_query_pict_formats_reply_t *, const xcb_visualid_t);
xcb_render_pictforminfo_t *(*xcb_render_util_find_format_dylibloader_wrapper_xcb_render_util)(const xcb_render_query_pict_formats_reply_t *, unsigned long, const xcb_render_pictforminfo_t *, int);
xcb_render_pictforminfo_t *(*xcb_render_util_find_standard_format_dylibloader_wrapper_xcb_render_util)(const xcb_render_query_pict_formats_reply_t *, xcb_pict_standard_t);
const xcb_render_query_version_reply_t *(*xcb_render_util_query_version_dylibloader_wrapper_xcb_render_util)(xcb_connection_t *);
const xcb_render_query_pict_formats_reply_t *(*xcb_render_util_query_formats_dylibloader_wrapper_xcb_render_util)(xcb_connection_t *);
int (*xcb_render_util_disconnect_dylibloader_wrapper_xcb_render_util)(xcb_connection_t *);
xcb_render_util_composite_text_stream_t *(*xcb_render_util_composite_text_stream_dylibloader_wrapper_xcb_render_util)(xcb_render_glyphset_t, uint32_t, uint32_t);
void (*xcb_render_util_glyphs_8_dylibloader_wrapper_xcb_render_util)(xcb_render_util_composite_text_stream_t *, int16_t, int16_t, uint32_t, const uint8_t *);
void (*xcb_render_util_glyphs_16_dylibloader_wrapper_xcb_render_util)(xcb_render_util_composite_text_stream_t *, int16_t, int16_t, uint32_t, const uint16_t *);
void (*xcb_render_util_glyphs_32_dylibloader_wrapper_xcb_render_util)(xcb_render_util_composite_text_stream_t *, int16_t, int16_t, uint32_t, const uint32_t *);
void (*xcb_render_util_change_glyphset_dylibloader_wrapper_xcb_render_util)(xcb_render_util_composite_text_stream_t *, xcb_render_glyphset_t);
xcb_void_cookie_t (*xcb_render_util_composite_text_dylibloader_wrapper_xcb_render_util)(xcb_connection_t *, uint8_t, xcb_render_picture_t, xcb_render_picture_t, xcb_render_pictformat_t, int16_t, int16_t, xcb_render_util_composite_text_stream_t *);
xcb_void_cookie_t (*xcb_render_util_composite_text_checked_dylibloader_wrapper_xcb_render_util)(xcb_connection_t *, uint8_t, xcb_render_picture_t, xcb_render_picture_t, xcb_render_pictformat_t, int16_t, int16_t, xcb_render_util_composite_text_stream_t *);
void (*xcb_render_util_composite_text_free_dylibloader_wrapper_xcb_render_util)(xcb_render_util_composite_text_stream_t *);
int initialize_xcb_render_util(int verbose) {
  void *handle;
  char *error;
  handle = dlopen("libxcb-render-util.so.0", RTLD_LAZY);
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
/* xcb_render_util_find_visual_format */
  *(void **) (&xcb_render_util_find_visual_format_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_find_visual_format");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_find_format */
  *(void **) (&xcb_render_util_find_format_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_find_format");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_find_standard_format */
  *(void **) (&xcb_render_util_find_standard_format_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_find_standard_format");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_query_version */
  *(void **) (&xcb_render_util_query_version_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_query_version");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_query_formats */
  *(void **) (&xcb_render_util_query_formats_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_query_formats");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_disconnect */
  *(void **) (&xcb_render_util_disconnect_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_disconnect");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_composite_text_stream */
  *(void **) (&xcb_render_util_composite_text_stream_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_composite_text_stream");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_glyphs_8 */
  *(void **) (&xcb_render_util_glyphs_8_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_glyphs_8");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_glyphs_16 */
  *(void **) (&xcb_render_util_glyphs_16_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_glyphs_16");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_glyphs_32 */
  *(void **) (&xcb_render_util_glyphs_32_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_glyphs_32");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_change_glyphset */
  *(void **) (&xcb_render_util_change_glyphset_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_change_glyphset");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_composite_text */
  *(void **) (&xcb_render_util_composite_text_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_composite_text");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_composite_text_checked */
  *(void **) (&xcb_render_util_composite_text_checked_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_composite_text_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_render_util_composite_text_free */
  *(void **) (&xcb_render_util_composite_text_free_dylibloader_wrapper_xcb_render_util) = dlsym(handle, "xcb_render_util_composite_text_free");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
return 0;
}
