/* This file is generated. Do not edit!
   see https://github.com/hpvb/dynload-wrapper (patched) for details
   generated by scripts/generate-wrapper.py 0.5
   flags: scripts/generate-wrapper.py --include include/xcb/xfixes.h --sys-include xcb-so_wrap.h --sys-include xcb_render-so_wrap.h --sys-include xcb_shape-so_wrap.h --sys-include <xcb/xfixes.h> --soname libxcb-xfixes.so.0 --init-name xcb_xfixes --output-header include_gen/xcb_xfixes-so_wrap.h --output-implementation src_gen/xcb_xfixes-so_wrap.c --ignore-other --include-dir include
*/
#include <stdint.h>

#define xcb_xfixes_query_version xcb_xfixes_query_version_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_query_version_unchecked xcb_xfixes_query_version_unchecked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_query_version_reply xcb_xfixes_query_version_reply_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_change_save_set_checked xcb_xfixes_change_save_set_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_change_save_set xcb_xfixes_change_save_set_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_select_selection_input_checked xcb_xfixes_select_selection_input_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_select_selection_input xcb_xfixes_select_selection_input_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_select_cursor_input_checked xcb_xfixes_select_cursor_input_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_select_cursor_input xcb_xfixes_select_cursor_input_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_sizeof xcb_xfixes_get_cursor_image_sizeof_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image xcb_xfixes_get_cursor_image_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_unchecked xcb_xfixes_get_cursor_image_unchecked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_cursor_image xcb_xfixes_get_cursor_image_cursor_image_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_cursor_image_length xcb_xfixes_get_cursor_image_cursor_image_length_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_cursor_image_end xcb_xfixes_get_cursor_image_cursor_image_end_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_reply xcb_xfixes_get_cursor_image_reply_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_region_next xcb_xfixes_region_next_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_region_end xcb_xfixes_region_end_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_sizeof xcb_xfixes_create_region_sizeof_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_checked xcb_xfixes_create_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region xcb_xfixes_create_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_rectangles xcb_xfixes_create_region_rectangles_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_rectangles_length xcb_xfixes_create_region_rectangles_length_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_rectangles_iterator xcb_xfixes_create_region_rectangles_iterator_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_from_bitmap_checked xcb_xfixes_create_region_from_bitmap_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_from_bitmap xcb_xfixes_create_region_from_bitmap_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_from_window_checked xcb_xfixes_create_region_from_window_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_from_window xcb_xfixes_create_region_from_window_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_from_gc_checked xcb_xfixes_create_region_from_gc_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_from_gc xcb_xfixes_create_region_from_gc_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_from_picture_checked xcb_xfixes_create_region_from_picture_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_region_from_picture xcb_xfixes_create_region_from_picture_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_destroy_region_checked xcb_xfixes_destroy_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_destroy_region xcb_xfixes_destroy_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_region_sizeof xcb_xfixes_set_region_sizeof_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_region_checked xcb_xfixes_set_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_region xcb_xfixes_set_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_region_rectangles xcb_xfixes_set_region_rectangles_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_region_rectangles_length xcb_xfixes_set_region_rectangles_length_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_region_rectangles_iterator xcb_xfixes_set_region_rectangles_iterator_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_copy_region_checked xcb_xfixes_copy_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_copy_region xcb_xfixes_copy_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_union_region_checked xcb_xfixes_union_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_union_region xcb_xfixes_union_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_intersect_region_checked xcb_xfixes_intersect_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_intersect_region xcb_xfixes_intersect_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_subtract_region_checked xcb_xfixes_subtract_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_subtract_region xcb_xfixes_subtract_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_invert_region_checked xcb_xfixes_invert_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_invert_region xcb_xfixes_invert_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_translate_region_checked xcb_xfixes_translate_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_translate_region xcb_xfixes_translate_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_region_extents_checked xcb_xfixes_region_extents_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_region_extents xcb_xfixes_region_extents_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_fetch_region_sizeof xcb_xfixes_fetch_region_sizeof_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_fetch_region xcb_xfixes_fetch_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_fetch_region_unchecked xcb_xfixes_fetch_region_unchecked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_fetch_region_rectangles xcb_xfixes_fetch_region_rectangles_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_fetch_region_rectangles_length xcb_xfixes_fetch_region_rectangles_length_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_fetch_region_rectangles_iterator xcb_xfixes_fetch_region_rectangles_iterator_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_fetch_region_reply xcb_xfixes_fetch_region_reply_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_gc_clip_region_checked xcb_xfixes_set_gc_clip_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_gc_clip_region xcb_xfixes_set_gc_clip_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_window_shape_region_checked xcb_xfixes_set_window_shape_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_window_shape_region xcb_xfixes_set_window_shape_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_picture_clip_region_checked xcb_xfixes_set_picture_clip_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_picture_clip_region xcb_xfixes_set_picture_clip_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_cursor_name_sizeof xcb_xfixes_set_cursor_name_sizeof_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_cursor_name_checked xcb_xfixes_set_cursor_name_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_cursor_name xcb_xfixes_set_cursor_name_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_cursor_name_name xcb_xfixes_set_cursor_name_name_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_cursor_name_name_length xcb_xfixes_set_cursor_name_name_length_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_cursor_name_name_end xcb_xfixes_set_cursor_name_name_end_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_name_sizeof xcb_xfixes_get_cursor_name_sizeof_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_name xcb_xfixes_get_cursor_name_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_name_unchecked xcb_xfixes_get_cursor_name_unchecked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_name_name xcb_xfixes_get_cursor_name_name_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_name_name_length xcb_xfixes_get_cursor_name_name_length_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_name_name_end xcb_xfixes_get_cursor_name_name_end_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_name_reply xcb_xfixes_get_cursor_name_reply_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_and_name_sizeof xcb_xfixes_get_cursor_image_and_name_sizeof_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_and_name xcb_xfixes_get_cursor_image_and_name_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_and_name_unchecked xcb_xfixes_get_cursor_image_and_name_unchecked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_and_name_cursor_image xcb_xfixes_get_cursor_image_and_name_cursor_image_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_and_name_cursor_image_length xcb_xfixes_get_cursor_image_and_name_cursor_image_length_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_and_name_cursor_image_end xcb_xfixes_get_cursor_image_and_name_cursor_image_end_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_and_name_name xcb_xfixes_get_cursor_image_and_name_name_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_and_name_name_length xcb_xfixes_get_cursor_image_and_name_name_length_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_and_name_name_end xcb_xfixes_get_cursor_image_and_name_name_end_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_cursor_image_and_name_reply xcb_xfixes_get_cursor_image_and_name_reply_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_change_cursor_checked xcb_xfixes_change_cursor_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_change_cursor xcb_xfixes_change_cursor_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_change_cursor_by_name_sizeof xcb_xfixes_change_cursor_by_name_sizeof_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_change_cursor_by_name_checked xcb_xfixes_change_cursor_by_name_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_change_cursor_by_name xcb_xfixes_change_cursor_by_name_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_change_cursor_by_name_name xcb_xfixes_change_cursor_by_name_name_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_change_cursor_by_name_name_length xcb_xfixes_change_cursor_by_name_name_length_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_change_cursor_by_name_name_end xcb_xfixes_change_cursor_by_name_name_end_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_expand_region_checked xcb_xfixes_expand_region_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_expand_region xcb_xfixes_expand_region_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_hide_cursor_checked xcb_xfixes_hide_cursor_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_hide_cursor xcb_xfixes_hide_cursor_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_show_cursor_checked xcb_xfixes_show_cursor_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_show_cursor xcb_xfixes_show_cursor_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_barrier_next xcb_xfixes_barrier_next_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_barrier_end xcb_xfixes_barrier_end_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_pointer_barrier_sizeof xcb_xfixes_create_pointer_barrier_sizeof_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_pointer_barrier_checked xcb_xfixes_create_pointer_barrier_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_pointer_barrier xcb_xfixes_create_pointer_barrier_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_pointer_barrier_devices xcb_xfixes_create_pointer_barrier_devices_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_pointer_barrier_devices_length xcb_xfixes_create_pointer_barrier_devices_length_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_create_pointer_barrier_devices_end xcb_xfixes_create_pointer_barrier_devices_end_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_delete_pointer_barrier_checked xcb_xfixes_delete_pointer_barrier_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_delete_pointer_barrier xcb_xfixes_delete_pointer_barrier_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_client_disconnect_mode_checked xcb_xfixes_set_client_disconnect_mode_checked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_set_client_disconnect_mode xcb_xfixes_set_client_disconnect_mode_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_client_disconnect_mode xcb_xfixes_get_client_disconnect_mode_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_client_disconnect_mode_unchecked xcb_xfixes_get_client_disconnect_mode_unchecked_dylibloader_orig_xcb_xfixes
#define xcb_xfixes_get_client_disconnect_mode_reply xcb_xfixes_get_client_disconnect_mode_reply_dylibloader_orig_xcb_xfixes
#include "xcb-so_wrap.h"
#include "xcb_render-so_wrap.h"
#include "xcb_shape-so_wrap.h"
#include <xcb/xfixes.h>
#undef xcb_xfixes_query_version
#undef xcb_xfixes_query_version_unchecked
#undef xcb_xfixes_query_version_reply
#undef xcb_xfixes_change_save_set_checked
#undef xcb_xfixes_change_save_set
#undef xcb_xfixes_select_selection_input_checked
#undef xcb_xfixes_select_selection_input
#undef xcb_xfixes_select_cursor_input_checked
#undef xcb_xfixes_select_cursor_input
#undef xcb_xfixes_get_cursor_image_sizeof
#undef xcb_xfixes_get_cursor_image
#undef xcb_xfixes_get_cursor_image_unchecked
#undef xcb_xfixes_get_cursor_image_cursor_image
#undef xcb_xfixes_get_cursor_image_cursor_image_length
#undef xcb_xfixes_get_cursor_image_cursor_image_end
#undef xcb_xfixes_get_cursor_image_reply
#undef xcb_xfixes_region_next
#undef xcb_xfixes_region_end
#undef xcb_xfixes_create_region_sizeof
#undef xcb_xfixes_create_region_checked
#undef xcb_xfixes_create_region
#undef xcb_xfixes_create_region_rectangles
#undef xcb_xfixes_create_region_rectangles_length
#undef xcb_xfixes_create_region_rectangles_iterator
#undef xcb_xfixes_create_region_from_bitmap_checked
#undef xcb_xfixes_create_region_from_bitmap
#undef xcb_xfixes_create_region_from_window_checked
#undef xcb_xfixes_create_region_from_window
#undef xcb_xfixes_create_region_from_gc_checked
#undef xcb_xfixes_create_region_from_gc
#undef xcb_xfixes_create_region_from_picture_checked
#undef xcb_xfixes_create_region_from_picture
#undef xcb_xfixes_destroy_region_checked
#undef xcb_xfixes_destroy_region
#undef xcb_xfixes_set_region_sizeof
#undef xcb_xfixes_set_region_checked
#undef xcb_xfixes_set_region
#undef xcb_xfixes_set_region_rectangles
#undef xcb_xfixes_set_region_rectangles_length
#undef xcb_xfixes_set_region_rectangles_iterator
#undef xcb_xfixes_copy_region_checked
#undef xcb_xfixes_copy_region
#undef xcb_xfixes_union_region_checked
#undef xcb_xfixes_union_region
#undef xcb_xfixes_intersect_region_checked
#undef xcb_xfixes_intersect_region
#undef xcb_xfixes_subtract_region_checked
#undef xcb_xfixes_subtract_region
#undef xcb_xfixes_invert_region_checked
#undef xcb_xfixes_invert_region
#undef xcb_xfixes_translate_region_checked
#undef xcb_xfixes_translate_region
#undef xcb_xfixes_region_extents_checked
#undef xcb_xfixes_region_extents
#undef xcb_xfixes_fetch_region_sizeof
#undef xcb_xfixes_fetch_region
#undef xcb_xfixes_fetch_region_unchecked
#undef xcb_xfixes_fetch_region_rectangles
#undef xcb_xfixes_fetch_region_rectangles_length
#undef xcb_xfixes_fetch_region_rectangles_iterator
#undef xcb_xfixes_fetch_region_reply
#undef xcb_xfixes_set_gc_clip_region_checked
#undef xcb_xfixes_set_gc_clip_region
#undef xcb_xfixes_set_window_shape_region_checked
#undef xcb_xfixes_set_window_shape_region
#undef xcb_xfixes_set_picture_clip_region_checked
#undef xcb_xfixes_set_picture_clip_region
#undef xcb_xfixes_set_cursor_name_sizeof
#undef xcb_xfixes_set_cursor_name_checked
#undef xcb_xfixes_set_cursor_name
#undef xcb_xfixes_set_cursor_name_name
#undef xcb_xfixes_set_cursor_name_name_length
#undef xcb_xfixes_set_cursor_name_name_end
#undef xcb_xfixes_get_cursor_name_sizeof
#undef xcb_xfixes_get_cursor_name
#undef xcb_xfixes_get_cursor_name_unchecked
#undef xcb_xfixes_get_cursor_name_name
#undef xcb_xfixes_get_cursor_name_name_length
#undef xcb_xfixes_get_cursor_name_name_end
#undef xcb_xfixes_get_cursor_name_reply
#undef xcb_xfixes_get_cursor_image_and_name_sizeof
#undef xcb_xfixes_get_cursor_image_and_name
#undef xcb_xfixes_get_cursor_image_and_name_unchecked
#undef xcb_xfixes_get_cursor_image_and_name_cursor_image
#undef xcb_xfixes_get_cursor_image_and_name_cursor_image_length
#undef xcb_xfixes_get_cursor_image_and_name_cursor_image_end
#undef xcb_xfixes_get_cursor_image_and_name_name
#undef xcb_xfixes_get_cursor_image_and_name_name_length
#undef xcb_xfixes_get_cursor_image_and_name_name_end
#undef xcb_xfixes_get_cursor_image_and_name_reply
#undef xcb_xfixes_change_cursor_checked
#undef xcb_xfixes_change_cursor
#undef xcb_xfixes_change_cursor_by_name_sizeof
#undef xcb_xfixes_change_cursor_by_name_checked
#undef xcb_xfixes_change_cursor_by_name
#undef xcb_xfixes_change_cursor_by_name_name
#undef xcb_xfixes_change_cursor_by_name_name_length
#undef xcb_xfixes_change_cursor_by_name_name_end
#undef xcb_xfixes_expand_region_checked
#undef xcb_xfixes_expand_region
#undef xcb_xfixes_hide_cursor_checked
#undef xcb_xfixes_hide_cursor
#undef xcb_xfixes_show_cursor_checked
#undef xcb_xfixes_show_cursor
#undef xcb_xfixes_barrier_next
#undef xcb_xfixes_barrier_end
#undef xcb_xfixes_create_pointer_barrier_sizeof
#undef xcb_xfixes_create_pointer_barrier_checked
#undef xcb_xfixes_create_pointer_barrier
#undef xcb_xfixes_create_pointer_barrier_devices
#undef xcb_xfixes_create_pointer_barrier_devices_length
#undef xcb_xfixes_create_pointer_barrier_devices_end
#undef xcb_xfixes_delete_pointer_barrier_checked
#undef xcb_xfixes_delete_pointer_barrier
#undef xcb_xfixes_set_client_disconnect_mode_checked
#undef xcb_xfixes_set_client_disconnect_mode
#undef xcb_xfixes_get_client_disconnect_mode
#undef xcb_xfixes_get_client_disconnect_mode_unchecked
#undef xcb_xfixes_get_client_disconnect_mode_reply
#include <dlfcn.h>
#include <stdio.h>
xcb_xfixes_query_version_cookie_t (*xcb_xfixes_query_version_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, uint32_t, uint32_t);
xcb_xfixes_query_version_cookie_t (*xcb_xfixes_query_version_unchecked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, uint32_t, uint32_t);
xcb_xfixes_query_version_reply_t *(*xcb_xfixes_query_version_reply_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_query_version_cookie_t, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_xfixes_change_save_set_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, uint8_t, uint8_t, uint8_t, xcb_window_t);
xcb_void_cookie_t (*xcb_xfixes_change_save_set_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, uint8_t, uint8_t, uint8_t, xcb_window_t);
xcb_void_cookie_t (*xcb_xfixes_select_selection_input_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint32_t);
xcb_void_cookie_t (*xcb_xfixes_select_selection_input_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_window_t, xcb_atom_t, uint32_t);
xcb_void_cookie_t (*xcb_xfixes_select_cursor_input_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_window_t, uint32_t);
xcb_void_cookie_t (*xcb_xfixes_select_cursor_input_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_window_t, uint32_t);
int (*xcb_xfixes_get_cursor_image_sizeof_dylibloader_wrapper_xcb_xfixes)(const void *);
xcb_xfixes_get_cursor_image_cookie_t (*xcb_xfixes_get_cursor_image_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *);
xcb_xfixes_get_cursor_image_cookie_t (*xcb_xfixes_get_cursor_image_unchecked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *);
uint32_t *(*xcb_xfixes_get_cursor_image_cursor_image_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_image_reply_t *);
int (*xcb_xfixes_get_cursor_image_cursor_image_length_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_image_reply_t *);
xcb_generic_iterator_t (*xcb_xfixes_get_cursor_image_cursor_image_end_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_image_reply_t *);
xcb_xfixes_get_cursor_image_reply_t *(*xcb_xfixes_get_cursor_image_reply_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_get_cursor_image_cookie_t, xcb_generic_error_t **);
void (*xcb_xfixes_region_next_dylibloader_wrapper_xcb_xfixes)(xcb_xfixes_region_iterator_t *);
xcb_generic_iterator_t (*xcb_xfixes_region_end_dylibloader_wrapper_xcb_xfixes)(xcb_xfixes_region_iterator_t);
int (*xcb_xfixes_create_region_sizeof_dylibloader_wrapper_xcb_xfixes)(const void *, uint32_t);
xcb_void_cookie_t (*xcb_xfixes_create_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, uint32_t, const xcb_rectangle_t *);
xcb_void_cookie_t (*xcb_xfixes_create_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, uint32_t, const xcb_rectangle_t *);
xcb_rectangle_t *(*xcb_xfixes_create_region_rectangles_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_create_region_request_t *);
int (*xcb_xfixes_create_region_rectangles_length_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_create_region_request_t *);
xcb_rectangle_iterator_t (*xcb_xfixes_create_region_rectangles_iterator_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_create_region_request_t *);
xcb_void_cookie_t (*xcb_xfixes_create_region_from_bitmap_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_pixmap_t);
xcb_void_cookie_t (*xcb_xfixes_create_region_from_bitmap_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_pixmap_t);
xcb_void_cookie_t (*xcb_xfixes_create_region_from_window_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_window_t, xcb_shape_kind_t);
xcb_void_cookie_t (*xcb_xfixes_create_region_from_window_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_window_t, xcb_shape_kind_t);
xcb_void_cookie_t (*xcb_xfixes_create_region_from_gc_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_gcontext_t);
xcb_void_cookie_t (*xcb_xfixes_create_region_from_gc_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_gcontext_t);
xcb_void_cookie_t (*xcb_xfixes_create_region_from_picture_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_render_picture_t);
xcb_void_cookie_t (*xcb_xfixes_create_region_from_picture_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_render_picture_t);
xcb_void_cookie_t (*xcb_xfixes_destroy_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_destroy_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t);
int (*xcb_xfixes_set_region_sizeof_dylibloader_wrapper_xcb_xfixes)(const void *, uint32_t);
xcb_void_cookie_t (*xcb_xfixes_set_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, uint32_t, const xcb_rectangle_t *);
xcb_void_cookie_t (*xcb_xfixes_set_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, uint32_t, const xcb_rectangle_t *);
xcb_rectangle_t *(*xcb_xfixes_set_region_rectangles_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_set_region_request_t *);
int (*xcb_xfixes_set_region_rectangles_length_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_set_region_request_t *);
xcb_rectangle_iterator_t (*xcb_xfixes_set_region_rectangles_iterator_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_set_region_request_t *);
xcb_void_cookie_t (*xcb_xfixes_copy_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_copy_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_union_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_union_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_intersect_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_intersect_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_subtract_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_subtract_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_invert_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_rectangle_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_invert_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_rectangle_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_translate_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, int16_t, int16_t);
xcb_void_cookie_t (*xcb_xfixes_translate_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, int16_t, int16_t);
xcb_void_cookie_t (*xcb_xfixes_region_extents_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_region_extents_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t);
int (*xcb_xfixes_fetch_region_sizeof_dylibloader_wrapper_xcb_xfixes)(const void *);
xcb_xfixes_fetch_region_cookie_t (*xcb_xfixes_fetch_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t);
xcb_xfixes_fetch_region_cookie_t (*xcb_xfixes_fetch_region_unchecked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t);
xcb_rectangle_t *(*xcb_xfixes_fetch_region_rectangles_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_fetch_region_reply_t *);
int (*xcb_xfixes_fetch_region_rectangles_length_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_fetch_region_reply_t *);
xcb_rectangle_iterator_t (*xcb_xfixes_fetch_region_rectangles_iterator_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_fetch_region_reply_t *);
xcb_xfixes_fetch_region_reply_t *(*xcb_xfixes_fetch_region_reply_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_fetch_region_cookie_t, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_xfixes_set_gc_clip_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_gcontext_t, xcb_xfixes_region_t, int16_t, int16_t);
xcb_void_cookie_t (*xcb_xfixes_set_gc_clip_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_gcontext_t, xcb_xfixes_region_t, int16_t, int16_t);
xcb_void_cookie_t (*xcb_xfixes_set_window_shape_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_window_t, xcb_shape_kind_t, int16_t, int16_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_set_window_shape_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_window_t, xcb_shape_kind_t, int16_t, int16_t, xcb_xfixes_region_t);
xcb_void_cookie_t (*xcb_xfixes_set_picture_clip_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_render_picture_t, xcb_xfixes_region_t, int16_t, int16_t);
xcb_void_cookie_t (*xcb_xfixes_set_picture_clip_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_render_picture_t, xcb_xfixes_region_t, int16_t, int16_t);
int (*xcb_xfixes_set_cursor_name_sizeof_dylibloader_wrapper_xcb_xfixes)(const void *);
xcb_void_cookie_t (*xcb_xfixes_set_cursor_name_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_cursor_t, uint16_t, const char *);
xcb_void_cookie_t (*xcb_xfixes_set_cursor_name_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_cursor_t, uint16_t, const char *);
char *(*xcb_xfixes_set_cursor_name_name_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_set_cursor_name_request_t *);
int (*xcb_xfixes_set_cursor_name_name_length_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_set_cursor_name_request_t *);
xcb_generic_iterator_t (*xcb_xfixes_set_cursor_name_name_end_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_set_cursor_name_request_t *);
int (*xcb_xfixes_get_cursor_name_sizeof_dylibloader_wrapper_xcb_xfixes)(const void *);
xcb_xfixes_get_cursor_name_cookie_t (*xcb_xfixes_get_cursor_name_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_cursor_t);
xcb_xfixes_get_cursor_name_cookie_t (*xcb_xfixes_get_cursor_name_unchecked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_cursor_t);
char *(*xcb_xfixes_get_cursor_name_name_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_name_reply_t *);
int (*xcb_xfixes_get_cursor_name_name_length_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_name_reply_t *);
xcb_generic_iterator_t (*xcb_xfixes_get_cursor_name_name_end_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_name_reply_t *);
xcb_xfixes_get_cursor_name_reply_t *(*xcb_xfixes_get_cursor_name_reply_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_get_cursor_name_cookie_t, xcb_generic_error_t **);
int (*xcb_xfixes_get_cursor_image_and_name_sizeof_dylibloader_wrapper_xcb_xfixes)(const void *);
xcb_xfixes_get_cursor_image_and_name_cookie_t (*xcb_xfixes_get_cursor_image_and_name_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *);
xcb_xfixes_get_cursor_image_and_name_cookie_t (*xcb_xfixes_get_cursor_image_and_name_unchecked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *);
uint32_t *(*xcb_xfixes_get_cursor_image_and_name_cursor_image_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_image_and_name_reply_t *);
int (*xcb_xfixes_get_cursor_image_and_name_cursor_image_length_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_image_and_name_reply_t *);
xcb_generic_iterator_t (*xcb_xfixes_get_cursor_image_and_name_cursor_image_end_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_image_and_name_reply_t *);
char *(*xcb_xfixes_get_cursor_image_and_name_name_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_image_and_name_reply_t *);
int (*xcb_xfixes_get_cursor_image_and_name_name_length_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_image_and_name_reply_t *);
xcb_generic_iterator_t (*xcb_xfixes_get_cursor_image_and_name_name_end_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_get_cursor_image_and_name_reply_t *);
xcb_xfixes_get_cursor_image_and_name_reply_t *(*xcb_xfixes_get_cursor_image_and_name_reply_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_get_cursor_image_and_name_cookie_t, xcb_generic_error_t **);
xcb_void_cookie_t (*xcb_xfixes_change_cursor_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_cursor_t, xcb_cursor_t);
xcb_void_cookie_t (*xcb_xfixes_change_cursor_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_cursor_t, xcb_cursor_t);
int (*xcb_xfixes_change_cursor_by_name_sizeof_dylibloader_wrapper_xcb_xfixes)(const void *);
xcb_void_cookie_t (*xcb_xfixes_change_cursor_by_name_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_cursor_t, uint16_t, const char *);
xcb_void_cookie_t (*xcb_xfixes_change_cursor_by_name_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_cursor_t, uint16_t, const char *);
char *(*xcb_xfixes_change_cursor_by_name_name_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_change_cursor_by_name_request_t *);
int (*xcb_xfixes_change_cursor_by_name_name_length_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_change_cursor_by_name_request_t *);
xcb_generic_iterator_t (*xcb_xfixes_change_cursor_by_name_name_end_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_change_cursor_by_name_request_t *);
xcb_void_cookie_t (*xcb_xfixes_expand_region_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t, uint16_t, uint16_t, uint16_t, uint16_t);
xcb_void_cookie_t (*xcb_xfixes_expand_region_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_region_t, xcb_xfixes_region_t, uint16_t, uint16_t, uint16_t, uint16_t);
xcb_void_cookie_t (*xcb_xfixes_hide_cursor_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_window_t);
xcb_void_cookie_t (*xcb_xfixes_hide_cursor_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_window_t);
xcb_void_cookie_t (*xcb_xfixes_show_cursor_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_window_t);
xcb_void_cookie_t (*xcb_xfixes_show_cursor_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_window_t);
void (*xcb_xfixes_barrier_next_dylibloader_wrapper_xcb_xfixes)(xcb_xfixes_barrier_iterator_t *);
xcb_generic_iterator_t (*xcb_xfixes_barrier_end_dylibloader_wrapper_xcb_xfixes)(xcb_xfixes_barrier_iterator_t);
int (*xcb_xfixes_create_pointer_barrier_sizeof_dylibloader_wrapper_xcb_xfixes)(const void *);
xcb_void_cookie_t (*xcb_xfixes_create_pointer_barrier_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_barrier_t, xcb_window_t, uint16_t, uint16_t, uint16_t, uint16_t, uint32_t, uint16_t, const uint16_t *);
xcb_void_cookie_t (*xcb_xfixes_create_pointer_barrier_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_barrier_t, xcb_window_t, uint16_t, uint16_t, uint16_t, uint16_t, uint32_t, uint16_t, const uint16_t *);
uint16_t *(*xcb_xfixes_create_pointer_barrier_devices_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_create_pointer_barrier_request_t *);
int (*xcb_xfixes_create_pointer_barrier_devices_length_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_create_pointer_barrier_request_t *);
xcb_generic_iterator_t (*xcb_xfixes_create_pointer_barrier_devices_end_dylibloader_wrapper_xcb_xfixes)(const xcb_xfixes_create_pointer_barrier_request_t *);
xcb_void_cookie_t (*xcb_xfixes_delete_pointer_barrier_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_barrier_t);
xcb_void_cookie_t (*xcb_xfixes_delete_pointer_barrier_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_barrier_t);
xcb_void_cookie_t (*xcb_xfixes_set_client_disconnect_mode_checked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, uint32_t);
xcb_void_cookie_t (*xcb_xfixes_set_client_disconnect_mode_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, uint32_t);
xcb_xfixes_get_client_disconnect_mode_cookie_t (*xcb_xfixes_get_client_disconnect_mode_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *);
xcb_xfixes_get_client_disconnect_mode_cookie_t (*xcb_xfixes_get_client_disconnect_mode_unchecked_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *);
xcb_xfixes_get_client_disconnect_mode_reply_t *(*xcb_xfixes_get_client_disconnect_mode_reply_dylibloader_wrapper_xcb_xfixes)(xcb_connection_t *, xcb_xfixes_get_client_disconnect_mode_cookie_t, xcb_generic_error_t **);
int initialize_xcb_xfixes(int verbose) {
  void *handle;
  char *error;
  handle = dlopen("libxcb-xfixes.so.0", RTLD_LAZY);
  if (!handle) {
    if (verbose) {
      fprintf(stderr, "%s\n", dlerror());
    }
    return(1);
  }
  dlerror();
/* xcb_xfixes_query_version */
  *(void **) (&xcb_xfixes_query_version_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_query_version");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_query_version_unchecked */
  *(void **) (&xcb_xfixes_query_version_unchecked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_query_version_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_query_version_reply */
  *(void **) (&xcb_xfixes_query_version_reply_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_query_version_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_change_save_set_checked */
  *(void **) (&xcb_xfixes_change_save_set_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_change_save_set_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_change_save_set */
  *(void **) (&xcb_xfixes_change_save_set_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_change_save_set");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_select_selection_input_checked */
  *(void **) (&xcb_xfixes_select_selection_input_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_select_selection_input_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_select_selection_input */
  *(void **) (&xcb_xfixes_select_selection_input_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_select_selection_input");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_select_cursor_input_checked */
  *(void **) (&xcb_xfixes_select_cursor_input_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_select_cursor_input_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_select_cursor_input */
  *(void **) (&xcb_xfixes_select_cursor_input_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_select_cursor_input");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_sizeof */
  *(void **) (&xcb_xfixes_get_cursor_image_sizeof_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image */
  *(void **) (&xcb_xfixes_get_cursor_image_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_unchecked */
  *(void **) (&xcb_xfixes_get_cursor_image_unchecked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_cursor_image */
  *(void **) (&xcb_xfixes_get_cursor_image_cursor_image_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_cursor_image");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_cursor_image_length */
  *(void **) (&xcb_xfixes_get_cursor_image_cursor_image_length_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_cursor_image_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_cursor_image_end */
  *(void **) (&xcb_xfixes_get_cursor_image_cursor_image_end_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_cursor_image_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_reply */
  *(void **) (&xcb_xfixes_get_cursor_image_reply_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_region_next */
  *(void **) (&xcb_xfixes_region_next_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_region_next");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_region_end */
  *(void **) (&xcb_xfixes_region_end_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_region_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_sizeof */
  *(void **) (&xcb_xfixes_create_region_sizeof_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_checked */
  *(void **) (&xcb_xfixes_create_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region */
  *(void **) (&xcb_xfixes_create_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_rectangles */
  *(void **) (&xcb_xfixes_create_region_rectangles_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_rectangles");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_rectangles_length */
  *(void **) (&xcb_xfixes_create_region_rectangles_length_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_rectangles_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_rectangles_iterator */
  *(void **) (&xcb_xfixes_create_region_rectangles_iterator_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_rectangles_iterator");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_from_bitmap_checked */
  *(void **) (&xcb_xfixes_create_region_from_bitmap_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_from_bitmap_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_from_bitmap */
  *(void **) (&xcb_xfixes_create_region_from_bitmap_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_from_bitmap");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_from_window_checked */
  *(void **) (&xcb_xfixes_create_region_from_window_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_from_window_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_from_window */
  *(void **) (&xcb_xfixes_create_region_from_window_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_from_window");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_from_gc_checked */
  *(void **) (&xcb_xfixes_create_region_from_gc_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_from_gc_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_from_gc */
  *(void **) (&xcb_xfixes_create_region_from_gc_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_from_gc");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_from_picture_checked */
  *(void **) (&xcb_xfixes_create_region_from_picture_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_from_picture_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_region_from_picture */
  *(void **) (&xcb_xfixes_create_region_from_picture_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_region_from_picture");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_destroy_region_checked */
  *(void **) (&xcb_xfixes_destroy_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_destroy_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_destroy_region */
  *(void **) (&xcb_xfixes_destroy_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_destroy_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_region_sizeof */
  *(void **) (&xcb_xfixes_set_region_sizeof_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_region_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_region_checked */
  *(void **) (&xcb_xfixes_set_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_region */
  *(void **) (&xcb_xfixes_set_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_region_rectangles */
  *(void **) (&xcb_xfixes_set_region_rectangles_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_region_rectangles");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_region_rectangles_length */
  *(void **) (&xcb_xfixes_set_region_rectangles_length_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_region_rectangles_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_region_rectangles_iterator */
  *(void **) (&xcb_xfixes_set_region_rectangles_iterator_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_region_rectangles_iterator");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_copy_region_checked */
  *(void **) (&xcb_xfixes_copy_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_copy_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_copy_region */
  *(void **) (&xcb_xfixes_copy_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_copy_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_union_region_checked */
  *(void **) (&xcb_xfixes_union_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_union_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_union_region */
  *(void **) (&xcb_xfixes_union_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_union_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_intersect_region_checked */
  *(void **) (&xcb_xfixes_intersect_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_intersect_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_intersect_region */
  *(void **) (&xcb_xfixes_intersect_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_intersect_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_subtract_region_checked */
  *(void **) (&xcb_xfixes_subtract_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_subtract_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_subtract_region */
  *(void **) (&xcb_xfixes_subtract_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_subtract_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_invert_region_checked */
  *(void **) (&xcb_xfixes_invert_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_invert_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_invert_region */
  *(void **) (&xcb_xfixes_invert_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_invert_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_translate_region_checked */
  *(void **) (&xcb_xfixes_translate_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_translate_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_translate_region */
  *(void **) (&xcb_xfixes_translate_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_translate_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_region_extents_checked */
  *(void **) (&xcb_xfixes_region_extents_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_region_extents_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_region_extents */
  *(void **) (&xcb_xfixes_region_extents_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_region_extents");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_fetch_region_sizeof */
  *(void **) (&xcb_xfixes_fetch_region_sizeof_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_fetch_region_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_fetch_region */
  *(void **) (&xcb_xfixes_fetch_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_fetch_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_fetch_region_unchecked */
  *(void **) (&xcb_xfixes_fetch_region_unchecked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_fetch_region_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_fetch_region_rectangles */
  *(void **) (&xcb_xfixes_fetch_region_rectangles_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_fetch_region_rectangles");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_fetch_region_rectangles_length */
  *(void **) (&xcb_xfixes_fetch_region_rectangles_length_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_fetch_region_rectangles_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_fetch_region_rectangles_iterator */
  *(void **) (&xcb_xfixes_fetch_region_rectangles_iterator_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_fetch_region_rectangles_iterator");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_fetch_region_reply */
  *(void **) (&xcb_xfixes_fetch_region_reply_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_fetch_region_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_gc_clip_region_checked */
  *(void **) (&xcb_xfixes_set_gc_clip_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_gc_clip_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_gc_clip_region */
  *(void **) (&xcb_xfixes_set_gc_clip_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_gc_clip_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_window_shape_region_checked */
  *(void **) (&xcb_xfixes_set_window_shape_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_window_shape_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_window_shape_region */
  *(void **) (&xcb_xfixes_set_window_shape_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_window_shape_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_picture_clip_region_checked */
  *(void **) (&xcb_xfixes_set_picture_clip_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_picture_clip_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_picture_clip_region */
  *(void **) (&xcb_xfixes_set_picture_clip_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_picture_clip_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_cursor_name_sizeof */
  *(void **) (&xcb_xfixes_set_cursor_name_sizeof_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_cursor_name_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_cursor_name_checked */
  *(void **) (&xcb_xfixes_set_cursor_name_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_cursor_name_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_cursor_name */
  *(void **) (&xcb_xfixes_set_cursor_name_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_cursor_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_cursor_name_name */
  *(void **) (&xcb_xfixes_set_cursor_name_name_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_cursor_name_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_cursor_name_name_length */
  *(void **) (&xcb_xfixes_set_cursor_name_name_length_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_cursor_name_name_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_cursor_name_name_end */
  *(void **) (&xcb_xfixes_set_cursor_name_name_end_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_cursor_name_name_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_name_sizeof */
  *(void **) (&xcb_xfixes_get_cursor_name_sizeof_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_name_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_name */
  *(void **) (&xcb_xfixes_get_cursor_name_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_name_unchecked */
  *(void **) (&xcb_xfixes_get_cursor_name_unchecked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_name_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_name_name */
  *(void **) (&xcb_xfixes_get_cursor_name_name_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_name_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_name_name_length */
  *(void **) (&xcb_xfixes_get_cursor_name_name_length_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_name_name_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_name_name_end */
  *(void **) (&xcb_xfixes_get_cursor_name_name_end_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_name_name_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_name_reply */
  *(void **) (&xcb_xfixes_get_cursor_name_reply_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_name_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_and_name_sizeof */
  *(void **) (&xcb_xfixes_get_cursor_image_and_name_sizeof_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_and_name_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_and_name */
  *(void **) (&xcb_xfixes_get_cursor_image_and_name_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_and_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_and_name_unchecked */
  *(void **) (&xcb_xfixes_get_cursor_image_and_name_unchecked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_and_name_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_and_name_cursor_image */
  *(void **) (&xcb_xfixes_get_cursor_image_and_name_cursor_image_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_and_name_cursor_image");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_and_name_cursor_image_length */
  *(void **) (&xcb_xfixes_get_cursor_image_and_name_cursor_image_length_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_and_name_cursor_image_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_and_name_cursor_image_end */
  *(void **) (&xcb_xfixes_get_cursor_image_and_name_cursor_image_end_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_and_name_cursor_image_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_and_name_name */
  *(void **) (&xcb_xfixes_get_cursor_image_and_name_name_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_and_name_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_and_name_name_length */
  *(void **) (&xcb_xfixes_get_cursor_image_and_name_name_length_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_and_name_name_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_and_name_name_end */
  *(void **) (&xcb_xfixes_get_cursor_image_and_name_name_end_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_and_name_name_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_cursor_image_and_name_reply */
  *(void **) (&xcb_xfixes_get_cursor_image_and_name_reply_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_cursor_image_and_name_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_change_cursor_checked */
  *(void **) (&xcb_xfixes_change_cursor_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_change_cursor_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_change_cursor */
  *(void **) (&xcb_xfixes_change_cursor_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_change_cursor");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_change_cursor_by_name_sizeof */
  *(void **) (&xcb_xfixes_change_cursor_by_name_sizeof_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_change_cursor_by_name_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_change_cursor_by_name_checked */
  *(void **) (&xcb_xfixes_change_cursor_by_name_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_change_cursor_by_name_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_change_cursor_by_name */
  *(void **) (&xcb_xfixes_change_cursor_by_name_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_change_cursor_by_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_change_cursor_by_name_name */
  *(void **) (&xcb_xfixes_change_cursor_by_name_name_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_change_cursor_by_name_name");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_change_cursor_by_name_name_length */
  *(void **) (&xcb_xfixes_change_cursor_by_name_name_length_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_change_cursor_by_name_name_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_change_cursor_by_name_name_end */
  *(void **) (&xcb_xfixes_change_cursor_by_name_name_end_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_change_cursor_by_name_name_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_expand_region_checked */
  *(void **) (&xcb_xfixes_expand_region_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_expand_region_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_expand_region */
  *(void **) (&xcb_xfixes_expand_region_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_expand_region");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_hide_cursor_checked */
  *(void **) (&xcb_xfixes_hide_cursor_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_hide_cursor_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_hide_cursor */
  *(void **) (&xcb_xfixes_hide_cursor_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_hide_cursor");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_show_cursor_checked */
  *(void **) (&xcb_xfixes_show_cursor_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_show_cursor_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_show_cursor */
  *(void **) (&xcb_xfixes_show_cursor_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_show_cursor");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_barrier_next */
  *(void **) (&xcb_xfixes_barrier_next_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_barrier_next");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_barrier_end */
  *(void **) (&xcb_xfixes_barrier_end_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_barrier_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_pointer_barrier_sizeof */
  *(void **) (&xcb_xfixes_create_pointer_barrier_sizeof_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_pointer_barrier_sizeof");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_pointer_barrier_checked */
  *(void **) (&xcb_xfixes_create_pointer_barrier_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_pointer_barrier_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_pointer_barrier */
  *(void **) (&xcb_xfixes_create_pointer_barrier_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_pointer_barrier");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_pointer_barrier_devices */
  *(void **) (&xcb_xfixes_create_pointer_barrier_devices_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_pointer_barrier_devices");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_pointer_barrier_devices_length */
  *(void **) (&xcb_xfixes_create_pointer_barrier_devices_length_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_pointer_barrier_devices_length");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_create_pointer_barrier_devices_end */
  *(void **) (&xcb_xfixes_create_pointer_barrier_devices_end_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_create_pointer_barrier_devices_end");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_delete_pointer_barrier_checked */
  *(void **) (&xcb_xfixes_delete_pointer_barrier_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_delete_pointer_barrier_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_delete_pointer_barrier */
  *(void **) (&xcb_xfixes_delete_pointer_barrier_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_delete_pointer_barrier");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_client_disconnect_mode_checked */
  *(void **) (&xcb_xfixes_set_client_disconnect_mode_checked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_client_disconnect_mode_checked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_set_client_disconnect_mode */
  *(void **) (&xcb_xfixes_set_client_disconnect_mode_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_set_client_disconnect_mode");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_client_disconnect_mode */
  *(void **) (&xcb_xfixes_get_client_disconnect_mode_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_client_disconnect_mode");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_client_disconnect_mode_unchecked */
  *(void **) (&xcb_xfixes_get_client_disconnect_mode_unchecked_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_client_disconnect_mode_unchecked");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
/* xcb_xfixes_get_client_disconnect_mode_reply */
  *(void **) (&xcb_xfixes_get_client_disconnect_mode_reply_dylibloader_wrapper_xcb_xfixes) = dlsym(handle, "xcb_xfixes_get_client_disconnect_mode_reply");
  if (verbose) {
    error = dlerror();
    if (error != NULL) {
      fprintf(stderr, "%s\n", error);
      return(1);
    }
  }
return 0;
}
