#ifndef DYLIBLOAD_WRAPPER_EGL
#define DYLIBLOAD_WRAPPER_EGL
/* This file is generated. Do not edit!
   see https://github.com/hpvb/dynload-wrapper (patched) for details
   generated by scripts/generate-wrapper.py 0.5
   flags: scripts/generate-wrapper.py --include include/EGL/egl.h --sys-include <EGL/egl.h> --soname libEGL.so.1 --init-name egl --output-header include_gen/egl-so_wrap.h --output-implementation src_gen/egl-so_wrap.c --ignore-other --include-dir include
*/
#include <stdint.h>

#define eglChooseConfig eglChooseConfig_dylibloader_orig_egl
#define eglCopyBuffers eglCopyBuffers_dylibloader_orig_egl
#define eglCreateContext eglCreateContext_dylibloader_orig_egl
#define eglCreatePbufferSurface eglCreatePbufferSurface_dylibloader_orig_egl
#define eglCreatePixmapSurface eglCreatePixmapSurface_dylibloader_orig_egl
#define eglCreateWindowSurface eglCreateWindowSurface_dylibloader_orig_egl
#define eglDestroyContext eglDestroyContext_dylibloader_orig_egl
#define eglDestroySurface eglDestroySurface_dylibloader_orig_egl
#define eglGetConfigAttrib eglGetConfigAttrib_dylibloader_orig_egl
#define eglGetConfigs eglGetConfigs_dylibloader_orig_egl
#define eglGetCurrentDisplay eglGetCurrentDisplay_dylibloader_orig_egl
#define eglGetCurrentSurface eglGetCurrentSurface_dylibloader_orig_egl
#define eglGetDisplay eglGetDisplay_dylibloader_orig_egl
#define eglGetError eglGetError_dylibloader_orig_egl
#define eglGetProcAddress eglGetProcAddress_dylibloader_orig_egl
#define eglInitialize eglInitialize_dylibloader_orig_egl
#define eglMakeCurrent eglMakeCurrent_dylibloader_orig_egl
#define eglQueryContext eglQueryContext_dylibloader_orig_egl
#define eglQueryString eglQueryString_dylibloader_orig_egl
#define eglQuerySurface eglQuerySurface_dylibloader_orig_egl
#define eglSwapBuffers eglSwapBuffers_dylibloader_orig_egl
#define eglTerminate eglTerminate_dylibloader_orig_egl
#define eglWaitGL eglWaitGL_dylibloader_orig_egl
#define eglWaitNative eglWaitNative_dylibloader_orig_egl
#define eglBindTexImage eglBindTexImage_dylibloader_orig_egl
#define eglReleaseTexImage eglReleaseTexImage_dylibloader_orig_egl
#define eglSurfaceAttrib eglSurfaceAttrib_dylibloader_orig_egl
#define eglSwapInterval eglSwapInterval_dylibloader_orig_egl
#define eglBindAPI eglBindAPI_dylibloader_orig_egl
#define eglQueryAPI eglQueryAPI_dylibloader_orig_egl
#define eglCreatePbufferFromClientBuffer eglCreatePbufferFromClientBuffer_dylibloader_orig_egl
#define eglReleaseThread eglReleaseThread_dylibloader_orig_egl
#define eglWaitClient eglWaitClient_dylibloader_orig_egl
#define eglGetCurrentContext eglGetCurrentContext_dylibloader_orig_egl
#define eglCreateSync eglCreateSync_dylibloader_orig_egl
#define eglDestroySync eglDestroySync_dylibloader_orig_egl
#define eglClientWaitSync eglClientWaitSync_dylibloader_orig_egl
#define eglGetSyncAttrib eglGetSyncAttrib_dylibloader_orig_egl
#define eglCreateImage eglCreateImage_dylibloader_orig_egl
#define eglDestroyImage eglDestroyImage_dylibloader_orig_egl
#define eglGetPlatformDisplay eglGetPlatformDisplay_dylibloader_orig_egl
#define eglCreatePlatformWindowSurface eglCreatePlatformWindowSurface_dylibloader_orig_egl
#define eglCreatePlatformPixmapSurface eglCreatePlatformPixmapSurface_dylibloader_orig_egl
#define eglWaitSync eglWaitSync_dylibloader_orig_egl
#include <EGL/egl.h>
#undef eglChooseConfig
#undef eglCopyBuffers
#undef eglCreateContext
#undef eglCreatePbufferSurface
#undef eglCreatePixmapSurface
#undef eglCreateWindowSurface
#undef eglDestroyContext
#undef eglDestroySurface
#undef eglGetConfigAttrib
#undef eglGetConfigs
#undef eglGetCurrentDisplay
#undef eglGetCurrentSurface
#undef eglGetDisplay
#undef eglGetError
#undef eglGetProcAddress
#undef eglInitialize
#undef eglMakeCurrent
#undef eglQueryContext
#undef eglQueryString
#undef eglQuerySurface
#undef eglSwapBuffers
#undef eglTerminate
#undef eglWaitGL
#undef eglWaitNative
#undef eglBindTexImage
#undef eglReleaseTexImage
#undef eglSurfaceAttrib
#undef eglSwapInterval
#undef eglBindAPI
#undef eglQueryAPI
#undef eglCreatePbufferFromClientBuffer
#undef eglReleaseThread
#undef eglWaitClient
#undef eglGetCurrentContext
#undef eglCreateSync
#undef eglDestroySync
#undef eglClientWaitSync
#undef eglGetSyncAttrib
#undef eglCreateImage
#undef eglDestroyImage
#undef eglGetPlatformDisplay
#undef eglCreatePlatformWindowSurface
#undef eglCreatePlatformPixmapSurface
#undef eglWaitSync
#ifdef __cplusplus
extern "C" {
#endif
#define eglChooseConfig eglChooseConfig_dylibloader_wrapper_egl
#define eglCopyBuffers eglCopyBuffers_dylibloader_wrapper_egl
#define eglCreateContext eglCreateContext_dylibloader_wrapper_egl
#define eglCreatePbufferSurface eglCreatePbufferSurface_dylibloader_wrapper_egl
#define eglCreatePixmapSurface eglCreatePixmapSurface_dylibloader_wrapper_egl
#define eglCreateWindowSurface eglCreateWindowSurface_dylibloader_wrapper_egl
#define eglDestroyContext eglDestroyContext_dylibloader_wrapper_egl
#define eglDestroySurface eglDestroySurface_dylibloader_wrapper_egl
#define eglGetConfigAttrib eglGetConfigAttrib_dylibloader_wrapper_egl
#define eglGetConfigs eglGetConfigs_dylibloader_wrapper_egl
#define eglGetCurrentDisplay eglGetCurrentDisplay_dylibloader_wrapper_egl
#define eglGetCurrentSurface eglGetCurrentSurface_dylibloader_wrapper_egl
#define eglGetDisplay eglGetDisplay_dylibloader_wrapper_egl
#define eglGetError eglGetError_dylibloader_wrapper_egl
#define eglGetProcAddress eglGetProcAddress_dylibloader_wrapper_egl
#define eglInitialize eglInitialize_dylibloader_wrapper_egl
#define eglMakeCurrent eglMakeCurrent_dylibloader_wrapper_egl
#define eglQueryContext eglQueryContext_dylibloader_wrapper_egl
#define eglQueryString eglQueryString_dylibloader_wrapper_egl
#define eglQuerySurface eglQuerySurface_dylibloader_wrapper_egl
#define eglSwapBuffers eglSwapBuffers_dylibloader_wrapper_egl
#define eglTerminate eglTerminate_dylibloader_wrapper_egl
#define eglWaitGL eglWaitGL_dylibloader_wrapper_egl
#define eglWaitNative eglWaitNative_dylibloader_wrapper_egl
#define eglBindTexImage eglBindTexImage_dylibloader_wrapper_egl
#define eglReleaseTexImage eglReleaseTexImage_dylibloader_wrapper_egl
#define eglSurfaceAttrib eglSurfaceAttrib_dylibloader_wrapper_egl
#define eglSwapInterval eglSwapInterval_dylibloader_wrapper_egl
#define eglBindAPI eglBindAPI_dylibloader_wrapper_egl
#define eglQueryAPI eglQueryAPI_dylibloader_wrapper_egl
#define eglCreatePbufferFromClientBuffer eglCreatePbufferFromClientBuffer_dylibloader_wrapper_egl
#define eglReleaseThread eglReleaseThread_dylibloader_wrapper_egl
#define eglWaitClient eglWaitClient_dylibloader_wrapper_egl
#define eglGetCurrentContext eglGetCurrentContext_dylibloader_wrapper_egl
#define eglCreateSync eglCreateSync_dylibloader_wrapper_egl
#define eglDestroySync eglDestroySync_dylibloader_wrapper_egl
#define eglClientWaitSync eglClientWaitSync_dylibloader_wrapper_egl
#define eglGetSyncAttrib eglGetSyncAttrib_dylibloader_wrapper_egl
#define eglCreateImage eglCreateImage_dylibloader_wrapper_egl
#define eglDestroyImage eglDestroyImage_dylibloader_wrapper_egl
#define eglGetPlatformDisplay eglGetPlatformDisplay_dylibloader_wrapper_egl
#define eglCreatePlatformWindowSurface eglCreatePlatformWindowSurface_dylibloader_wrapper_egl
#define eglCreatePlatformPixmapSurface eglCreatePlatformPixmapSurface_dylibloader_wrapper_egl
#define eglWaitSync eglWaitSync_dylibloader_wrapper_egl
extern EGLBoolean (*eglChooseConfig_dylibloader_wrapper_egl)(EGLDisplay, const EGLint *, EGLConfig *, EGLint, EGLint *);
extern EGLBoolean (*eglCopyBuffers_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLNativePixmapType);
extern EGLContext (*eglCreateContext_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, EGLContext, const EGLint *);
extern EGLSurface (*eglCreatePbufferSurface_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, const EGLint *);
extern EGLSurface (*eglCreatePixmapSurface_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, EGLNativePixmapType, const EGLint *);
extern EGLSurface (*eglCreateWindowSurface_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, EGLNativeWindowType, const EGLint *);
extern EGLBoolean (*eglDestroyContext_dylibloader_wrapper_egl)(EGLDisplay, EGLContext);
extern EGLBoolean (*eglDestroySurface_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface);
extern EGLBoolean (*eglGetConfigAttrib_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, EGLint, EGLint *);
extern EGLBoolean (*eglGetConfigs_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig *, EGLint, EGLint *);
extern EGLDisplay (*eglGetCurrentDisplay_dylibloader_wrapper_egl)(void);
extern EGLSurface (*eglGetCurrentSurface_dylibloader_wrapper_egl)(EGLint);
extern EGLDisplay (*eglGetDisplay_dylibloader_wrapper_egl)(EGLNativeDisplayType);
extern EGLint (*eglGetError_dylibloader_wrapper_egl)(void);
extern __eglMustCastToProperFunctionPointerType (*eglGetProcAddress_dylibloader_wrapper_egl)(const char *);
extern EGLBoolean (*eglInitialize_dylibloader_wrapper_egl)(EGLDisplay, EGLint *, EGLint *);
extern EGLBoolean (*eglMakeCurrent_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLSurface, EGLContext);
extern EGLBoolean (*eglQueryContext_dylibloader_wrapper_egl)(EGLDisplay, EGLContext, EGLint, EGLint *);
extern const char *(*eglQueryString_dylibloader_wrapper_egl)(EGLDisplay, EGLint);
extern EGLBoolean (*eglQuerySurface_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLint, EGLint *);
extern EGLBoolean (*eglSwapBuffers_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface);
extern EGLBoolean (*eglTerminate_dylibloader_wrapper_egl)(EGLDisplay);
extern EGLBoolean (*eglWaitGL_dylibloader_wrapper_egl)(void);
extern EGLBoolean (*eglWaitNative_dylibloader_wrapper_egl)(EGLint);
extern EGLBoolean (*eglBindTexImage_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLint);
extern EGLBoolean (*eglReleaseTexImage_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLint);
extern EGLBoolean (*eglSurfaceAttrib_dylibloader_wrapper_egl)(EGLDisplay, EGLSurface, EGLint, EGLint);
extern EGLBoolean (*eglSwapInterval_dylibloader_wrapper_egl)(EGLDisplay, EGLint);
extern EGLBoolean (*eglBindAPI_dylibloader_wrapper_egl)(EGLenum);
extern EGLenum (*eglQueryAPI_dylibloader_wrapper_egl)(void);
extern EGLSurface (*eglCreatePbufferFromClientBuffer_dylibloader_wrapper_egl)(EGLDisplay, EGLenum, EGLClientBuffer, EGLConfig, const EGLint *);
extern EGLBoolean (*eglReleaseThread_dylibloader_wrapper_egl)(void);
extern EGLBoolean (*eglWaitClient_dylibloader_wrapper_egl)(void);
extern EGLContext (*eglGetCurrentContext_dylibloader_wrapper_egl)(void);
extern EGLSync (*eglCreateSync_dylibloader_wrapper_egl)(EGLDisplay, EGLenum, const EGLAttrib *);
extern EGLBoolean (*eglDestroySync_dylibloader_wrapper_egl)(EGLDisplay, EGLSync);
extern EGLint (*eglClientWaitSync_dylibloader_wrapper_egl)(EGLDisplay, EGLSync, EGLint, EGLTime);
extern EGLBoolean (*eglGetSyncAttrib_dylibloader_wrapper_egl)(EGLDisplay, EGLSync, EGLint, EGLAttrib *);
extern EGLImage (*eglCreateImage_dylibloader_wrapper_egl)(EGLDisplay, EGLContext, EGLenum, EGLClientBuffer, const EGLAttrib *);
extern EGLBoolean (*eglDestroyImage_dylibloader_wrapper_egl)(EGLDisplay, EGLImage);
extern EGLDisplay (*eglGetPlatformDisplay_dylibloader_wrapper_egl)(EGLenum, void *, const EGLAttrib *);
extern EGLSurface (*eglCreatePlatformWindowSurface_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, void *, const EGLAttrib *);
extern EGLSurface (*eglCreatePlatformPixmapSurface_dylibloader_wrapper_egl)(EGLDisplay, EGLConfig, void *, const EGLAttrib *);
extern EGLBoolean (*eglWaitSync_dylibloader_wrapper_egl)(EGLDisplay, EGLSync, EGLint);
int initialize_egl(int verbose);
#ifdef __cplusplus
}
#endif
#endif
